-- ============================================================================
-- Seed batch 7: 125 globally-applicable debate questions (PL + EN) + smaczki
-- ----------------------------------------------------------------------------
-- Generated 2026-07-03. Second file of the 268-question drop (126 + 125 + 17)
-- that brings the catalog from 732 to exactly 1000. Same rules and mechanics
-- as batch 6 (see 20260703130000): universal dilemmas, ~50/50 splits, variable
-- smaczki (nullable a2/a3 pairs; a few punchy questions carry just one hook).
-- Deduplicated against all 750 historical EN texts + batch 6.
-- Idempotent: keyed on EN text.
-- Topics in this file: Environment (14), Lifestyle (12), Friendship (12),
-- Freedom (5), Culture (12), Society (11), Ethics (10), Money (9), Work (9),
-- Technology (10), Health (10), Justice (7), Relationships (4).
-- ============================================================================

begin;

do $$
declare
  r   record;
  qid uuid;
  s1  uuid;
  s2  uuid;
  s3  uuid;
begin
  for r in
    select * from (values
      ('Environment', false,
       'Should a river or an ancient forest have rights like a person?',
       'Czy rzeka albo stary las powinny mieć prawa jak człowiek?',
       'They can be harmed but have no voice', 'Można je skrzywdzić, a głosu nie mają',
       'Rights come with duties', 'Prawa idą w parze z obowiązkami',
       null, null),
      ('Environment', false,
       'Is paying to offset your flights just buying a clear conscience?',
       'Czy płacenie za kompensację lotów to kupowanie sobie czystego sumienia?',
       'The CO2 flew with you anyway', 'Dwutlenek i tak z tobą leciał',
       'Still better than doing nothing', 'Wciąż lepsze niż nic',
       null, null),
      ('Environment', false,
       'Is walking past litter you could pick up a small moral failure?',
       'Czy przejście obok śmiecia, który mogłeś podnieść, to mała moralna porażka?',
       'Someone has to be first', 'Ktoś musi być pierwszy',
       'You didn''t drop it', 'To nie ty go rzuciłeś',
       null, null),
      ('Environment', false,
       'Can a nature documentary replace being in nature?',
       'Czy film przyrodniczy może zastąpić bycie w naturze?',
       'You''ll never dive that deep yourself', 'Sam nigdy nie zanurkujesz tak głęboko',
       'A screen has no wind', 'Ekran nie wieje wiatrem',
       null, null),
      ('Environment', false,
       'Is growing your own vegetables worth the trouble?',
       'Czy uprawianie własnych warzyw jest warte zachodu?',
       'The tastiest hours you''ll ever spend', 'Najsmaczniejsze godziny twojego życia',
       'The shop is cheaper and faster', 'W sklepie taniej i szybciej',
       null, null),
      ('Environment', false,
       'Would you give up flying if everyone else had to as well?',
       'Czy zrezygnowałbyś z latania, gdyby wszyscy inni też musieli?',
       'Fair rules make sacrifice easy', 'Przy równych zasadach łatwiej o wyrzeczenia',
       'The world would shrink back', 'Świat znów by się skurczył',
       null, null),
      ('Environment', false,
       'Is keeping cut flowers a strange way to love nature?',
       'Czy trzymanie ciętych kwiatów to dziwny sposób kochania natury?',
       'You love them as they die', 'Kochasz je, patrząc, jak umierają',
       'Beauty is worth a short life', 'Piękno bywa warte krótkiego życia',
       null, null),
      ('Environment', false,
       'Is a perfect lawn a monument to wasted effort?',
       'Czy idealny trawnik to pomnik zmarnowanego wysiłku?',
       'Green concrete', 'Zielony beton',
       'Order you can walk on', 'Porządek, po którym można chodzić',
       null, null),
      ('Environment', false,
       'Should we stop eating wild-caught fish now that farming exists?',
       'Czy powinniśmy przestać jeść dzikie ryby, skoro istnieją hodowle?',
       'The ocean is not a pantry', 'Ocean to nie spiżarnia',
       'Farms have their own sins', 'Hodowle mają własne grzechy',
       null, null),
      ('Environment', false,
       'Is loving nature while hating bugs hypocrisy?',
       'Czy kochanie natury przy nienawiści do robaków to hipokryzja?',
       'Nature is mostly bugs', 'Natura to głównie owady',
       'Love has degrees', 'Miłość ma stopnie',
       null, null),
      ('Environment', false,
       'Is camping with all the comforts still really camping?',
       'Czy biwak ze wszystkimi wygodami to jeszcze biwak?',
       'Comfort is a wall against nature', 'Wygoda to ściana odgradzająca od natury',
       'Misery is not a virtue', 'Niewygoda to nie cnota',
       null, null),
      ('Environment', false,
       'Would you accept a wilder, messier city if it meant more nature?',
       'Czy zaakceptowałbyś dziksze, mniej uporządkowane miasto w zamian za więcej natury?',
       'Let the city breathe', 'Pozwól miastu oddychać',
       'Mess invites decay', 'Nieład zaprasza rozkład',
       null, null),
      ('Environment', false,
       'Can you grieve a species you never saw?',
       'Czy można opłakiwać gatunek, którego nigdy się nie widziało?',
       'Every loss shrinks the world', 'Każda strata zmniejsza świat',
       'You can''t miss a stranger', 'Nie tęskni się za obcym',
       null, null),
      ('Environment', false,
       'Is buying secondhand always the more ethical choice?',
       'Czy kupowanie z drugiej ręki to zawsze bardziej etyczny wybór?',
       'The greenest product already exists', 'Najbardziej ekologiczna rzecz już istnieje',
       'Someone has to buy new', 'Ktoś musi kupować nowe',
       null, null),
      ('Lifestyle', false,
       'Is traveling alone better than traveling with friends?',
       'Czy podróżowanie samemu jest lepsze niż z przyjaciółmi?',
       'The trip answers only to you', 'Podróż słucha tylko ciebie',
       'Joy shared is joy doubled', 'Radość dzielona to radość podwójna',
       null, null),
      ('Lifestyle', false,
       'Are souvenirs just future clutter?',
       'Czy pamiątki z podróży to przyszłe graty?',
       'Dust collectors with memories', 'Łapacze kurzu ze wspomnieniami',
       'Objects hold places inside them', 'Przedmioty przechowują w sobie miejsca',
       null, null),
      ('Lifestyle', false,
       'Is a holiday spent doing nothing a holiday wasted?',
       'Czy urlop spędzony na nicnierobieniu to urlop zmarnowany?',
       'You can rest at home for free', 'Odpoczywać możesz w domu za darmo',
       'Doing nothing IS the luxury', 'Nicnierobienie to właśnie ten luksus',
       null, null),
      ('Lifestyle', false,
       'Is minimalism a luxury only the comfortable can afford?',
       'Czy minimalizm to luksus, na który stać tylko zamożnych?',
       'The poor can''t risk owning less', 'Biedny nie może ryzykować posiadania mniej',
       '"Less" is a choice open to anyone', '„Mniej" to wybór dostępny każdemu',
       null, null),
      ('Lifestyle', false,
       'Does turning dreams into a checklist kill them?',
       'Czy zamienianie marzeń w listę do odhaczenia je zabija?',
       'A dream with a deadline is a task', 'Marzenie z terminem to zadanie',
       'Unwritten dreams evaporate', 'Niezapisane marzenia wyparowują',
       null, null),
      ('Lifestyle', false,
       'Is wearing the same outfit every day a superpower rather than laziness?',
       'Czy noszenie codziennie tego samego zestawu ubrań to supermoc, a nie lenistwo?',
       'One decision less, forever', 'Jedna decyzja mniej, na zawsze',
       'Clothes are a language — you''ve gone mute', 'Ubrania to język — a ty zamilkłeś',
       null, null),
      ('Lifestyle', false,
       'Is an adult sleeping with a childhood plush toy nothing to hide?',
       'Czy dorosły śpiący z pluszakiem z dzieciństwa nie ma czego ukrywać?',
       'Comfort needs no license', 'Ukojenie nie potrzebuje licencji',
       'Some things are for growing out of', 'Z niektórych rzeczy się wyrasta',
       null, null),
      ('Lifestyle', false,
       'Can you claim to know a country after a week''s holiday there?',
       'Czy można twierdzić, że zna się kraj po tygodniu wakacji?',
       'You met its airport and its beach', 'Poznałeś jego lotnisko i plażę',
       'A week with open eyes counts', 'Tydzień z otwartymi oczami się liczy',
       null, null),
      ('Lifestyle', false,
       'When visiting friends in another city, is booking a hotel an insult?',
       'Czy rezerwując hotel u przyjaciół w innym mieście, robisz im przykrość?',
       'Their sofa is an embrace', 'Ich kanapa to uścisk',
       'Guests, like fish, stink on day three', 'Gość i ryba trzeciego dnia cuchnie',
       null, null),
      ('Lifestyle', false,
       'Is eating alone at a restaurant a pleasure everyone should learn?',
       'Czy jedzenie samemu w restauracji to przyjemność, której warto się nauczyć?',
       'A table for one is a throne', 'Stolik dla jednego to tron',
       'Meals are made of company', 'Posiłki robi się z towarzystwa',
       null, null),
      ('Lifestyle', false,
       'Should everyone keep a hobby they''re bad at?',
       'Czy każdy powinien mieć hobby, w którym jest słaby?',
       'Fun lives where pressure ends', 'Frajda mieszka tam, gdzie kończy się presja',
       'Time is too scarce for mediocrity', 'Czas jest za krótki na przeciętność',
       null, null),
      ('Lifestyle', false,
       'Does a good weekend need a plan?',
       'Czy dobry weekend potrzebuje planu?',
       'Freedom favors the prepared', 'Wolność sprzyja przygotowanym',
       'Plans are weekday things', 'Plany to sprawa dni roboczych',
       null, null),
      ('Friendship', false,
       'Should dinner guests help with the washing up?',
       'Czy goście po kolacji powinni pomóc w zmywaniu?',
       'Shared mess, shared hands', 'Wspólny bałagan, wspólne ręce',
       'A guest is not staff', 'Gość to nie obsługa',
       null, null),
      ('Friendship', false,
       'Is bringing an uninvited plus-one to a party a serious offense?',
       'Czy przyprowadzenie niezapowiedzianej osoby na imprezę to poważne przewinienie?',
       'You rewrote their guest list', 'Przepisałeś cudzą listę gości',
       'More people, more party', 'Więcej ludzi, więcej imprezy',
       null, null),
      ('Friendship', false,
       'Can a friendship survive one of you getting rich?',
       'Czy przyjaźń przetrwa, gdy jedno z was się wzbogaci?',
       'Money changes the weather', 'Pieniądze zmieniają pogodę między ludźmi',
       'Real friends don''t check wallets', 'Prawdziwi przyjaciele nie zaglądają do portfeli',
       null, null),
      ('Friendship', false,
       'Should you tell a friend their new business idea is bad?',
       'Czy powiedzieć przyjacielowi, że jego nowy pomysł na biznes jest zły?',
       'Better you than the market', 'Lepiej ty niż rynek',
       'Dreams die from friendly fire', 'Marzenia giną od przyjacielskiego ognia',
       null, null),
      ('Friendship', false,
       'Is an old friend you never see still a friend?',
       'Czy stary przyjaciel, którego nigdy nie widujesz, to nadal przyjaciel?',
       'Roots don''t need daily watering', 'Korzenie nie potrzebują codziennego podlewania',
       'Friendship is a verb', 'Przyjaźń to czasownik',
       null, null),
      ('Friendship', false,
       'Is it okay to have a friend you only ever complain to?',
       'Czy można mieć przyjaciela tylko do narzekania?',
       'Venting keeps you sane', 'Wygadanie się trzyma cię w pionie',
       'You''ve made them a dumpster', 'Zrobiłeś z niego śmietnik',
       null, null),
      ('Friendship', false,
       'Should a friend''s secret die with you even after the friendship ends?',
       'Czy sekret przyjaciela powinien umrzeć z tobą, nawet gdy przyjaźń się skończy?',
       'The secret didn''t break up with you', 'Sekret się z tobą nie rozstał',
       'Loyalty has an expiry date', 'Lojalność ma termin ważności',
       null, null),
      ('Friendship', false,
       'Is teasing the truest sign of friendship?',
       'Czy dogryzanie to najprawdziwszy znak przyjaźni?',
       'We only roast the ones we love', 'Dogryzamy tylko tym, których kochamy',
       'Some jokes leave bruises', 'Niektóre żarty zostawiają siniaki',
       null, null),
      ('Friendship', false,
       'Should you visit a friend in hospital even when they say not to come?',
       'Czy odwiedzić przyjaciela w szpitalu, nawet gdy prosi, by nie przychodzić?',
       '"Don''t come" often means "come"', '„Nie przychodź" często znaczy „przyjdź"',
       'Respect their wish, not your guilt', 'Uszanuj jego wolę, nie swoje wyrzuty',
       null, null),
      ('Friendship', false,
       'Can friendships made after forty be as deep as childhood ones?',
       'Czy przyjaźnie zawarte po czterdziestce mogą być tak głębokie jak te z dzieciństwa?',
       'Shared history can''t be bought', 'Wspólnej historii nie da się kupić',
       'Depth is honesty, not years', 'Głębia to szczerość, nie staż',
       null, null),
      ('Friendship', false,
       'Is keeping score of who calls first poisoning a friendship?',
       'Czy liczenie, kto dzwoni pierwszy, zatruwa przyjaźń?',
       'Scoreboards kill affection', 'Tablice wyników zabijają czułość',
       'A one-way road wears you out', 'Droga jednokierunkowa męczy',
       null, null),
      ('Friendship', false,
       'Is a group of three friends always secretly a two-plus-one?',
       'Czy trójka przyjaciół to zawsze po cichu dwójka plus jeden?',
       'Someone is always the bridge', 'Ktoś zawsze jest mostem',
       null, null,
       null, null),
      ('Freedom', false,
       'Should you be free to do anything that harms only you?',
       'Czy powinieneś móc robić wszystko, co szkodzi wyłącznie tobie?',
       'Your life, your experiment', 'Twoje życie, twój eksperyment',
       'No harm stays only yours', 'Żadna krzywda nie zostaje tylko twoja',
       'Who counts as "only you"?', 'Kto się liczy jako „tylko ty"?'),
      ('Freedom', false,
       'Is discipline the truest form of freedom?',
       'Czy dyscyplina to najprawdziwsza forma wolności?',
       'The trained hand plays freely', 'Wyćwiczona ręka gra swobodnie',
       'A cage you built is still a cage', 'Klatka własnej roboty to wciąż klatka',
       null, null),
      ('Freedom', false,
       'Does free speech have to include the right to offend?',
       'Czy wolność słowa musi obejmować prawo do obrażania?',
       'Comfort was never part of the deal', 'Wygoda nigdy nie była częścią umowy',
       'Words draw blood too', 'Słowa też ranią do krwi',
       null, null),
      ('Freedom', false,
       'Is wasting your own potential anyone''s business but yours?',
       'Czy marnowanie własnego potencjału to sprawa kogokolwiek poza tobą?',
       'Talent is not a debt', 'Talent to nie dług',
       'Gifts are given to be used', 'Dary są po to, by ich używać',
       null, null),
      ('Freedom', false,
       'Would life be better with fewer choices?',
       'Czy życie byłoby lepsze przy mniejszej liczbie wyborów?',
       'The menu is the tyranny', 'To menu jest tyranem',
       'Choice is what dignity looks like', 'Wybór to twarz godności',
       null, null)
      ,('Culture', false,
       'Is hating popular things just another kind of conformity?',
       'Czy pogarda dla tego, co popularne, to tylko inny rodzaj konformizmu?',
       'A contrarian is a follower in reverse', 'Kontrarianin to naśladowca na wstecznym',
       'The crowd is usually wrong', 'Tłum zwykle się myli',
       null, null),
      ('Culture', false,
       'Do lyrics matter less than the melody?',
       'Czy tekst piosenki znaczy mniej niż melodia?',
       'You hum it, you don''t recite it', 'Nucisz ją, a nie recytujesz',
       'Words are the soul of a song', 'Słowa to dusza piosenki',
       null, null),
      ('Culture', false,
       'Is art you don''t understand still worth your time?',
       'Czy sztuka, której nie rozumiesz, jest nadal warta twojego czasu?',
       'Confusion is the doorway', 'Zmieszanie to drzwi wejściowe',
       'Obscurity can be a costume', 'Niezrozumiałość bywa kostiumem',
       null, null),
      ('Culture', false,
       'Do reviews ruin more experiences than they save?',
       'Czy recenzje psują więcej doświadczeń, niż ratują?',
       'Someone else moved into your head', 'Ktoś inny zamieszkał w twojej głowie',
       'Life is too short for bad films', 'Życie jest za krótkie na złe filmy',
       null, null),
      ('Culture', false,
       'Is photographing art in museums missing the point?',
       'Czy fotografowanie dzieł w muzeum to rozminięcie się z ich sensem?',
       'You saw it through a screen', 'Widziałeś je przez ekran',
       'A photo is a bookmark', 'Zdjęcie to zakładka do wspomnienia',
       null, null),
      ('Culture', false,
       'Can something kitschy still be great art?',
       'Czy coś kiczowatego może być wielką sztuką?',
       'Joy doesn''t check credentials', 'Radość nie sprawdza dyplomów',
       'Kitsch flatters, art challenges', 'Kicz schlebia, sztuka rzuca wyzwanie',
       null, null),
      ('Culture', false,
       'Do sad songs heal better than happy ones?',
       'Czy smutne piosenki leczą lepiej niż wesołe?',
       'Sorrow needs a witness', 'Smutek potrzebuje świadka',
       'You''re feeding the wound', 'Karmisz ranę',
       null, null),
      ('Culture', false,
       'Is translation always a betrayal of the original?',
       'Czy przekład to zawsze zdrada oryginału?',
       'Every language cuts differently', 'Każdy język tnie inaczej',
       'A betrayal that gives you the world', 'Zdrada, która daje ci świat',
       null, null),
      ('Culture', false,
       'Does art owe you an explanation?',
       'Czy sztuka jest ci winna wyjaśnienie?',
       'Meaning is half the work', 'Znaczenie to połowa dzieła',
       'The work must speak alone', 'Dzieło musi mówić samo',
       null, null),
      ('Culture', false,
       'Is originality overrated?',
       'Czy oryginalność jest przereklamowana?',
       'Everything is a remix', 'Wszystko jest remiksem',
       'Copies never start fires', 'Kopie nie wzniecają pożarów',
       null, null),
      ('Culture', false,
       'Should children''s stories have sad endings too?',
       'Czy bajki dla dzieci powinny miewać też smutne zakończenia?',
       'Life won''t spare them', 'Życie ich nie oszczędzi',
       'Childhood is for shelter', 'Dzieciństwo jest od dawania schronienia',
       null, null),
      ('Culture', false,
       'Is judging a book by its cover perfectly rational?',
       'Czy ocenianie książki po okładce jest w pełni racjonalne?',
       'Design is information', 'Projekt okładki to informacja',
       'The oldest mistake in the world', 'Najstarszy błąd świata',
       null, null),
      ('Society', false,
       'Is what you overhear through the wall none of your business?',
       'Czy to, co słyszysz przez ścianę, to nie twoja sprawa?',
       'Walls are accidents, privacy isn''t', 'Ściany to przypadek, prywatność nie',
       'Some sounds are cries for help', 'Niektóre dźwięki to wołanie o pomoc',
       null, null),
      ('Society', false,
       'Can you fairly dislike someone for something they can''t help?',
       'Czy można uczciwie kogoś nie lubić za coś, na co nie ma wpływu?',
       'Feelings don''t take orders', 'Uczucia nie przyjmują rozkazów',
       'Judge choices, not features', 'Oceniaj wybory, nie cechy',
       null, null),
      ('Society', false,
       'Is it easier to be kind to strangers than to your own family?',
       'Czy łatwiej być miłym dla obcych niż dla własnej rodziny?',
       'Strangers never test you twice', 'Obcy nie testują cię dwa razy',
       'Home is where kindness gets real', 'Dom to test prawdziwej dobroci',
       null, null),
      ('Society', false,
       'Is apologizing first a victory rather than a surrender?',
       'Czy przeprosiny jako pierwszy to zwycięstwo, a nie kapitulacja?',
       'The brave move first', 'Odważni ruszają pierwsi',
       'Someone learns that sorry pays', 'Ktoś się uczy, że przepraszanie popłaca',
       null, null),
      ('Society', false,
       'Should you wake a stranger sleeping past their stop?',
       'Czy budzić nieznajomego, który przesypia swój przystanek?',
       'You''d want to be woken', 'Sam chciałbyś zostać obudzony',
       'Maybe sleep was what they needed', 'Może właśnie snu potrzebował najbardziej',
       null, null),
      ('Society', false,
       'Is staying in your hometown forever settling for less?',
       'Czy zostanie na zawsze w rodzinnym mieście to godzenie się na mniej?',
       'The world is a menu', 'Świat to całe menu',
       'Roots are wealth', 'Korzenie to majątek',
       null, null),
      ('Society', false,
       'Is watching strangers in a café creepy rather than human?',
       'Czy przyglądanie się nieznajomym w kawiarni jest niepokojące, a nie ludzkie?',
       'Everyone is a story', 'Każdy człowiek to opowieść',
       null, null,
       null, null),
      ('Society', false,
       'Is a compliment from a stranger worth more than one from a friend?',
       'Czy komplement od nieznajomego jest wart więcej niż od przyjaciela?',
       'Strangers owe you nothing', 'Obcy nic ci nie są winni',
       'Friends know what they''re praising', 'Przyjaciele wiedzą, co chwalą',
       null, null),
      ('Society', false,
       'Is offering help before it''s asked for presumptuous?',
       'Czy oferowanie pomocy, zanim ktoś poprosi, to zarozumialstwo?',
       'Pride starves quietly', 'Duma głoduje po cichu',
       'An uninvited rescue is a judgment', 'Nieproszony ratunek to ocena',
       null, null),
      ('Society', false,
       'Is living for the weekend wasting five days out of seven?',
       'Czy życie od weekendu do weekendu to marnowanie pięciu dni z siedmiu?',
       'You''re renting out your best hours', 'Wynajmujesz komuś swoje najlepsze godziny',
       'Anticipation is half the joy', 'Oczekiwanie to połowa radości',
       null, null),
      ('Society', false,
       'Should elders'' advice carry extra weight simply because of their age?',
       'Czy rady starszych powinny ważyć więcej tylko ze względu na ich wiek?',
       'They walked the road ahead of you', 'Przeszli tę drogę przed tobą',
       'Old maps, new roads', 'Stare mapy, nowe drogi',
       null, null),
      ('Ethics', false,
       'Is refusing to take sides a decision you must answer for?',
       'Czy odmowa opowiedzenia się po którejś ze stron to decyzja, za którą odpowiadasz?',
       'The fence is also a seat', 'Płot to też miejsce siedzące',
       'Not every war is yours', 'Nie każda wojna jest twoja',
       null, null),
      ('Ethics', false,
       'Is flattering the powerful just smart navigation?',
       'Czy schlebianie wpływowym to po prostu sprytna nawigacja?',
       'Oil keeps machines running', 'Oliwa utrzymuje maszyny w ruchu',
       'Every bow bends the spine', 'Każdy ukłon zgina kręgosłup',
       null, null),
      ('Ethics', false,
       'Is breaking a promise to yourself as serious as breaking one to a friend?',
       'Czy złamanie obietnicy danej sobie jest równie poważne jak tej danej przyjacielowi?',
       'You''re the witness you can''t escape', 'Jesteś świadkiem, przed którym nie uciekniesz',
       'No one else got hurt', 'Nikt inny nie ucierpiał',
       null, null),
      ('Ethics', false,
       'Would you take help you qualify for but don''t really need?',
       'Czy przyjąłbyś pomoc, która ci się należy, choć nie jest ci naprawdę potrzebna?',
       'The rules said yes', 'Zasady powiedziały „tak"',
       'Someone needier stands behind you', 'Ktoś bardziej potrzebujący stoi za tobą',
       null, null),
      ('Ethics', false,
       'Is judging people of the past by today''s morals unfair?',
       'Czy ocenianie ludzi z przeszłości dzisiejszą moralnością jest niesprawiedliwe?',
       'They couldn''t know better?', 'Nie mogli wiedzieć lepiej?',
       'Cruelty was always cruelty', 'Okrucieństwo zawsze było okrucieństwem',
       'Future eyes are watching you too', 'Przyszłe oczy patrzą też na ciebie'),
      ('Ethics', false,
       'Should a promise made to a child bind as strongly as one made to an adult?',
       'Czy obietnica dana dziecku zobowiązuje tak samo mocno jak ta dana dorosłemu?',
       'Children keep perfect records', 'Dzieci prowadzą bezbłędne rejestry',
       'Adults understand circumstances', 'Dorośli rozumieją okoliczności',
       null, null),
      ('Ethics', false,
       'Is being charming on purpose a form of manipulation?',
       'Czy bycie czarującym z premedytacją to forma manipulacji?',
       'Rehearsed warmth is a tool', 'Wyćwiczone ciepło to narzędzie',
       'Making people feel good is a gift', 'Sprawianie ludziom przyjemności to dar',
       null, null),
      ('Ethics', false,
       'Should you thank people just for doing their jobs?',
       'Czy dziękować ludziom za samo wykonywanie ich pracy?',
       'Courtesy costs nothing', 'Uprzejmość nic nie kosztuje',
       'Thanks devalues into noise', 'Podziękowania rozmieniają się na drobne',
       null, null),
      ('Ethics', false,
       'Is doing the right thing for the wrong reason still right?',
       'Czy dobry uczynek ze złych pobudek to nadal dobry uczynek?',
       'The deed lands the same', 'Czyn ląduje tak samo',
       'Motive is the moral core', 'Motyw to moralny rdzeń',
       null, null),
      ('Ethics', false,
       'Is enjoying a wrongdoer''s downfall shameful?',
       'Czy radość z upadku winowajcy przynosi wstyd?',
       'Justice tastes sweet', 'Sprawiedliwość smakuje słodko',
       'Joy in pain stains you', 'Radość z cudzego bólu plami',
       null, null),
      ('Money', false,
       'Should the rich still live frugally?',
       'Czy bogaci powinni mimo wszystko żyć oszczędnie?',
       'Waste is waste at any income', 'Marnotrawstwo to marnotrawstwo, niezależnie od konta',
       'What is wealth for, then?', 'Po co w takim razie bogactwo?',
       null, null),
      ('Money', false,
       'Should you tell a seller they''re charging too little?',
       'Czy powiedzieć sprzedawcy, że liczy sobie za mało?',
       'Honesty beats a bargain', 'Szczerość ponad okazję',
       'The market speaks for itself', 'Rynek mówi sam za siebie',
       null, null),
      ('Money', false,
       'Would you pay more to be served by a human instead of a machine?',
       'Czy zapłaciłbyś więcej, by obsłużył cię człowiek, a nie maszyna?',
       'Service is a relationship', 'Obsługa to relacja',
       'Same product — why pay more?', 'Ten sam produkt — czemu drożej?',
       null, null),
      ('Money', false,
       'Should small debts between friends simply expire?',
       'Czy drobne długi między przyjaciółmi powinny po prostu wygasać?',
       'Friendship amortizes', 'Przyjaźń amortyzuje',
       'Small debts are small tests', 'Małe długi to małe testy',
       null, null),
      ('Money', false,
       'Would being paid well to do nothing destroy you?',
       'Czy dobra pensja za nicnierobienie by cię zniszczyła?',
       'Purpose starves quietly', 'Poczucie sensu umiera po cichu',
       'Everyone has a dream list ready', 'Każdy ma gotową listę marzeń',
       null, null),
      ('Money', false,
       'Should lottery winners stay anonymous?',
       'Czy zwycięzcy loterii powinni pozostawać anonimowi?',
       'Money attracts long-lost cousins', 'Pieniądze przyciągają dalekich kuzynów',
       'Faces make the dream real', 'Twarze czynią marzenie realnym',
       null, null),
      ('Money', false,
       'Would you sell an embarrassing story about yourself for real money?',
       'Czy sprzedałbyś kompromitującą historię o sobie za duże pieniądze?',
       'Shame fades, money stays', 'Wstyd mija, pieniądze zostają',
       'Dignity has no refund policy', 'Godności się nie zwraca',
       null, null),
      ('Money', false,
       'Should you keep a big windfall secret from your friends?',
       'Czy dużą wygraną warto zataić przed przyjaciółmi?',
       'Money rewrites friendships', 'Pieniądze przepisują przyjaźnie',
       'Secrets grow into awkwardness', 'Sekrety rosną w niezręczność',
       null, null),
      ('Money', false,
       'Can an expensive gift be a burden rather than a joy?',
       'Czy drogi prezent może być ciężarem, a nie radością?',
       'Gifts issue invoices of gratitude', 'Prezenty wystawiają faktury wdzięczności',
       'Generosity is never a problem', 'Hojność nigdy nie jest problemem',
       null, null)
      ,('Work', false,
       'Is working for free "for exposure" ever worth it?',
       'Czy praca za darmo „dla rozgłosu" bywa tego warta?',
       'Exposure doesn''t pay rent', 'Rozgłos nie płaci czynszu',
       'A foot in the door can be worth a shift', 'Stopa w drzwiach bywa warta dniówki',
       null, null),
      ('Work', false,
       'Is "good enough" the true mark of a professional?',
       'Czy „wystarczająco dobrze" to prawdziwy znak profesjonalisty?',
       'Perfect ships never sail', 'Idealne statki nigdy nie wypływają',
       'Craft lives in the last ten percent', 'Kunszt mieszka w ostatnich dziesięciu procentach',
       null, null),
      ('Work', false,
       'Is ambition without a clear goal just dressed-up anxiety?',
       'Czy ambicja bez wyraźnego celu to tylko przebrany niepokój?',
       'A race with no finish line', 'Bieg bez mety',
       'Direction reveals itself in motion', 'Kierunek wyłania się w ruchu',
       null, null),
      ('Work', false,
       'Do work friendships expire with the contract?',
       'Czy przyjaźnie z pracy wygasają razem z umową?',
       'The context was the glue', 'To kontekst był klejem',
       'People outlast payrolls', 'Ludzie trwają dłużej niż listy płac',
       null, null),
      ('Work', false,
       'Is a long commute a dealbreaker no salary can fix?',
       'Czy długi dojazd to problem, którego nie naprawi żadna pensja?',
       'You pay in mornings and evenings', 'Płacisz porankami i wieczorami',
       'Podcasts turn traffic into school', 'Podcasty zmieniają korki w szkołę',
       null, null),
      ('Work', false,
       'Should your boss know about your side projects?',
       'Czy szef powinien wiedzieć o twoich projektach po godzinach?',
       'Transparency buys trust', 'Jawność kupuje zaufanie',
       'Your evenings are not company property', 'Twoje wieczory to nie własność firmy',
       null, null),
      ('Work', false,
       'Is working surrounded by people better than working behind a closed door?',
       'Czy praca wśród ludzi jest lepsza niż za zamkniętymi drzwiami?',
       'Energy is contagious', 'Energia jest zaraźliwa',
       'Focus needs walls', 'Skupienie potrzebuje ścian',
       null, null),
      ('Work', false,
       'Would you take a fascinating job that no one respects?',
       'Czy przyjąłbyś fascynującą pracę, której nikt nie szanuje?',
       'Interest outlives applause', 'Ciekawość przeżywa oklaski',
       'Status opens every next door', 'Status otwiera każde kolejne drzwi',
       null, null),
      ('Work', false,
       'Do experienced people owe the young their knowledge?',
       'Czy doświadczeni są winni młodym swoją wiedzę?',
       'A ladder is for lowering down', 'Drabinę spuszcza się w dół',
       'That knowledge cost years', 'Ta wiedza kosztowała lata',
       null, null),
      ('Technology', false,
       'Would you pay extra for a holiday with no phone signal?',
       'Czy dopłaciłbyś za wakacje bez zasięgu?',
       'Silence is the last luxury', 'Cisza to ostatni luksus',
       'Paying to be unreachable is madness', 'Płacenie za bycie nieosiągalnym to szaleństwo',
       null, null),
      ('Technology', false,
       'Would you let your home restock itself without asking you?',
       'Czy pozwoliłbyś, aby dom sam uzupełniał zapasy bez pytania?',
       'One chore gone forever', 'Jeden obowiązek mniej na zawsze',
       'You just hired a spy with shelves', 'Właśnie zatrudniłeś szpiega z półkami',
       null, null),
      ('Technology', false,
       'Should everything digital come with a real off switch?',
       'Czy wszystko, co cyfrowe, powinno mieć prawdziwy wyłącznik?',
       'Power you can touch', 'Wyłącznik, którego można dotknąć',
       null, null,
       null, null),
      ('Technology', false,
       'Can weekly video calls replace visiting your parents?',
       'Czy cotygodniowe wideorozmowy mogą zastąpić odwiedziny u rodziców?',
       'Presence has no bandwidth', 'Obecność nie ma przepustowości',
       'Better often on screen than rarely in person', 'Lepiej często na ekranie niż rzadko osobiście',
       null, null),
      ('Technology', false,
       'Should you research your symptoms before seeing the doctor?',
       'Czy sprawdzać swoje objawy w sieci przed wizytą u lekarza?',
       'An informed patient asks better questions', 'Poinformowany pacjent lepiej pyta',
       'Dr. Internet finds cancer everywhere', 'Doktor Internet wszędzie widzi raka',
       null, null),
      ('Technology', false,
       'Is paying to win in games buying a lie?',
       'Czy płacenie za wygraną w grach to kupowanie kłamstwa?',
       'You bought the trophy, not the victory', 'Kupiłeś puchar, nie zwycięstwo',
       'Time is money — each pays with one', 'Czas to pieniądz — każdy płaci innym',
       null, null),
      ('Technology', false,
       'Is going a whole day without answering messages a right rather than rudeness?',
       'Czy cały dzień bez odpisywania na wiadomości to prawo, a nie brak kultury?',
       'Availability is not a debt', 'Dostępność to nie dług',
       'Silence makes people worry', 'Cisza każe bliskim się martwić',
       null, null),
      ('Technology', false,
       'Would you let your face replace all your keys and cards?',
       'Czy pozwoliłbyś, aby twarz zastąpiła ci wszystkie klucze i karty?',
       'You can''t leave your face at home', 'Twarzy nie zostawisz w domu',
       'A lock you can never change', 'Zamek, którego nigdy nie wymienisz',
       null, null),
      ('Technology', false,
       'Would you donate your data to science the way people donate blood?',
       'Czy oddałbyś swoje dane nauce, tak jak ludzie oddają krew?',
       'Your clicks could cure someone', 'Twoje kliknięcia mogą kogoś wyleczyć',
       '"Science" is a word on a form', '„Nauka" to tylko słowo na formularzu',
       null, null),
      ('Technology', false,
       'Is a never-ending family group chat a blessing rather than a burden?',
       'Czy niekończący się rodzinny czat to błogosławieństwo, a nie ciężar?',
       'The family hearth fits in your pocket', 'Ognisko domowe mieści się w kieszeni',
       'A meeting that never adjourns', 'Zebranie, które nigdy się nie kończy',
       null, null),
      ('Health', false,
       'Is "sleep on it" the best decision-making advice there is?',
       'Czy „prześpij się z tym" to najlepsza rada przy podejmowaniu decyzji?',
       'Morning edits the night''s drama', 'Poranek redaguje nocne dramaty',
       'Delay dressed up as wisdom', 'Zwłoka przebrana za mądrość',
       null, null),
      ('Health', false,
       'Is crying at films a sign of health rather than weakness?',
       'Czy płacz na filmach to znak zdrowia, a nie słabości?',
       'Those tears were queued anyway', 'Te łzy i tak czekały w kolejce',
       'It''s fiction — get a grip', 'To fikcja — weź się w garść',
       null, null),
      ('Health', false,
       'Would you trade a year of life for a lifetime of perfect sleep?',
       'Czy oddałbyś rok życia za idealny sen do końca swoich dni?',
       'Sleep is where life gets repaired', 'Sen to warsztat naprawczy życia',
       'You''d sleep away what you traded', 'Prześpisz dokładnie to, co oddałeś',
       null, null),
      ('Health', false,
       'Is living alone the best way to truly know yourself?',
       'Czy mieszkanie samemu to najlepszy sposób, by naprawdę poznać siebie?',
       'Solitude is a mirror', 'Samotność to lustro',
       'Other people are the mirror', 'To inni ludzie są lustrem',
       null, null),
      ('Health', false,
       'Is complaining out loud good for you?',
       'Czy narzekanie na głos służy zdrowiu?',
       'Pressure needs a valve', 'Ciśnienie potrzebuje zaworu',
       'Complaints water the weeds', 'Narzekanie podlewa chwasty',
       null, null),
      ('Health', false,
       'Are team sports better for the soul than solo sports?',
       'Czy sporty drużynowe są lepsze dla ducha niż indywidualne?',
       'The team carries you on bad days', 'Zespół niesie cię w gorsze dni',
       'The swim lane never lies', 'Tor pływacki nigdy nie kłamie',
       null, null),
      ('Health', false,
       'Can a garden do what a therapist does?',
       'Czy ogród potrafi to, co terapeuta?',
       'Soil doesn''t charge by the hour', 'Ziemia nie liczy za godzinę',
       'Weeding won''t untangle your childhood', 'Pielenie nie rozplącze ci dzieciństwa',
       null, null),
      ('Health', false,
       'Is aging a disease we should try to cure?',
       'Czy starzenie się to choroba, którą powinniśmy próbować wyleczyć?',
       'Every disease was once "natural"', 'Każda choroba była kiedyś „naturalna"',
       'Mortality gives life its shape', 'Śmiertelność nadaje życiu kształt',
       'A cure for everyone — or for the rich?', 'Lek dla wszystkich — czy dla bogatych?'),
      ('Health', false,
       'Is exercise you hate still worth doing?',
       'Czy trening, którego nienawidzisz, wciąż jest wart wysiłku?',
       'The body doesn''t ask if you enjoyed it', 'Ciało nie pyta, czy było miło',
       'Hate guarantees quitting', 'Niechęć gwarantuje porzucenie',
       null, null),
      ('Health', false,
       'Would you take a pill that replaced exercise?',
       'Czy wziąłbyś tabletkę zastępującą ćwiczenia?',
       'Same health, hours saved', 'To samo zdrowie, godziny zaoszczędzone',
       'The effort was the medicine', 'To wysiłek był lekarstwem',
       null, null),
      ('Justice', false,
       'Should a child ever be asked to testify against a parent?',
       'Czy dziecko powinno kiedykolwiek zeznawać przeciwko rodzicowi?',
       'Truth has no age limit', 'Prawda nie ma limitu wieku',
       'No child should carry that', 'Żadne dziecko nie powinno tego dźwigać',
       null, null),
      ('Justice', false,
       'If two people wrong each other equally, is justice already done?',
       'Czy gdy dwie osoby skrzywdzą się nawzajem tak samo, sprawiedliwości stało się zadość?',
       'The ledger is balanced', 'Rachunek się wyrównał',
       'Two wrongs don''t make a zero', 'Dwa zła nie dają zera',
       null, null),
      ('Justice', false,
       'Should not knowing a rule excuse breaking it?',
       'Czy nieznajomość zasady powinna usprawiedliwiać jej złamanie?',
       'You can''t obey what you can''t see', 'Nie sposób przestrzegać niewidzialnego',
       'Ignorance would become a strategy', 'Niewiedza stałaby się strategią',
       null, null),
      ('Justice', false,
       'Should a parent''s punishment be softened for their children''s sake?',
       'Czy karę dla rodzica powinno się łagodzić ze względu na jego dzieci?',
       'The kids did nothing wrong', 'Dzieci nic nie zawiniły',
       'Parenthood would become a shield', 'Rodzicielstwo stałoby się tarczą',
       null, null),
      ('Justice', false,
       'Is wasting someone''s time a form of theft?',
       'Czy marnowanie czyjegoś czasu to forma kradzieży?',
       'Hours never come back', 'Godziny nigdy nie wracają',
       'Theft needs a thing', 'Kradzież wymaga rzeczy',
       null, null),
      ('Justice', false,
       'Is a lottery the fairest way to share what can''t be divided?',
       'Czy losowanie to najuczciwszy sposób dzielenia tego, czego nie da się podzielić?',
       'Chance has no favorites', 'Los nie ma pupili',
       'Need should outrank luck', 'Potrzeba powinna bić przypadek',
       null, null),
      ('Justice', false,
       'If the wrong was public, must the apology be public too?',
       'Czy jeśli krzywda była publiczna, przeprosiny też muszą być publiczne?',
       'The audience saw the slap', 'Publiczność widziała ten policzek',
       'Sincerity hates a stage', 'Szczerość nie znosi sceny',
       null, null),
      ('Relationships', false,
       'Do couples need separate friend groups to stay healthy?',
       'Czy para potrzebuje osobnych kręgów przyjaciół, by być zdrowa?',
       'You need somewhere to be just you', 'Potrzebujesz miejsca, gdzie jesteś tylko sobą',
       'Shared friends weave the safety net', 'Wspólni przyjaciele tkają siatkę bezpieczeństwa',
       null, null),
      ('Relationships', false,
       'Is making your partner your whole world romantic rather than risky?',
       'Czy uczynienie z partnera całego swojego świata jest romantyczne, a nie ryzykowne?',
       'All your eggs, one heart', 'Wszystkie jajka w jednym sercu',
       'That is what love IS', 'Przecież właśnie tym jest miłość',
       null, null),
      ('Relationships', false,
       'Can you be fairly jealous of your partner''s past?',
       'Czy można uczciwie być zazdrosnym o przeszłość partnera?',
       'The past made the person you love', 'Przeszłość ulepiła osobę, którą kochasz',
       'You can''t win against ghosts', 'Z duchami się nie wygrywa',
       null, null),
      ('Relationships', false,
       'Would you want to know if your partner settled for you?',
       'Czy chciałbyś wiedzieć, że partner „zadowolił się" tobą?',
       'Truth, even when it cuts', 'Prawda, nawet gdy tnie',
       'Some questions poison the well', 'Niektóre pytania zatruwają studnię',
       null, null)
    ) as s(category, is_premium, en, pl, a1en, a1pl, a2en, a2pl, a3en, a3pl)
  loop
    -- skip if this EN text was already seeded
    if exists (
      select 1 from public.question_translations
      where locale = 'en' and question_text = r.en
    ) then
      continue;
    end if;

    insert into public.questions (category, is_premium)
    values (r.category, r.is_premium)
    returning id into qid;

    insert into public.question_translations (question_id, locale, question_text)
    values (qid, 'en', r.en),
           (qid, 'pl', r.pl);

    -- smaczek 1 (free teaser) -- always present
    insert into public.question_smaczki (question_id, position, is_active)
    values (qid, 1, true)
    returning id into s1;
    insert into public.question_smaczki_translations (smaczek_id, locale, text)
    values (s1, 'en', r.a1en),
           (s1, 'pl', r.a1pl);

    -- smaczek 2 (premium) -- most questions
    if r.a2en is not null then
      insert into public.question_smaczki (question_id, position, is_active)
      values (qid, 2, true)
      returning id into s2;
      insert into public.question_smaczki_translations (smaczek_id, locale, text)
      values (s2, 'en', r.a2en),
             (s2, 'pl', r.a2pl);
    end if;

    -- smaczek 3 (premium) -- only where a third angle genuinely deepens it
    if r.a3en is not null then
      insert into public.question_smaczki (question_id, position, is_active)
      values (qid, 3, true)
      returning id into s3;
      insert into public.question_smaczki_translations (smaczek_id, locale, text)
      values (s3, 'en', r.a3en),
             (s3, 'pl', r.a3pl);
    end if;
  end loop;
end $$;

-- ----------------------------------------------------------------------------
-- Schedule every still-unscheduled active question onto the next free dates.
-- Keeps Strategy A (unique question_id) intact.
-- ----------------------------------------------------------------------------
insert into public.daily_questions (publish_date, question_id)
select dates.d::date, q.id
from (
  select d, row_number() over (order by d) rn
  from generate_series(current_date, current_date + 1499, '1 day'::interval) d
  where d::date not in (select publish_date from public.daily_questions)
) dates
join (
  select id, row_number() over (order by random()) rn
  from public.questions
  where is_active
    and id not in (select question_id from public.daily_questions)
) q on q.rn = dates.rn
on conflict do nothing;

commit;
