-- ============================================================================
-- Seed batch 4: 125 globally-applicable debate questions (PL + EN) + 2 smaczki
-- ----------------------------------------------------------------------------
-- Generated 2026-07-03. Same recipe as batch 1-3: universal YES/NO dilemmas
-- anyone in any country can debate (no law-, currency-, or country-specific
-- framings), each chosen to split people ~50/50. Deduplicated against all 482
-- questions live in prod on 2026-07-03 (full EN text pull).
--
-- Each question gets exactly TWO bilingual "smaczki":
--   position 1 -> shown FREE (strongest hook)
--   position 2 -> premium-gated counter-angle
--
-- is_premium is false for every row: the column is inert since
-- 20260701120000_open_premium_questions_to_unlock_pool.sql (never set it).
--
-- Idempotent: keyed on EN text; re-running skips rows that already exist.
-- Topics in this file: Ethics (24), Justice (14), Relationships (29),
-- Family (26), Friendship (28), Money (4 of 19; rest in batch 5).
-- ============================================================================

begin;

do $$
declare
  r   record;
  qid uuid;
  s1  uuid;
  s2  uuid;
begin
  for r in
    select * from (values
      ('Ethics', false,
       'If you could hear what people really think, would you want to?',
       'Gdybyś mógł usłyszeć, co ludzie naprawdę myślą, chciałbyś?',
       'No more guessing', 'Koniec zgadywania',
       'Could you bear the truth?', 'Zniósłbyś tę prawdę?'),
      ('Ethics', false,
       'Would you accept a fortune if a stranger you''d never meet suffered for it?',
       'Czy przyjąłbyś fortunę, gdyby cierpiał za nią obcy, którego nigdy nie spotkasz?',
       'You''d never see it', 'Nigdy tego nie zobaczysz',
       'You''d always know', 'Zawsze będziesz wiedział'),
      ('Ethics', false,
       'Is it fair to lie to someone who lies to you?',
       'Czy wolno okłamywać kogoś, kto okłamuje ciebie?',
       'An eye for an eye?', 'Oko za oko?',
       'Now there are two liars', 'Teraz kłamców jest dwóch'),
      ('Ethics', false,
       'Is it okay to jump a queue when you''re in a genuine hurry?',
       'Czy wolno wepchnąć się do kolejki, gdy naprawdę się spieszysz?',
       'Real emergencies exist', 'Nagłe wypadki się zdarzają',
       'Everyone is in a hurry', 'Każdy się spieszy'),
      ('Ethics', false,
       'Must you keep a promise that now works against you?',
       'Czy trzeba dotrzymać obietnicy, która obróciła się przeciwko tobie?',
       'A word is a word', 'Słowo to słowo',
       'You promised in a different world', 'Obiecywałeś w innym świecie'),
      ('Ethics', false,
       'Is listening in when people talk about you fair game?',
       'Czy podsłuchiwanie, gdy mówią o tobie, to fair play?',
       'It''s about you, after all', 'Przecież chodzi o ciebie',
       'Eavesdroppers hear no good', 'Podsłuchujący nie usłyszy nic dobrego'),
      ('Ethics', false,
       'If you found a stranger''s diary, would reading it be wrong?',
       'Gdybyś znalazł cudzy pamiętnik, czy przeczytanie go byłoby złe?',
       'They''ll never know', 'Nigdy się nie dowie',
       'It''s someone''s soul', 'To czyjaś dusza'),
      ('Ethics', false,
       'If life dealt you an unfair advantage, is it wrong to use it fully?',
       'Jeśli los dał ci nieuczciwą przewagę, czy korzystanie z niej w pełni jest złe?',
       'You didn''t choose it', 'Nie ty ją wybrałeś',
       'Someone pays for it', 'Ktoś za nią płaci'),
      ('Ethics', false,
       'If a big company forgets to charge you, should you tell them?',
       'Gdy wielka firma zapomni pobrać od ciebie opłatę, czy powinieneś jej to zgłosić?',
       'They wouldn''t notice', 'I tak nie zauważą',
       'Honesty isn''t about size', 'Uczciwość nie zna rozmiaru'),
      ('Ethics', false,
       'Is preaching good while doing wrong worse than openly doing wrong?',
       'Czy głoszenie dobra i czynienie zła jest gorsze niż jawne zło?',
       'At least be honest', 'Przynajmniej bądź szczery',
       'The words still help others', 'Te słowa komuś pomagają'),
      ('Ethics', false,
       'Is it wrong to profit when disaster strikes others?',
       'Czy zarabianie na cudzej katastrofie jest złe?',
       'Business is business?', 'Biznes to biznes?',
       'A fortune built on tears', 'Fortuna na łzach'),
      ('Ethics', false,
       'If cheating in a game hurts no one, is it still wrong?',
       'Jeśli oszustwo w grze nikomu nie szkodzi, czy nadal jest złe?',
       'No victim, no crime?', 'Nie ma ofiary, nie ma winy?',
       'You know you cheated', 'Ty wiesz, że oszukałeś'),
      ('Ethics', false,
       'Should meat eaters be willing to kill the animal themselves?',
       'Czy jedzący mięso powinni umieć sami zabić zwierzę?',
       'Own what''s on your plate', 'Weź odpowiedzialność za talerz',
       'We divide labor for a reason', 'Od tego jest podział pracy'),
      ('Ethics', false,
       'If a machine said it feels pain, would turning it off be cruel?',
       'Gdyby maszyna mówiła, że czuje ból, czy wyłączenie jej byłoby okrutne?',
       'What if it''s true?', 'A jeśli to prawda?',
       'It''s just saying words', 'To tylko słowa'),
      ('Ethics', false,
       'Is stealing from a thief still stealing?',
       'Czy kradzież u złodzieja to wciąż kradzież?',
       'Poetic justice?', 'Sprawiedliwość poetycka?',
       'Theft is theft', 'Kradzież to kradzież'),
      ('Ethics', false,
       'Do people mostly end up getting what they deserve in life?',
       'Czy ludzie w życiu przeważnie dostają to, na co zasłużyli?',
       'What goes around comes around', 'Jak sobie pościelesz, tak się wyśpisz',
       'Tell that to the unlucky', 'Powiedz to pechowcom'),
      ('Ethics', false,
       'Would most people break the rules if they could never be caught?',
       'Czy większość ludzi łamałaby zasady, gdyby nigdy nie mogła zostać przyłapana?',
       'Locks keep us honest', 'Uczciwi dzięki zamkom',
       'Conscience needs no witnesses', 'Sumienie nie potrzebuje świadków'),
      ('Ethics', false,
       'Is taking every freebie from a hotel room fair game?',
       'Czy zabieranie z pokoju hotelowego wszystkiego, co darmowe, to fair play?',
       'You paid for it', 'Przecież zapłaciłeś',
       'Where''s the line?', 'Gdzie leży granica?'),
      ('Ethics', false,
       'Would you save your drowning pet before a drowning stranger?',
       'Czy ratowałbyś swoje tonące zwierzę przed tonącym nieznajomym?',
       'Family is family', 'Rodzina to rodzina',
       'A human life is a human life', 'Człowiek to człowiek'),
      ('Ethics', false,
       'Would you tell a stranger you''d just seen their partner cheating?',
       'Czy powiedziałbyś nieznajomemu, że właśnie widziałeś zdradę jego partnera?',
       'You''d want to know', 'Ty chciałbyś wiedzieć',
       'Not your life, not your call', 'Nie twoje życie, nie twoja decyzja'),
      ('Ethics', false,
       'Is pretending not to see someone you know ever okay?',
       'Czy udawanie, że nie widzisz znajomego, bywa w porządku?',
       'No energy today', 'Nie dziś, nie mam siły',
       'They saw you too', 'Oni też cię widzieli'),
      ('Ethics', false,
       'If everyone breaks a small rule, is it still wrong to break it?',
       'Jeśli wszyscy łamią drobną zasadę, czy jej łamanie wciąż jest złe?',
       'Rules outlive their sense', 'Zasady przeżywają swój sens',
       '"Everyone" is no excuse', '„Wszyscy" to żadna wymówka'),
      ('Ethics', false,
       'Should we feel uneasy enjoying sports built on hurting people?',
       'Czy powinno nas uwierać, że lubimy sporty oparte na zadawaniu bólu?',
       'You cheer for pain', 'Kibicujesz bólowi',
       'They chose the ring', 'Sami weszli na ring'),
      ('Ethics', false,
       'Would a world where nobody could lie be a better world?',
       'Czy świat, w którym nikt nie może kłamać, byłby lepszy?',
       'Finally, the truth', 'Nareszcie prawda',
       'Truth without mercy', 'Prawda bez litości'),
      ('Justice', false,
       'Is letting ten guilty people go free better than jailing one innocent?',
       'Czy lepiej wypuścić dziesięciu winnych, niż skazać jednego niewinnego?',
       'Never punish the innocent', 'Niewinny to świętość',
       'Ten more back on the streets', 'Dziesięciu wraca na ulice'),
      ('Justice', false,
       'Should a teenager who commits a terrible crime be judged as an adult?',
       'Czy nastolatek, który popełnił straszny czyn, powinien być sądzony jak dorosły?',
       'The harm is adult-sized', 'Krzywda jest dorosła',
       'A child''s brain, still', 'To wciąż dziecięcy umysł'),
      ('Justice', false,
       'Is torturing one person ever right if it could save a city?',
       'Czy tortury wobec jednej osoby bywają słuszne, jeśli mogą ocalić miasto?',
       'Thousands of lives', 'Tysiące istnień',
       'Then we become them', 'Wtedy stajemy się nimi'),
      ('Justice', false,
       'Should victims have a say in their offender''s punishment?',
       'Czy ofiary powinny mieć głos przy wymierzaniu kary sprawcy?',
       'It''s their wound', 'To ich rana',
       'Pain is a bad judge', 'Ból to zły sędzia'),
      ('Justice', false,
       'Should even the worst crimes stop being punishable after enough decades?',
       'Czy nawet najgorsze zbrodnie powinny się przedawniać po dziesięcioleciach?',
       'That person no longer exists', 'Tamtego człowieka już nie ma',
       'The victims remember', 'Ofiary pamiętają'),
      ('Justice', false,
       'Should parents be punished for crimes their children commit?',
       'Czy rodzice powinni odpowiadać za czyny swoich dzieci?',
       'Who raised them?', 'Kto ich wychował?',
       'A child is a separate person', 'Dziecko to osobny człowiek'),
      ('Justice', false,
       'If someone breaks into your home, is anything you do to them justified?',
       'Jeśli ktoś włamuje się do twojego domu, czy wszystko, co mu zrobisz, jest usprawiedliwione?',
       'Your home, your castle', 'Twój dom, twoja twierdza',
       'Even a thief has a life', 'Nawet złodziej ma życie'),
      ('Justice', false,
       'Should the rich pay bigger fines for the same offense?',
       'Czy bogaci powinni płacić wyższe grzywny za to samo wykroczenie?',
       'A fine should sting everyone', 'Grzywna ma boleć każdego',
       'One law, one price', 'Jedno prawo, jedna cena'),
      ('Justice', false,
       'Would a short, harsh punishment be more humane than years in prison?',
       'Czy krótka, surowa kara byłaby humanitarniejsza niż lata w więzieniu?',
       'Prison eats whole lives', 'Więzienie pożera całe życie',
       'We left that in the past', 'To zostawiliśmy w przeszłości'),
      ('Justice', false,
       'Should a lifetime of good deeds soften the punishment for one bad one?',
       'Czy całe życie dobrych uczynków powinno łagodzić karę za jeden zły?',
       'Judge the whole person', 'Sądź całego człowieka',
       'The victim met only one', 'Ofiara poznała tylko ten jeden'),
      ('Justice', false,
       'Should very old prisoners who pose no danger be released to die free?',
       'Czy bardzo starzy, już niegroźni więźniowie powinni umierać na wolności?',
       'Punishing a shadow', 'Karzemy już tylko cień',
       'Their victims got no mercy', 'Ich ofiary litości nie dostały'),
      ('Justice', false,
       'Should someone who broke the law to do good still be punished?',
       'Czy ktoś, kto złamał prawo, by czynić dobro, powinien mimo to ponieść karę?',
       'Good intentions, broken law', 'Dobre chęci, złamane prawo',
       'Punish the hero?', 'Karać bohatera?'),
      ('Justice', false,
       'Should an accused person''s name stay secret until they''re proven guilty?',
       'Czy nazwisko oskarżonego powinno pozostać tajne aż do wyroku?',
       'Accusation isn''t guilt', 'Oskarżenie to nie wina',
       'The public deserves to know', 'Ludzie mają prawo wiedzieć'),
      ('Justice', false,
       'Should bad luck make the same reckless act a worse crime?',
       'Czy pech powinien czynić tę samą lekkomyślność cięższym przestępstwem?',
       'Same act, same guilt', 'Ten sam czyn, ta sama wina',
       'Harm is what counts', 'Liczy się krzywda'),
      ('Relationships', false,
       'Is there exactly one right person out there for you?',
       'Czy istnieje dokładnie jedna właściwa osoba dla ciebie?',
       'Some meetings feel fated', 'Niektóre spotkania są jak przeznaczenie',
       'Eight billion people...', 'Osiem miliardów ludzi...'),
      ('Relationships', false,
       'Is love at first sight real love?',
       'Czy miłość od pierwszego wejrzenia to prawdziwa miłość?',
       'Sometimes you just know', 'Czasem po prostu wiesz',
       'You fell for a face', 'Zakochałeś się w twarzy'),
      ('Relationships', false,
       'Can you truly love two people at the same time?',
       'Czy da się naprawdę kochać dwie osoby naraz?',
       'The heart doesn''t count', 'Serce nie liczy',
       'One of them gets less', 'Któreś dostaje mniej'),
      ('Relationships', false,
       'Should couples take separate vacations sometimes?',
       'Czy pary powinny czasem wyjeżdżać na osobne wakacje?',
       'Missing someone is healthy', 'Tęsknota bywa zdrowa',
       'Memories are for sharing', 'Wspomnienia są wspólne'),
      ('Relationships', false,
       'Do separate beds mean a relationship is in trouble?',
       'Czy osobne łóżka oznaczają kłopoty w związku?',
       'Distance starts at night', 'Dystans zaczyna się nocą',
       'Rested people love better', 'Wyspani kochają lepiej'),
      ('Relationships', false,
       'Should you confess a one-time kiss that meant nothing?',
       'Czy przyznać się do jednego pocałunku, który nic nie znaczył?',
       'They deserve the truth', 'Zasługuje na prawdę',
       'Why share the burden?', 'Po co dzielić się ciężarem?'),
      ('Relationships', false,
       'Is it fine to go to sleep angry instead of fighting it out at night?',
       'Czy w porządku jest zasnąć w złości zamiast kłócić się w nocy?',
       'Morning brings wisdom', 'Rano człowiek mądrzejszy',
       'Anger grows overnight', 'Złość rośnie przez noc'),
      ('Relationships', false,
       'Should married couples keep their money fully separate?',
       'Czy małżonkowie powinni trzymać pieniądze całkiem osobno?',
       'Love is not accounting', 'Miłość to nie księgowość',
       'One life, one wallet', 'Jedno życie, jeden portfel'),
      ('Relationships', false,
       'Do couples who argue often love more honestly than those who never fight?',
       'Czy pary, które często się kłócą, kochają szczerzej niż te bez kłótni?',
       'Silence hides more', 'Cisza ukrywa więcej',
       'Peace isn''t pretending', 'Spokój to nie udawanie'),
      ('Relationships', false,
       'Is an emotional affair worse than a physical one?',
       'Czy zdrada emocjonalna jest gorsza niż fizyczna?',
       'Hearts leave first', 'Serce odchodzi pierwsze',
       'Touch crosses the line', 'To dotyk przekracza granicę'),
      ('Relationships', false,
       'Are public proposals unfair pressure on the answer?',
       'Czy oświadczyny przy ludziach to nieuczciwa presja?',
       'Try saying no to a crowd', 'Spróbuj odmówić przy tłumie',
       'Big love, big stage', 'Wielka miłość, wielka scena'),
      ('Relationships', false,
       'Is wanting marriage a good enough reason to leave a happy relationship?',
       'Czy pragnienie ślubu to wystarczający powód, by odejść ze szczęśliwego związku?',
       'Your future matters too', 'Twoja przyszłość też się liczy',
       'Leaving love for paper?', 'Porzucić miłość dla papieru?'),
      ('Relationships', false,
       'Can real love exist without physical attraction?',
       'Czy prawdziwa miłość może istnieć bez fizycznego pociągu?',
       'Souls outlast skin', 'Dusza przetrwa ciało',
       'That''s friendship, not love', 'To przyjaźń, nie miłość'),
      ('Relationships', false,
       'Is jumping into a new relationship right after a breakup a mistake?',
       'Czy wskakiwanie w nowy związek zaraz po rozstaniu to błąd?',
       'You''re dating your pain', 'Umawiasz się ze swoim bólem',
       'Hearts heal in company', 'Serce goi się w towarzystwie'),
      ('Relationships', false,
       'Should partners need each other''s approval for big personal purchases?',
       'Czy partnerzy powinni pytać się nawzajem o zgodę przy dużych zakupach?',
       'Shared life, shared money', 'Wspólne życie, wspólne pieniądze',
       'It''s still your money', 'To wciąż twoje pieniądze'),
      ('Relationships', false,
       'Can a life without romantic love be just as full?',
       'Czy życie bez miłości romantycznej może być równie pełne?',
       'Love has many faces', 'Miłość ma wiele twarzy',
       'Something''s always missing', 'Czegoś zawsze brakuje'),
      ('Relationships', false,
       'Can you fall back in love after the feeling completely dies?',
       'Czy można znów się zakochać, gdy uczucie całkiem wygasło?',
       'Embers can catch again', 'Z żaru bywa płomień',
       'What died stays dead', 'Co umarło, nie wróci'),
      ('Relationships', false,
       'Can a committed couple live in separate homes forever?',
       'Czy oddana sobie para może na zawsze mieszkać osobno?',
       'Closeness isn''t an address', 'Bliskość to nie adres',
       'Home is where they are', 'Dom jest tam, gdzie oni'),
      ('Relationships', false,
       'Should your partner also be your best friend?',
       'Czy partner powinien być też twoim najlepszym przyjacielem?',
       'Marry your best friend', 'Poślub najlepszego przyjaciela',
       'Fire needs mystery', 'Ogień potrzebuje tajemnicy'),
      ('Relationships', false,
       'Does real love mean accepting your partner exactly as they are?',
       'Czy prawdziwa miłość to akceptacja partnera dokładnie takim, jaki jest?',
       'Love is not a project', 'Miłość to nie projekt',
       'Growth is love too', 'Rozwój to też miłość'),
      ('Relationships', false,
       'Can real chemistry grow where there was none at first?',
       'Czy prawdziwa chemia może się pojawić tam, gdzie na początku jej nie było?',
       'Slow fires burn longest', 'Wolny ogień płonie najdłużej',
       'The spark is there or it isn''t', 'Iskra jest albo jej nie ma'),
      ('Relationships', false,
       'Is a workplace romance worth the risk?',
       'Czy biurowy romans jest wart ryzyka?',
       'You spend half your life there', 'Tam spędzasz pół życia',
       'A breakup with an audience', 'Rozstanie przy widowni'),
      ('Relationships', false,
       'Is "taking a break" just a slow way of breaking up?',
       'Czy „przerwa w związku" to tylko powolne rozstanie?',
       'The door is already open', 'Drzwi już są uchylone',
       'Some come back stronger', 'Niektórzy wracają silniejsi'),
      ('Relationships', false,
       'Is growing apart a good enough reason to end a good relationship?',
       'Czy oddalenie się od siebie wystarczy, by zakończyć dobry związek?',
       'Roommates aren''t partners', 'Współlokator to nie partner',
       'Good is worth fighting for', 'O dobre warto walczyć'),
      ('Relationships', false,
       'Should a proposal be decided together rather than sprung as a surprise?',
       'Czy oświadczyny powinny być wspólną decyzją, a nie niespodzianką?',
       'Biggest decision, two voices', 'Największa decyzja — dwa głosy',
       'Magic needs surprise', 'Magia potrzebuje zaskoczenia'),
      ('Relationships', false,
       'Is secretly testing your partner''s loyalty ever justified?',
       'Czy potajemne testowanie wierności partnera bywa usprawiedliwione?',
       'Better to know now', 'Lepiej wiedzieć teraz',
       'The test is the betrayal', 'To test jest zdradą'),
      ('Relationships', false,
       'Is fear of being alone a valid reason to stay in a relationship?',
       'Czy strach przed samotnością to ważny powód, by trwać w związku?',
       'Company beats the void', 'Towarzystwo lepsze niż pustka',
       'You''re wasting two lives', 'Marnujesz dwa życia'),
      ('Relationships', false,
       'Could you truly love someone whose worldview you find wrong?',
       'Czy mógłbyś naprawdę kochać kogoś o poglądach, które uważasz za błędne?',
       'Hearts don''t vote', 'Serce nie głosuje',
       'Values are the foundation', 'Wartości to fundament'),
      ('Relationships', false,
       'Is marrying in your early twenties too soon?',
       'Czy ślub tuż po dwudziestce to za wcześnie?',
       'You barely know yourself', 'Ledwo znasz samego siebie',
       'Growing up together is the point', 'Dorastanie razem to właśnie to'),
      ('Family', false,
       'Should grandparents have a say in how the grandchildren are raised?',
       'Czy dziadkowie powinni mieć głos w wychowaniu wnuków?',
       'They raised you, didn''t they?', 'Ciebie jakoś wychowali',
       'Their time has passed', 'Ich czasy już minęły'),
      ('Family', false,
       'Is living with your parents at thirty nothing to be ashamed of?',
       'Czy mieszkanie z rodzicami po trzydziestce to nic wstydliwego?',
       'Family is not a failure', 'Rodzina to nie porażka',
       'The nest is for leaving', 'Gniazdo jest po to, by wyfrunąć'),
      ('Family', false,
       'Should parents charge rent to adult children living at home?',
       'Czy rodzice powinni brać czynsz od dorosłych dzieci mieszkających w domu?',
       'Welcome to real life', 'Witaj w dorosłości',
       'Charging your own child?', 'Kasować własne dziecko?'),
      ('Family', false,
       'Is giving a child a very unusual name unfair to the child?',
       'Czy nadanie dziecku bardzo nietypowego imienia jest wobec niego nieuczciwe?',
       'They wear it, not you', 'To ono będzie je nosić',
       'Ordinary name, ordinary life?', 'Zwykłe imię, zwykłe życie?'),
      ('Family', false,
       'Should fathers take as much parental leave as mothers?',
       'Czy ojcowie powinni brać tyle samo urlopu rodzicielskiego co matki?',
       'A child has two parents', 'Dziecko ma dwoje rodziców',
       'Nature set the roles?', 'Natura rozdała role?'),
      ('Family', false,
       'Is it fair to a child to become a parent after fifty?',
       'Czy zostanie rodzicem po pięćdziesiątce jest fair wobec dziecka?',
       'Wisdom raises well', 'Mądrość dobrze wychowuje',
       'Count the years ahead', 'Policz wspólne lata'),
      ('Family', false,
       'Is a parent at home better for a small child than the best daycare?',
       'Czy rodzic w domu jest lepszy dla małego dziecka niż najlepszy żłobek?',
       'No one replaces a parent', 'Nikt nie zastąpi rodzica',
       'Kids need kids', 'Dzieci potrzebują dzieci'),
      ('Family', false,
       'Can a parent be their child''s best friend?',
       'Czy rodzic może być najlepszym przyjacielem swojego dziecka?',
       'Trust opens every door', 'Zaufanie otwiera wszystko',
       'A friend can''t say no', 'Przyjaciel nie umie zakazać'),
      ('Family', false,
       'Is a shared family dinner every day worth sacrificing other plans for?',
       'Czy wspólny rodzinny posiłek codziennie jest wart poświęcenia innych planów?',
       'The table holds the family', 'Stół trzyma rodzinę razem',
       'Forced together isn''t together', 'Przymus to nie bliskość'),
      ('Family', false,
       'Is it okay for parents to take a vacation without the kids?',
       'Czy rodzice mogą jechać na wakacje bez dzieci?',
       'Happy parents, happy kids', 'Szczęśliwi rodzice, szczęśliwe dzieci',
       'Family memories can''t wait', 'Rodzinne wspomnienia nie zaczekają'),
      ('Family', false,
       'Do you owe a sibling closeness just because you share blood?',
       'Czy jesteś winien rodzeństwu bliskość tylko dlatego, że łączy was krew?',
       'No one else shares your story', 'Nikt inny nie zna twojej historii',
       'Family isn''t chosen', 'Rodziny się nie wybiera'),
      ('Family', false,
       'Do parents owe their children help with paying for education?',
       'Czy rodzice są winni dzieciom pomoc w opłaceniu edukacji?',
       'You brought them here', 'To ty ich tu sprowadziłeś',
       'Struggle builds adults', 'Trud tworzy dorosłych'),
      ('Family', false,
       'Should parents ever argue in front of their children?',
       'Czy rodzice mogą kłócić się przy dzieciach?',
       'Kids learn how to disagree', 'Dzieci uczą się, jak się spierać',
       'Home should feel safe', 'Dom ma być bezpieczny'),
      ('Family', false,
       'Does family always deserve priority over friends?',
       'Czy rodzina zawsze zasługuje na pierwszeństwo przed przyjaciółmi?',
       'Friends come and go', 'Przyjaciele przychodzą i odchodzą',
       'Some friends are more family', 'Bywa przyjaciel bliższy niż brat'),
      ('Family', false,
       'Is telling kids they can be anything setting them up for disappointment?',
       'Czy mówienie dzieciom, że mogą być, kim zechcą, szykuje im rozczarowanie?',
       'Not everyone gets the dream', 'Nie każdy dostaje marzenie',
       'Belief is rocket fuel', 'Wiara to paliwo'),
      ('Family', false,
       'Should you be allowed to scold a stranger''s misbehaving child?',
       'Czy wolno zwrócić uwagę cudzemu niegrzecznemu dziecku?',
       'It takes a village', 'Całą wioską się wychowuje',
       'Not your child, not your job', 'Nie twoje dziecko, nie twoja rola'),
      ('Family', false,
       'Is growing up with siblings better than growing up as an only child?',
       'Czy dorastanie z rodzeństwem jest lepsze niż bycie jedynakiem?',
       'A built-in team for life', 'Drużyna na całe życie',
       'All the love, undivided', 'Cała miłość, niepodzielona'),
      ('Family', false,
       'Should families discuss inheritance openly before anyone dies?',
       'Czy rodziny powinny otwarcie rozmawiać o spadku, zanim ktokolwiek umrze?',
       'Silence breeds wars', 'Milczenie rodzi wojny',
       'Counting before the funeral?', 'Liczenie przed pogrzebem?'),
      ('Family', false,
       'Would you take a DNA test knowing it might expose family secrets?',
       'Czy zrobiłbyś test DNA, wiedząc, że może ujawnić rodzinne sekrety?',
       'The truth is in you', 'Prawda jest w tobie',
       'Some doors never close again', 'Niektórych drzwi się nie zamknie'),
      ('Family', false,
       'Should a stepparent have the same authority as a birth parent?',
       'Czy macocha lub ojczym powinni mieć taki sam głos jak rodzic?',
       'Same home, same rules', 'Jeden dom, jedne zasady',
       '"You''re not my mom"', '„Nie jesteś moją mamą"'),
      ('Family', false,
       'Should you spend holidays with family even when it makes you miserable?',
       'Czy spędzać święta z rodziną, nawet gdy cię to unieszczęśliwia?',
       'Traditions outlast moods', 'Tradycja przetrwa humory',
       'Misery isn''t love', 'Cierpienie to nie miłość'),
      ('Family', false,
       'Should adult children take the car keys from an unsafe elderly parent?',
       'Czy dorosłe dzieci powinny odebrać kluczyki niebezpiecznie jeżdżącemu starszemu rodzicowi?',
       'Safety before pride', 'Bezpieczeństwo przed dumą',
       'You''re taking their freedom', 'Zabierasz im wolność'),
      ('Family', false,
       'Should children be expected to take over the family business?',
       'Czy od dzieci wypada oczekiwać przejęcia rodzinnej firmy?',
       'Generations built it', 'Budowały ją pokolenia',
       'Their life, their path', 'Ich życie, ich droga'),
      ('Family', false,
       'Would you read a late parent''s private letters?',
       'Czy przeczytałbyś prywatne listy zmarłego rodzica?',
       'One last conversation', 'Ostatnia rozmowa',
       'They never showed you', 'Za życia ich nie pokazali'),
      ('Family', false,
       'Is spoiling the grandchildren a grandparent''s right?',
       'Czy rozpieszczanie wnuków to przywilej dziadków?',
       'They did the hard part already', 'Swoje już odchowali',
       'Someone must undo the damage', 'Ktoś to potem musi odkręcić'),
      ('Family', false,
       'Should young children be taken to funerals?',
       'Czy małe dzieci powinny chodzić na pogrzeby?',
       'Grief is learned together', 'Żałoby uczymy się razem',
       'Let them stay children', 'Niech zostaną dziećmi'),
      ('Friendship', false,
       'Can you be close friends with someone whose values you reject?',
       'Czy da się przyjaźnić z kimś, czyje wartości odrzucasz?',
       'Friendship isn''t agreement', 'Przyjaźń to nie zgodność poglądów',
       'Values are who they are', 'Wartości to on sam'),
      ('Friendship', false,
       'Is gossiping about friends a normal part of friendship?',
       'Czy plotkowanie o przyjaciołach to normalna część przyjaźni?',
       'Everyone does it', 'Każdy to robi',
       'They gossip about you too', 'O tobie też plotkują'),
      ('Friendship', false,
       'Can a man and a woman ever be just friends?',
       'Czy mężczyzna i kobieta mogą być tylko przyjaciółmi?',
       'Millions manage it daily', 'Milionom się udaje',
       'Someone always wonders', 'Ktoś zawsze się zastanawia'),
      ('Friendship', false,
       'Is inventing an excuse to skip a social event okay?',
       'Czy wymyślenie wymówki, by ominąć spotkanie, jest w porządku?',
       'A kind lie spares feelings', 'Litościwe kłamstwo oszczędza uczucia',
       'Friends deserve the truth', 'Przyjaciołom mówi się prawdę'),
      ('Friendship', false,
       'Is being always late a quiet form of disrespect?',
       'Czy wieczne spóźnianie się to cicha forma braku szacunku?',
       'You''re spending their time', 'Wydajesz cudzy czas',
       'Some people just run late', 'Niektórzy tak po prostu mają'),
      ('Friendship', false,
       'Is small talk a waste of time?',
       'Czy small talk to strata czasu?',
       'Say something real or nothing', 'Mów naprawdę albo wcale',
       'Every friendship starts small', 'Każda przyjaźń zaczyna się od drobiazgów'),
      ('Friendship', false,
       'Is it okay to end a friendship without any explanation?',
       'Czy można zakończyć przyjaźń bez słowa wyjaśnienia?',
       'You owe yourself peace', 'Spokój należy się tobie',
       'Years deserve a goodbye', 'Lata zasługują na pożegnanie'),
      ('Friendship', false,
       'Is staying at a friend''s place for weeks without paying taking advantage?',
       'Czy tygodnie pomieszkiwania u przyjaciela za darmo to wykorzystywanie?',
       'Hospitality has limits', 'Gościnność ma granice',
       'A friend''s door is always open', 'Drzwi przyjaciela są zawsze otwarte'),
      ('Friendship', false,
       'Can you stay true friends with someone you directly compete with?',
       'Czy da się szczerze przyjaźnić z kimś, z kim bezpośrednio rywalizujesz?',
       'Iron sharpens iron', 'Żelazo ostrzy żelazo',
       'Only one gets the prize', 'Nagroda jest jedna'),
      ('Friendship', false,
       'Should friends pay each other full price for professional work?',
       'Czy przyjaciele powinni płacić sobie pełną cenę za profesjonalną pracę?',
       'Skills pay the bills', 'Fach to fach',
       'What are friends for?', 'Od czego są przyjaciele?'),
      ('Friendship', false,
       'Must you invite someone just because they invited you?',
       'Czy musisz kogoś zaprosić tylko dlatego, że on zaprosił ciebie?',
       'Courtesy is a circle', 'Uprzejmość to krąg',
       'An invitation isn''t a debt', 'Zaproszenie to nie dług'),
      ('Friendship', false,
       'Can a written apology mean as much as one said face to face?',
       'Czy pisemne przeprosiny mogą znaczyć tyle, co te twarzą w twarz?',
       'Words are words', 'Słowa to słowa',
       'Eyes can''t hide', 'Oczy nie kłamią'),
      ('Friendship', false,
       'Is a compliment you don''t mean still a kindness?',
       'Czy komplement, w który nie wierzysz, to wciąż życzliwość?',
       'Costs nothing, gives much', 'Nic nie kosztuje, wiele daje',
       'It''s still a lie', 'To nadal kłamstwo'),
      ('Friendship', false,
       'Should you always defend an absent friend when others mock them?',
       'Czy zawsze bronić nieobecnego przyjaciela, gdy inni z niego szydzą?',
       'That''s what friends are for', 'Po to są przyjaciele',
       'Sometimes it''s just a joke', 'Czasem to tylko żart'),
      ('Friendship', false,
       'Is having one "best" friend unfair to the others?',
       'Czy posiadanie jednego „najlepszego" przyjaciela jest nie fair wobec pozostałych?',
       'Nobody likes second place', 'Nikt nie lubi drugiego miejsca',
       'Hearts have podiums', 'Serce ma swoje podium'),
      ('Friendship', false,
       'Should close friends share their live location with each other?',
       'Czy bliscy przyjaciele powinni udostępniać sobie lokalizację na żywo?',
       'Nothing to hide, right?', 'Przecież nie masz nic do ukrycia',
       'Friendship isn''t surveillance', 'Przyjaźń to nie nadzór'),
      ('Friendship', false,
       'Are empty phrases like "let''s catch up soon" harmless?',
       'Czy puste obietnice w stylu „musimy się spotkać" są niewinne?',
       'It''s just social music', 'To tylko towarzyska melodia',
       'Words should mean something', 'Słowa powinny coś znaczyć'),
      ('Friendship', false,
       'Is showing up at a friend''s door unannounced okay these days?',
       'Czy wpadanie do przyjaciela bez zapowiedzi jest dziś w porządku?',
       'Spontaneity keeps us alive', 'Spontaniczność to życie',
       'My home, my calendar', 'Mój dom, mój kalendarz'),
      ('Friendship', false,
       'Can a host insist that guests take their shoes off?',
       'Czy gospodarz może wymagać od gości zdjęcia butów?',
       'Their floor, their rules', 'Ich podłoga, ich zasady',
       'Guests'' comfort comes first', 'Wygoda gości przede wszystkim'),
      ('Friendship', false,
       'Does telling your partner a friend''s secret still count as keeping it?',
       'Czy zdradzenie sekretu przyjaciela partnerowi to wciąż dochowanie tajemnicy?',
       'Couples share everything', 'Para dzieli wszystko',
       'A secret has one owner', 'Sekret ma jednego właściciela'),
      ('Friendship', false,
       'Do birthdays stop mattering once you''re an adult?',
       'Czy urodziny przestają mieć znaczenie w dorosłości?',
       'It''s just another Tuesday', 'To tylko kolejny wtorek',
       'One day a year is yours', 'Jeden dzień w roku jest twój'),
      ('Friendship', false,
       'Can you be true friends with your boss?',
       'Czy można się naprawdę przyjaźnić z własnym szefem?',
       'A person is a person', 'Człowiek to człowiek',
       'Power poisons friendship', 'Władza zatruwa przyjaźń'),
      ('Friendship', false,
       'Can you stay close to both people after their breakup?',
       'Czy po rozstaniu pary da się zostać blisko z obojgiem?',
       'You befriended two people', 'Przyjaźniłeś się z dwojgiem ludzi',
       'Sooner or later, you choose', 'Prędzej czy później wybierzesz'),
      ('Friendship', false,
       'Is muting a friend online while staying friends offline okay?',
       'Czy wyciszenie przyjaciela w sieci przy przyjaźni na żywo jest w porządku?',
       'Protect the feed, keep the friend', 'Chronisz feed, nie przyjaźń',
       'You muted their life', 'Wyciszyłeś jego życie'),
      ('Friendship', false,
       'When two friends fight, is staying neutral the coward''s way out?',
       'Czy gdy dwoje przyjaciół się kłóci, neutralność to tchórzostwo?',
       'Silence picks a side too', 'Milczenie też wybiera stronę',
       'It''s not your war', 'To nie twoja wojna'),
      ('Friendship', false,
       'Are friends you only share one activity with real friends?',
       'Czy znajomi tylko od jednej aktywności to prawdziwi przyjaciele?',
       'Shared joy is enough', 'Wspólna radość wystarczy',
       'Would they visit the hospital?', 'Przyszliby do szpitala?'),
      ('Friendship', false,
       'Can a favor with strings attached still be kindness?',
       'Czy przysługa z haczykiem to wciąż życzliwość?',
       'Help is help', 'Pomoc to pomoc',
       'That''s a transaction', 'To już transakcja'),
      ('Friendship', false,
       'Is arriving too early almost as rude as arriving late?',
       'Czy przyjście za wcześnie jest prawie tak niegrzeczne jak spóźnienie?',
       'The host isn''t ready', 'Gospodarz nie jest gotowy',
       'Eagerness isn''t a sin', 'Zapał to nie grzech'),
      ('Money', false,
       'Would a sudden huge fortune ruin most people''s lives?',
       'Czy nagła wielka fortuna zrujnowałaby życie większości ludzi?',
       'Money amplifies who you are', 'Pieniądze wzmacniają to, kim jesteś',
       'Problems prefer poverty', 'Problemy wolą biedę'),
      ('Money', false,
       'Is renting your home really throwing money away?',
       'Czy wynajmowanie mieszkania to naprawdę wyrzucanie pieniędzy?',
       'You''re paying someone''s loan', 'Spłacasz cudzy kredyt',
       'Freedom has no mortgage', 'Wolność nie ma hipoteki'),
      ('Money', false,
       'Is pocketing a banknote you find on the street wrong?',
       'Czy zabranie znalezionego na ulicy banknotu jest złe?',
       'Someone is looking for it', 'Ktoś go szuka',
       'Finders keepers', 'Znalezione nie kradzione'),
      ('Money', false,
       'Is buying fake designer goods harmless?',
       'Czy kupowanie podróbek znanych marek jest niewinne?',
       'Only egos get hurt', 'Cierpi tylko czyjeś ego',
       'Someone made the real thing', 'Ktoś stworzył oryginał')
    ) as s(category, is_premium, en, pl, a1en, a1pl, a2en, a2pl)
  loop
    -- skip if this EN text was already seeded
    if exists (
      select 1 from public.question_translations
      where locale = 'en' and question_text = r.en
    ) then
      continue;
    end if;

    insert into public.questions (category, is_premium)
    values (r.category, r.is_premium)
    returning id into qid;

    insert into public.question_translations (question_id, locale, question_text)
    values (qid, 'en', r.en),
           (qid, 'pl', r.pl);

    -- smaczek 1 (free teaser)
    insert into public.question_smaczki (question_id, position, is_active)
    values (qid, 1, true)
    returning id into s1;
    insert into public.question_smaczki_translations (smaczek_id, locale, text)
    values (s1, 'en', r.a1en),
           (s1, 'pl', r.a1pl);

    -- smaczek 2 (premium)
    insert into public.question_smaczki (question_id, position, is_active)
    values (qid, 2, true)
    returning id into s2;
    insert into public.question_smaczki_translations (smaczek_id, locale, text)
    values (s2, 'en', r.a2en),
           (s2, 'pl', r.a2pl);
  end loop;
end $$;

-- ----------------------------------------------------------------------------
-- Schedule every still-unscheduled active question onto the next free dates.
-- Keeps Strategy A (unique question_id) intact.
-- ----------------------------------------------------------------------------
insert into public.daily_questions (publish_date, question_id)
select dates.d::date, q.id
from (
  select d, row_number() over (order by d) rn
  from generate_series(current_date, current_date + 1499, '1 day'::interval) d
  where d::date not in (select publish_date from public.daily_questions)
) dates
join (
  select id, row_number() over (order by random()) rn
  from public.questions
  where is_active
    and id not in (select question_id from public.daily_questions)
) q on q.rn = dates.rn
on conflict do nothing;

commit;
