-- ============================================================================
-- Seed: 106 globally-applicable debate questions (PL + EN) + 2 smaczki each
-- ----------------------------------------------------------------------------
-- Generated 2026-06-25. A large batch of YES/NO ("TAK/NIE") questions that are
-- deliberately GLOBAL: every one is a universal moral/values/life dilemma that
-- a person in any country can debate. No country-, law-, currency-, or
-- institution-specific framings (those vary by jurisdiction and were excluded).
-- A mix of heavy ethics, justice, relationships, family, money, work, tech,
-- environment, health and culture -- all chosen to split people ~50/50.
--
-- Each question gets exactly TWO "smaczki" (discussion angles), bilingual:
--   position 1 -> shown FREE (strongest hook)
--   position 2 -> premium-gated
-- This matches the product cap of max two smaczki per question
-- (see 20260623120000_trim_smaczki_to_max_two.sql) and the get_question_smaczki
-- RPC gating (position 1 free, rest premium).
--
-- Idempotent: each question is keyed on its EN text, so re-running skips rows
-- that already exist (no duplicate translations or smaczki). One row at a time
-- so the freshly generated ids map to the right PL/EN pair and smaczki.
-- ============================================================================

begin;

-- ----------------------------------------------------------------------------
-- 1) Insert each question + both translations + its two bilingual smaczki.
-- ----------------------------------------------------------------------------
do $$
declare
  r   record;
  qid uuid;
  s1  uuid;
  s2  uuid;
begin
  for r in
    select * from (values
      ('Ethics', false,
       'Would you confess to a crime you didn''t commit to protect someone you love?',
       'Czy przyznałbyś się do winy, której nie popełniłeś, by chronić kogoś, kogo kochasz?',
       'Love or truth?', 'Miłość czy prawda?',
       'And the real culprit?', 'A prawdziwy sprawca?'),
      ('Ethics', true,
       'Does a good intention matter more than the harm it causes?',
       'Czy dobra intencja liczy się bardziej niż wyrządzona przez nią krzywda?',
       'Judge the heart?', 'Sądzić serce?',
       'Tell that to the victim', 'Powiedz to ofierze'),
      ('Ethics', false,
       'Is it right to sacrifice one innocent person to save many?',
       'Czy wolno poświęcić jednego niewinnego, by ocalić wielu?',
       'Numbers don''t lie?', 'Liczby nie kłamią?',
       'Who plays God?', 'Kto gra Boga?'),
      ('Justice', false,
       'Is revenge ever justified?',
       'Czy zemsta bywa usprawiedliwiona?',
       'Justice by your hand?', 'Sprawiedliwość własną ręką?',
       'Where does it end?', 'Gdzie się to kończy?'),
      ('Justice', true,
       'Should someone who hurt others be helped rather than punished?',
       'Czy ten, kto skrzywdził innych, powinien być raczej leczony niż karany?',
       'People can change?', 'Ludzie się zmieniają?',
       'And the victim?', 'A ofiara?'),
      ('Ethics', false,
       'Should some secrets be taken to the grave?',
       'Czy niektóre sekrety należy zabrać do grobu?',
       'Mercy in silence?', 'Litość w milczeniu?',
       'Whose burden is it?', 'Czyj to ciężar?'),
      ('Ethics', true,
       'Is it right to lie to a dying person to give them peace?',
       'Czy wolno okłamać umierającego, by dać mu spokój?',
       'Kindness or cowardice?', 'Dobroć czy tchórzostwo?',
       'Steal their goodbye?', 'Odebrać im pożegnanie?'),
      ('Ethics', false,
       'Are some acts simply unforgivable?',
       'Czy istnieją czyny po prostu niewybaczalne?',
       'Limits of mercy?', 'Granice litości?',
       'Is anyone beyond saving?', 'Czy ktoś jest bez ratunku?'),
      ('Ethics', true,
       'Should you betray a friend to do what''s right?',
       'Czy należy zdradzić przyjaciela, by postąpić słusznie?',
       'Loyalty above all?', 'Lojalność ponad wszystko?',
       'Silence makes you guilty?', 'Milczenie czyni cię winnym?'),
      ('Justice', false,
       'Would you turn in a family member who committed a serious crime?',
       'Czy wydałbyś członka rodziny, który popełnił ciężki czyn?',
       'Blood or conscience?', 'Krew czy sumienie?',
       'Who''s next?', 'Kto będzie następny?'),
      ('Ethics', true,
       'Is a parent right to kill a stranger to save their own child?',
       'Czy rodzic ma rację, zabijając obcego, by ratować własne dziecko?',
       'Instinct above law?', 'Instynkt ponad prawem?',
       'Whose child is worth less?', 'Czyje dziecko mniej warte?'),
      ('Ethics', false,
       'Should you tell a truth that will only cause pain?',
       'Czy mówić prawdę, która przyniesie tylko ból?',
       'Truth at any cost?', 'Prawda za każdą cenę?',
       'Whose pain, really?', 'Czyj to tak naprawdę ból?'),
      ('Ethics', true,
       'Can a good person commit a truly evil act and stay good?',
       'Czy dobry człowiek może popełnić zło i pozostać dobrym?',
       'One act defines us?', 'Jeden czyn nas definiuje?',
       'We''re the whole story', 'Liczy się cała historia'),
      ('Justice', false,
       'Is someone guilty for wanting to do harm they never did?',
       'Czy ktoś jest winny za chęć krzywdy, której nie wyrządził?',
       'Only deeds count?', 'Liczą się tylko czyny?',
       'What stopped you?', 'Co cię powstrzymało?'),
      ('Justice', true,
       'Does someone who harmed many still deserve mercy?',
       'Czy ten, kto skrzywdził wielu, wciąż zasługuje na litość?',
       'Mercy has no limit?', 'Litość bez granic?',
       'Can it be earned back?', 'Da się ją odzyskać?'),
      ('Ethics', false,
       'Is someone guilty for following orders they knew were wrong?',
       'Czy ktoś jest winny, wykonując rozkazy, które uważał za złe?',
       'Just following orders?', 'Tylko wykonywał rozkazy?',
       'You knew better', 'Wiedziałeś swoje'),
      ('Ethics', true,
       'Is violence ever the only moral choice?',
       'Czy przemoc bywa jedynym moralnym wyjściem?',
       'Stand by and watch?', 'Stać i patrzeć?',
       'It only breeds more', 'Rodzi tylko kolejną'),
      ('Ethics', false,
       'Is doing nothing while harm happens as bad as causing it?',
       'Czy bierność wobec krzywdy jest tak samo zła jak jej wyrządzenie?',
       'Silence is a choice?', 'Milczenie to wybór?',
       'You didn''t start it', 'Nie ty zacząłeś'),
      ('Ethics', true,
       'Are you morally obliged to risk your life for a stranger?',
       'Czy masz moralny obowiązek ryzykować życie dla obcego?',
       'We owe each other?', 'Jesteśmy sobie coś winni?',
       'Your life is yours', 'Twoje życie należy do ciebie'),
      ('Relationships', false,
       'Should you ever fully trust someone who betrayed you once?',
       'Czy można w pełni zaufać komuś, kto raz cię zdradził?',
       'People grow?', 'Ludzie dojrzewają?',
       'Once a traitor?', 'Raz zdrajca, zawsze zdrajca?'),
      ('Justice', true,
       'Should someone who steals out of desperation be punished?',
       'Czy karać kogoś, kto kradnie z rozpaczy?',
       'Hunger excuses it?', 'Głód usprawiedliwia?',
       'Then who pays?', 'To kto za to płaci?'),
      ('Ethics', true,
       'Must you keep a promise to someone who has died?',
       'Czy trzeba dotrzymać obietnicy danej komuś, kto już nie żyje?',
       'A word still binds?', 'Słowo wciąż wiąże?',
       'For them or for you?', 'Dla nich czy dla siebie?'),
      ('Relationships', false,
       'Should you reveal a friend''s affair to their partner?',
       'Czy ujawnić zdradę przyjaciela jego partnerowi?',
       'Not your secret?', 'Nie twój sekret?',
       'Living a lie too?', 'Też żyje w kłamstwie?'),
      ('Justice', true,
       'Should a person be judged forever by their worst act?',
       'Czy człowiek ma być na zawsze oceniany przez swój najgorszy czyn?',
       'It defines them?', 'To ich definiuje?',
       'Who hasn''t fallen?', 'Kto nigdy nie upadł?'),
      ('Ethics', false,
       'Is it wrong to break the rules to feed your starving family?',
       'Czy łamanie zasad, by nakarmić głodującą rodzinę, jest złem?',
       'Survival first?', 'Najpierw przetrwać?',
       'Rules bend for all?', 'Zasady nagną się dla każdego?'),
      ('Freedom', true,
       'Should one person''s freedom be sacrificed for the good of everyone?',
       'Czy wolność jednostki można poświęcić dla dobra ogółu?',
       'The greater good?', 'Dobro ogółu?',
       'Who gets sacrificed?', 'Kto zostanie poświęcony?'),
      ('Ethics', false,
       'Would you lie under oath to spare your family from ruin?',
       'Czy skłamałbyś pod przysięgą, by uchronić rodzinę przed ruiną?',
       'Family above all?', 'Rodzina ponad wszystko?',
       'And the one you lie about?', 'A ten, kogo to skrzywdzi?'),
      ('Ethics', true,
       'Should you forgive someone for your own peace, even if they aren''t sorry?',
       'Czy wybaczyć dla własnego spokoju, nawet gdy druga strona nie żałuje?',
       'Freedom for you?', 'Wolność dla ciebie?',
       'Lets them off?', 'Puszczasz im płazem?'),
      ('Family', false,
       'Should you tell a child a painful truth instead of a kind lie?',
       'Czy mówić dziecku bolesną prawdę zamiast łagodnego kłamstwa?',
       'Protect their innocence?', 'Chronić niewinność?',
       'Truth makes them strong?', 'Prawda ich wzmacnia?'),
      ('Justice', true,
       'Should punishment match the suffering a wrongdoer caused?',
       'Czy kara powinna odpowiadać cierpieniu, które sprawca wyrządził?',
       'Eye for an eye?', 'Oko za oko?',
       'Drags us down too?', 'Nas też pociąga w dół?'),
      ('Ethics', false,
       'Would you abandon a cause you believe in to save one person you love?',
       'Czy porzuciłbyś sprawę, w którą wierzysz, by ocalić jedną ukochaną osobę?',
       'One face over millions?', 'Jedna twarz nad tłumem?',
       'Principles over people?', 'Zasady ponad ludźmi?'),
      ('Ethics', true,
       'Must you confess a past wrong no one will ever discover?',
       'Czy trzeba wyznać dawne zło, którego nikt nigdy nie odkryje?',
       'Conscience demands it?', 'Sumienie żąda?',
       'Confess for whose sake?', 'Wyznać dla czyjego dobra?'),
      ('Ethics', false,
       'Should you warn someone making a terrible choice that is theirs to make?',
       'Czy ostrzegać kogoś przed złym wyborem, który należy tylko do niego?',
       'Their life, their call', 'Ich życie, ich wybór',
       'Care means speaking up?', 'Troska to odwaga mówić?'),
      ('Freedom', true,
       'Would you give up some freedom for a guarantee of safety?',
       'Czy oddałbyś część wolności za gwarancję bezpieczeństwa?',
       'Safety above all?', 'Bezpieczeństwo ponad wszystko?',
       'A comfortable cage?', 'Wygodna klatka?'),
      ('Ethics', false,
       'Should you spare an enemy who is now defenseless?',
       'Czy oszczędzić wroga, który jest teraz bezbronny?',
       'Mercy keeps us human?', 'Litość czyni nas ludźmi?',
       'He''d never spare you', 'On by cię nie oszczędził'),
      ('Relationships', false,
       'Is it ever okay to secretly read your partner''s phone?',
       'Czy wolno potajemnie czytać telefon partnera?',
       'And the trust?', 'A zaufanie?',
       'Why so afraid?', 'Czego się boisz?'),
      ('Family', false,
       'Should an unhappy couple stay together for the children?',
       'Czy nieszczęśliwa para powinna zostać razem dla dzieci?',
       'Kids feel the cracks', 'Dzieci czują fałsz',
       'A home worth keeping?', 'Dom wart ratowania?'),
      ('Relationships', true,
       'Should you tell a friend that their partner is cheating?',
       'Czy powiedzieć przyjacielowi, że partner go zdradza?',
       'They deserve to know', 'Mają prawo wiedzieć',
       'Shooting the messenger?', 'Posłaniec zawsze winny?'),
      ('Family', false,
       'Do grown children owe their aging parents care?',
       'Czy dorosłe dzieci są winne opiekę starzejącym się rodzicom?',
       'They raised you', 'Wychowali cię',
       'What if they failed you?', 'A jeśli cię zawiedli?'),
      ('Relationships', false,
       'Do couples who are very similar last longer than opposites?',
       'Czy bardzo podobne pary trwają dłużej niż przeciwieństwa?',
       'Fewer clashes?', 'Mniej zgrzytów?',
       'Where''s the spark?', 'Gdzie iskra?'),
      ('Relationships', true,
       'Can a relationship truly survive years of long distance?',
       'Czy związek na odległość naprawdę przetrwa lata?',
       'Distance deepens it?', 'Odległość pogłębia uczucie?',
       'Love needs touch', 'Miłość potrzebuje bliskości'),
      ('Family', false,
       'Is it okay to lie to your family to keep the peace?',
       'Czy wolno okłamywać rodzinę dla świętego spokoju?',
       'Peace over truth?', 'Spokój ponad prawdę?',
       'Lies pile up', 'Kłamstwa się piętrzą'),
      ('Family', true,
       'Is choosing to have children a selfish decision?',
       'Czy decyzja o posiadaniu dzieci jest egoistyczna?',
       'Whose dream is it?', 'Czyje to marzenie?',
       'The gift of life?', 'Dar życia?'),
      ('Relationships', false,
       'Should you keep a long friendship when you''ve grown apart?',
       'Czy utrzymywać starą przyjaźń, gdy się oddaliliście?',
       'Shared history counts', 'Wspólna przeszłość ma wagę',
       'Just nostalgia?', 'Tylko nostalgia?'),
      ('Relationships', true,
       'Is it wrong to let a partner''s wealth affect your attraction?',
       'Czy to złe, gdy zamożność partnera wpływa na uczucia?',
       'Security is real', 'Stabilność też się liczy',
       'Loving the wallet?', 'Kochasz portfel?'),
      ('Relationships', true,
       'Can a relationship be saved after one partner cheats?',
       'Czy związek da się uratować po zdradzie?',
       'Stronger than before?', 'Silniejsi niż wcześniej?',
       'Trust once broken', 'Raz złamane zaufanie'),
      ('Relationships', false,
       'Should your partner always come before your best friend?',
       'Czy partner zawsze powinien być ważniejszy niż przyjaciel?',
       'Friends outlast lovers?', 'Przyjaźń przetrwa miłość?',
       'You build a life together', 'Z partnerem budujesz życie'),
      ('Relationships', false,
       'Should a couple always split every cost down the middle?',
       'Czy para zawsze powinna dzielić koszty po połowie?',
       'Equal is fair?', 'Równo znaczy uczciwie?',
       'But incomes differ', 'A zarobki bywają różne'),
      ('Relationships', true,
       'Is marriage an outdated idea in the modern world?',
       'Czy małżeństwo to przestarzała idea w dzisiejszym świecie?',
       'Love needs no paper', 'Miłość nie potrzebuje papieru',
       'A promise that holds', 'Obietnica, która trzyma'),
      ('Relationships', false,
       'Should you forgive a friend who betrayed your secret?',
       'Czy wybaczyć przyjacielowi, który zdradził twój sekret?',
       'Everyone slips once?', 'Każdemu raz się zdarzy?',
       'Some things are sacred', 'Pewne rzeczy są święte'),
      ('Relationships', false,
       'Is a little jealousy a healthy sign of love?',
       'Czy odrobina zazdrości to zdrowy znak miłości?',
       'Proof they care?', 'Dowód, że mu zależy?',
       'First step to control', 'Pierwszy krok do kontroli'),
      ('Relationships', true,
       'Should you give up your career to follow a partner''s job?',
       'Czy porzucić własną karierę dla pracy partnera?',
       'Love is a team sport', 'Miłość to gra zespołowa',
       'Lose yourself?', 'Zgubisz siebie?'),
      ('Relationships', false,
       'Is it possible to stay genuine friends with an ex?',
       'Czy da się zostać szczerymi przyjaciółmi z byłym?',
       'Feelings linger?', 'Uczucia zostają?',
       'Why burn a good bond?', 'Po co palić dobrą więź?'),
      ('Family', false,
       'Is it wrong to tell children comforting lies about the world?',
       'Czy to złe, by opowiadać dzieciom pocieszające kłamstwa o świecie?',
       'Protect their wonder', 'Chronić magię dzieciństwa',
       'When do you stop?', 'Kiedy przestać?'),
      ('Family', true,
       'Do strict parents raise more successful children?',
       'Czy surowi rodzice wychowują bardziej udane dzieci?',
       'Discipline builds grit', 'Dyscyplina hartuje',
       'Fear isn''t respect', 'Strach to nie szacunek'),
      ('Relationships', true,
       'Should you ever lend money to a close friend?',
       'Czy w ogóle warto pożyczać pieniądze bliskiemu przyjacielowi?',
       'Friends help friends', 'Przyjaciel pomoże',
       'Money kills bonds?', 'Pieniądze niszczą więzi?'),
      ('Relationships', true,
       'Should you admit to a partner that you find someone else attractive?',
       'Czy przyznać partnerowi, że ktoś inny ci się podoba?',
       'Total honesty?', 'Pełna szczerość?',
       'Why wound them?', 'Po co ranić bez powodu?'),
      ('Family', true,
       'Is it wrong to place an aging parent in a care home?',
       'Czy to złe oddać starszego rodzica do domu opieki?',
       'Better care there?', 'Lepsza opieka na miejscu?',
       'Or just convenient?', 'Czy po prostu wygodniej?'),
      ('Relationships', true,
       'Does asking for a prenuptial agreement betray true love?',
       'Czy żądanie intercyzy zdradza brak prawdziwej miłości?',
       'Planning to fail?', 'Planujesz porażkę?',
       'Just being smart?', 'Po prostu rozsądek?'),
      ('Family', false,
       'Is it okay to cut off family members who hurt you?',
       'Czy wolno zerwać kontakt z raniącą cię rodziną?',
       'Blood is blood?', 'Krew to krew?',
       'Protect your peace', 'Chroń swój spokój'),
      ('Relationships', true,
       'Does a big age gap doom a romantic relationship?',
       'Czy duża różnica wieku skazuje związek na porażkę?',
       'Age is just a number?', 'Wiek to tylko liczba?',
       'Worlds apart?', 'Dwa różne światy?'),
      ('Relationships', true,
       'Should committed partners share all their passwords?',
       'Czy partnerzy w związku powinni dzielić się hasłami?',
       'Nothing to hide?', 'Nic do ukrycia?',
       'Still your own person', 'Wciąż masz siebie'),
      ('Relationships', false,
       'Does everyone deserve a second chance after a bad breakup?',
       'Czy każdy zasługuje na drugą szansę po złym rozstaniu?',
       'People grow', 'Ludzie dojrzewają',
       'Patterns repeat', 'Wzorce wracają'),
      ('Family', true,
       'Can a marriage be fully complete without children?',
       'Czy małżeństwo może być spełnione bez dzieci?',
       'Two is enough', 'Dwoje wystarczy',
       'Something missing?', 'Czegoś brakuje?'),
      ('Relationships', false,
       'Is it wrong to keep track of who gives more in a relationship?',
       'Czy to złe liczyć, kto daje więcej w związku?',
       'Fairness matters', 'Równowaga się liczy',
       'Love isn''t a ledger', 'Miłość to nie rachunki'),
      ('Relationships', false,
       'Should you give a friend brutal honesty when they want comfort?',
       'Czy mówić przyjacielowi gorzką prawdę, gdy szuka pocieszenia?',
       'Real friends are honest', 'Przyjaciel mówi prawdę',
       'Read the moment', 'Wyczuj chwilę'),
      ('Relationships', true,
       'Are relationships that start online weaker than those born in person?',
       'Czy związki z internetu są słabsze niż te z prawdziwego życia?',
       'No real spark?', 'Brak prawdziwej iskry?',
       'Just another door', 'To po prostu nowa droga'),
      ('Relationships', false,
       'Is it wiser to settle for a good partner than chase the perfect one?',
       'Czy mądrzej wybrać dobrego partnera, niż szukać ideału?',
       'Perfect doesn''t exist', 'Ideał nie istnieje',
       'Settling is surrender?', 'Kompromis to kapitulacja?'),
      ('Family', true,
       'Should a hard family truth be revealed if it will hurt everyone?',
       'Czy ujawniać bolesną rodzinną prawdę, gdy zrani wszystkich?',
       'Truth always wins?', 'Prawda zawsze wygrywa?',
       'Let it rest?', 'Niech śpi spokojnie?'),
      ('Relationships', false,
       'Should couples post their relationship all over social media?',
       'Czy pary powinny obnosić swój związek w mediach społecznościowych?',
       'Proud to show it?', 'Duma z miłości?',
       'Real love stays private', 'Prawdziwa miłość lubi ciszę'),
      ('Family', true,
       'Can a parent ever be right to raise their voice at a child?',
       'Czy rodzic ma kiedykolwiek rację, podnosząc głos na dziecko?',
       'Sets a clear limit?', 'Wyznacza granicę?',
       'Calm teaches more', 'Spokój uczy więcej'),
      ('Work', false,
       'Would you take a job you find dull if it paid three times as much?',
       'Czy przyjąłbyś nudną pracę, gdyby płacono ci trzy razy więcej?',
       'Money buys freedom?', 'Pieniądz daje wolność?',
       'Years you won''t relive', 'Lata, które nie wrócą'),
      ('Culture', false,
       'Could a machine ever create art more beautiful than a human can?',
       'Czy maszyna kiedykolwiek stworzy sztukę piękniejszą niż człowiek?',
       'Beauty needs a soul?', 'Piękno potrzebuje duszy?',
       'Beauty''s in the eye', 'Piękno jest w oku patrzącego'),
      ('Health', true,
       'If you could learn the exact day you will die, would you want to know?',
       'Gdybyś mógł poznać dokładny dzień swojej śmierci, chciałbyś go znać?',
       'Live every day fully?', 'Żyć każdym dniem?',
       'A clock you can''t unsee', 'Zegar, którego nie odgonisz'),
      ('Health', false,
       'Would living forever be a blessing rather than a curse?',
       'Czy życie wieczne byłoby raczej błogosławieństwem niż przekleństwem?',
       'Endless time?', 'Czas bez końca?',
       'Bury everyone you love?', 'Pochować wszystkich, kogo kochasz?'),
      ('Technology', false,
       'Is giving up your privacy worth the convenience that technology offers?',
       'Czy oddanie prywatności jest warte wygody, jaką daje technologia?',
       'Nothing to hide?', 'Nie masz nic do ukrycia?',
       'Who''s watching?', 'Kto patrzy?'),
      ('Technology', true,
       'Has the smartphone made humanity''s life better overall?',
       'Czy smartfon ogólnie polepszył życie ludzkości?',
       'World in your pocket', 'Świat w kieszeni',
       'Stolen attention?', 'Skradziona uwaga?'),
      ('Health', false,
       'Is chasing success ever worth ruining your health for?',
       'Czy pogoń za sukcesem jest kiedykolwiek warta zniszczenia zdrowia?',
       'Legacy outlives you?', 'Dorobek cię przetrwa?',
       'No health, no winner', 'Bez zdrowia nie ma zwycięzcy'),
      ('Technology', false,
       'Should everyone have the right to erase their entire past from the internet?',
       'Czy każdy powinien mieć prawo wymazać całą swoją przeszłość z internetu?',
       'A right to be forgotten?', 'Prawo do bycia zapomnianym?',
       'Erasing the truth too?', 'Wymazujesz też prawdę?'),
      ('Work', false,
       'Should you quit a secure job to chase an uncertain dream?',
       'Czy warto rzucić pewną pracę, by gonić za niepewnym marzeniem?',
       'Regret what you didn''t try?', 'Żałować, że nie spróbowałeś?',
       'Bills don''t wait', 'Rachunki nie czekają'),
      ('Society', true,
       'Is fame worth living with no privacy at all?',
       'Czy sława jest warta życia bez żadnej prywatności?',
       'Every door opens', 'Wszystkie drzwi stoją otworem',
       'Never truly alone', 'Nigdy naprawdę sam'),
      ('Technology', false,
       'Can a relationship with an artificial mind be as real as one with a person?',
       'Czy więź ze sztucznym umysłem może być równie prawdziwa jak z człowiekiem?',
       'It always listens', 'Zawsze wysłucha',
       'Can code really care?', 'Czy kod potrafi kochać?'),
      ('Environment', true,
       'Is it wrong to travel by air for pleasure knowing the harm to the planet?',
       'Czy podróżowanie samolotem dla przyjemności jest złe, skoro szkodzi planecie?',
       'One life to see it all', 'Jedno życie, by zwiedzić świat',
       'Who pays the bill?', 'Kto zapłaci rachunek?'),
      ('Money', false,
       'Is it true that more money stops making us happier past a point?',
       'Czy to prawda, że powyżej pewnego progu więcej pieniędzy już nie uszczęśliwia?',
       'Enough is enough?', 'Wystarczy tyle?',
       'Say that when you''re broke', 'Powiedz to bez grosza'),
      ('Health', true,
       'If you could stay physically thirty forever, should you?',
       'Gdybyś mógł na zawsze zostać fizycznie trzydziestolatkiem, powinieneś?',
       'A body that never fails?', 'Ciało, które się nie zużywa?',
       'Frozen while the world moves on', 'Zastygły, gdy świat idzie dalej'),
      ('Culture', false,
       'Is an original artwork worth more than a flawless copy of it?',
       'Czy oryginał dzieła sztuki jest wart więcej niż jego idealna kopia?',
       'Same to the eye', 'Dla oka to samo',
       'The aura of the real?', 'Aura oryginału?'),
      ('Society', false,
       'Is a life worth living if no part of it is shared online?',
       'Czy warto żyć życiem, którego żadna część nie trafia do sieci?',
       'Real even if unseen', 'Prawdziwe, choć niewidziane',
       'Did it even happen?', 'Czy to się w ogóle wydarzyło?'),
      ('Work', true,
       'Would a world where machines do all the work be a good thing?',
       'Czy świat, w którym maszyny wykonują całą pracę, byłby czymś dobrym?',
       'Free at last?', 'Nareszcie wolni?',
       'Where''s our purpose?', 'A gdzie nasz sens?'),
      ('Work', false,
       'Should you always pick work you love over work that pays more?',
       'Czy zawsze warto wybrać pracę, którą kochasz, zamiast lepiej płatnej?',
       'Love what you do?', 'Kochać to, co robisz?',
       'Passion won''t pay rent', 'Pasją nie zapłacisz czynszu'),
      ('Technology', true,
       'If your mind could be copied into a machine, would that copy still be you?',
       'Gdyby twój umysł skopiowano do maszyny, czy ta kopia byłaby wciąż tobą?',
       'Your memories live on', 'Twoje wspomnienia żyją dalej',
       'Just a copy?', 'Tylko kopia?'),
      ('Environment', false,
       'Should we accept a less comfortable life to protect the natural world?',
       'Czy powinniśmy pogodzić się z mniej wygodnym życiem, by chronić przyrodę?',
       'Earth comes first?', 'Ziemia ważniejsza?',
       'Who gives up first?', 'Kto pierwszy zrezygnuje?'),
      ('Money', false,
       'Is it fair that those with more money can skip the wait everyone else faces?',
       'Czy to sprawiedliwe, że bogatsi mogą ominąć kolejkę, w której stoją inni?',
       'You earned it', 'Zasłużyłeś na to',
       'Time shouldn''t be for sale', 'Czas nie powinien być na sprzedaż'),
      ('Work', false,
       'Would a life of leisure with no work feel meaningful for long?',
       'Czy życie w samym wypoczynku, bez pracy, długo miałoby sens?',
       'Endless freedom?', 'Wolność bez końca?',
       'Boredom is its own prison', 'Nuda to też więzienie'),
      ('Health', true,
       'If you could delete your most painful memory, should you?',
       'Gdybyś mógł usunąć swoje najbardziej bolesne wspomnienie, powinieneś?',
       'Free of the pain?', 'Wolny od tego bólu?',
       'It made you who you are', 'To uczyniło cię tobą'),
      ('Culture', false,
       'Does the greatest art require the artist to suffer?',
       'Czy największa sztuka wymaga cierpienia twórcy?',
       'Pain digs deepest?', 'Ból sięga najgłębiej?',
       'Can''t joy create too?', 'A radość nie tworzy?'),
      ('Technology', false,
       'Would the internet be better if no one could be anonymous on it?',
       'Czy internet byłby lepszy, gdyby nikt nie mógł być w nim anonimowy?',
       'End the cruelty?', 'Koniec okrucieństwa?',
       'A mask can protect', 'Maska potrafi chronić'),
      ('Environment', true,
       'Should the living sacrifice comfort for generations not yet born?',
       'Czy żyjący powinni poświęcać wygodę dla pokoleń, które się jeszcze nie narodziły?',
       'We owe those after us?', 'Mamy dług wobec następnych?',
       'Why us and not them?', 'Czemu my, a nie oni?'),
      ('Culture', false,
       'Is something made slowly by hand worth more than a perfect mass-produced one?',
       'Czy rzecz robiona powoli ręką jest warta więcej niż idealna z masowej produkcji?',
       'The human hand', 'Ludzka ręka',
       'Flaws over perfection?', 'Niedoskonałość nad ideałem?'),
      ('Money', true,
       'Would you give up ten years of life to become extremely wealthy?',
       'Czy oddałbyś dziesięć lat życia, by stać się ogromnie bogatym?',
       'Live large while you can', 'Żyj pełnią, póki możesz',
       'Years never come back', 'Lata nie wracają'),
      ('Environment', false,
       'Should wild places be left untouched even if we could profit from using them?',
       'Czy dzikie tereny należy zostawić nietknięte, nawet gdy moglibyśmy na nich zarobić?',
       'Wild has its own worth', 'Dzikość ma własną wartość',
       'People need to live too', 'Ludzie też muszą żyć'),
      ('Family', true,
       'Would a child raised completely without screens have a better life?',
       'Czy dziecko wychowane całkowicie bez ekranów miałoby lepsze życie?',
       'Real world first', 'Najpierw prawdziwy świat',
       'Left behind by peers?', 'Zostanie w tyle za rówieśnikami?'),
      ('Society', false,
       'Is it better to be content with little than to always want more?',
       'Czy lepiej zadowolić się małym niż wiecznie pragnąć więcej?',
       'Peace of mind', 'Spokój ducha',
       'Giving up too soon?', 'Poddajesz się za wcześnie?'),
      ('Technology', true,
       'Would decisions be fairer if a machine made them instead of a person?',
       'Czy decyzje byłyby sprawiedliwsze, gdyby podejmowała je maszyna zamiast człowieka?',
       'No bias, no favorites', 'Bez uprzedzeń, bez wyjątków',
       'No room for mercy', 'Bez miejsca na litość'),
      ('Technology', false,
       'Would most people be happier after a month with no internet at all?',
       'Czy większość ludzi byłaby szczęśliwsza po miesiącu zupełnie bez internetu?',
       'The mind goes quiet', 'Głowa się wycisza',
       'Cut off from everyone?', 'Odcięty od wszystkich?'),
      ('Culture', true,
       'Is it better to be celebrated after death than ignored while alive?',
       'Czy lepiej być docenionym po śmierci niż niezauważonym za życia?',
       'Your name outlives you', 'Nazwisko cię przetrwa',
       'You''ll never know it', 'Nigdy się o tym nie dowiesz'),
      ('Work', true,
       'Is it wise to sacrifice your best years working hard to enjoy life later?',
       'Czy mądrze jest poświęcić najlepsze lata na ciężką pracę, by cieszyć się życiem później?',
       'Build a future?', 'Budujesz przyszłość?',
       'Later may never come', 'Później może nie nadejść')
    ) as s(category, is_premium, en, pl, a1en, a1pl, a2en, a2pl)
  loop
    -- skip if this EN text was already seeded
    if exists (
      select 1 from public.question_translations
      where locale = 'en' and question_text = r.en
    ) then
      continue;
    end if;

    insert into public.questions (category, is_premium)
    values (r.category, r.is_premium)
    returning id into qid;

    insert into public.question_translations (question_id, locale, question_text)
    values (qid, 'en', r.en),
           (qid, 'pl', r.pl);

    -- smaczek 1 (free teaser)
    insert into public.question_smaczki (question_id, position, is_active)
    values (qid, 1, true)
    returning id into s1;
    insert into public.question_smaczki_translations (smaczek_id, locale, text)
    values (s1, 'en', r.a1en),
           (s1, 'pl', r.a1pl);

    -- smaczek 2 (premium)
    insert into public.question_smaczki (question_id, position, is_active)
    values (qid, 2, true)
    returning id into s2;
    insert into public.question_smaczki_translations (smaczek_id, locale, text)
    values (s2, 'en', r.a2en),
           (s2, 'pl', r.a2pl);
  end loop;
end $$;

-- ----------------------------------------------------------------------------
-- 2) Schedule every still-unscheduled active question onto the next free dates.
--    Keeps Strategy A (unique question_id) intact. Wide horizon so the whole
--    new batch lands on a calendar slot.
-- ----------------------------------------------------------------------------
insert into public.daily_questions (publish_date, question_id)
select dates.d::date, q.id
from (
  select d, row_number() over (order by d) rn
  from generate_series(current_date, current_date + 1499, '1 day'::interval) d
  where d::date not in (select publish_date from public.daily_questions)
) dates
join (
  select id, row_number() over (order by random()) rn
  from public.questions
  where is_active
    and id not in (select question_id from public.daily_questions)
) q on q.rn = dates.rn
on conflict do nothing;

commit;
