-- ============================================================================
-- Seed batch 6: 126 globally-applicable debate questions (PL + EN) + smaczki
-- ----------------------------------------------------------------------------
-- Generated 2026-07-03. First file of the 268-question drop that brings the
-- catalog from 732 to exactly 1000 (batch 6: 126, batch 7: 125, batch 8: 17).
-- Same rules as batches 1-5: universal dilemmas, no country/law/currency
-- framings, ~50/50 splits. Deduplicated against ALL 750 historical EN texts
-- (732 live + 18 pruned), reconstructed from seed files on disk plus batches
-- 2-3 recovered from git commit a3a04a0 (they exist only in remote history).
--
-- Smaczki: position 1 free hook, position 2 premium counter-angle. NEW in this
-- batch: variable count -- most questions get 2, a few deep ones get a 3rd
-- angle (also premium: the RPC frees position 1 only), a few punchy ones get
-- just 1. Tuple carries nullable a2/a3 pairs; the loop skips nulls.
-- is_premium stays false everywhere (column inert since 2026-07-01).
-- Idempotent: keyed on EN text.
-- Topics in this file: Money (15), Work (15), Ethics (14), Culture (17),
-- Justice (10), Technology (12), Health (12), Society (12),
-- Relationships (10), Family (9).
-- ============================================================================

begin;

do $$
declare
  r   record;
  qid uuid;
  s1  uuid;
  s2  uuid;
  s3  uuid;
begin
  for r in
    select * from (values
      ('Money', false,
       'Is checking a cheaper online price while standing in a small shop unfair to the owner?',
       'Czy sprawdzanie tańszej ceny w internecie, stojąc w małym sklepie, jest nie fair wobec właściciela?',
       'The shop pays rent, you pay nothing', 'Sklep płaci czynsz, ty nic',
       'Your budget, your rules', 'Twój budżet, twoje zasady',
       null, null),
      ('Money', false,
       'Is returning clothes you wore once to an event a form of theft?',
       'Czy zwracanie ubrań założonych raz na imprezę to forma kradzieży?',
       'The tag was still on', 'Metka przecież została',
       'Someone buys it "new" after you', 'Ktoś kupi je „nowe" po tobie',
       null, null),
      ('Money', false,
       'Should parents hand over the inheritance while they are still alive?',
       'Czy rodzice powinni przekazać spadek, póki jeszcze żyją?',
       'Help when it''s needed most', 'Pomoc wtedy, gdy najbardziej potrzebna',
       'Old age is expensive too', 'Starość też kosztuje',
       null, null),
      ('Money', false,
       'Can a high salary quietly trap you in a life you don''t want?',
       'Czy wysoka pensja może po cichu uwięzić cię w życiu, którego nie chcesz?',
       'A golden cage is still a cage', 'Złota klatka to wciąż klatka',
       'Try being trapped while poor', 'Spróbuj być uwięziony na biednie',
       null, null),
      ('Money', false,
       'Is calling a purchase an "investment in yourself" usually self-deception?',
       'Czy nazywanie zakupu „inwestycją w siebie" to zwykle oszukiwanie się?',
       'A treat in a fancy costume', 'Zachcianka w eleganckim przebraniu',
       'Some purchases really do pay off', 'Niektóre zakupy naprawdę procentują',
       null, null),
      ('Money', false,
       'Is giving away things you no longer want really generosity?',
       'Czy oddawanie rzeczy, których już nie chcesz, to naprawdę hojność?',
       'It costs you nothing', 'Nic cię to nie kosztuje',
       'Better used than binned', 'Lepiej, żeby służyły, niż leżały',
       null, null),
      ('Money', false,
       'Can you truly be free while in debt?',
       'Czy można być naprawdę wolnym, mając długi?',
       'Your future is already sold', 'Twoja przyszłość jest już sprzedana',
       'That debt built your home', 'Ten dług zbudował twój dom',
       null, null),
      ('Money', false,
       'Does treating your home as an investment ruin what a home is?',
       'Czy traktowanie domu jak inwestycji psuje to, czym jest dom?',
       'You live inside a price chart', 'Mieszkasz w wykresie cen',
       'It''s most people''s whole wealth', 'To cały majątek większości ludzi',
       null, null),
      ('Money', false,
       'Is a bargain you didn''t need still wasted money?',
       'Czy okazja, której nie potrzebowałeś, to wciąż wyrzucone pieniądze?',
       'You "saved" by spending?', '„Zaoszczędziłeś", wydając?',
       'A stock bought cheap is a stock', 'Zapas kupiony tanio to zapas',
       null, null),
      ('Money', false,
       'Is paying someone for chores you could do yourself the smartest money you spend?',
       'Czy płacenie komuś za obowiązki, które możesz zrobić sam, to najlepiej wydane pieniądze?',
       'You''re buying back your hours', 'Odkupujesz własne godziny',
       'Laziness with a receipt', 'Lenistwo z paragonem',
       null, null),
      ('Money', false,
       'Would you put your name on a loved one''s loan?',
       'Czy podpisałbyś się pod kredytem bliskiej osoby?',
       'Just a signature — until it isn''t', 'Tylko podpis — dopóki nie przestanie',
       'Family vouches for family', 'Rodzina ręczy za rodzinę',
       null, null),
      ('Money', false,
       'Is being stingy with yourself while generous to others a virtue?',
       'Czy skąpienie sobie przy hojności dla innych to cnota?',
       'Saints don''t buy gadgets', 'Święci nie kupują gadżetów',
       'You count too', 'Ty też się liczysz',
       null, null),
      ('Money', false,
       'Does getting rich mostly reveal who someone already was?',
       'Czy bogactwo głównie odsłania, kim ktoś był naprawdę?',
       'A wallet is a mirror', 'Portfel to lustro',
       'Comfort corrupts slowly', 'Wygoda psuje powoli',
       null, null),
      ('Money', false,
       'Is "you get what you pay for" mostly a myth?',
       'Czy „dostajesz to, za co płacisz" to w większości mit?',
       'Half the price is marketing', 'Połowa ceny to marketing',
       'Cheap bites back later', 'Tanie gryzie z opóźnieniem',
       null, null),
      ('Money', false,
       'Is spending a fortune on a hobby that earns nothing perfectly rational?',
       'Czy wydawanie fortuny na hobby, które nic nie zarabia, jest w pełni racjonalne?',
       'Joy is the return on investment', 'Radość to twój zwrot z inwestycji',
       'A money pit in nice wrapping', 'Studnia bez dna w ładnym opakowaniu',
       null, null),
      ('Work', false,
       'Is a messy desk a sign of a creative mind?',
       'Czy bałagan na biurku to znak kreatywnego umysłu?',
       'Genius has no time to tidy', 'Geniusz nie ma czasu sprzątać',
       'Chaos outside, chaos inside', 'Chaos na zewnątrz, chaos w środku',
       null, null),
      ('Work', false,
       'Is being irreplaceable at work a trap rather than a triumph?',
       'Czy bycie niezastąpionym w pracy to pułapka, a nie triumf?',
       'You can never leave', 'Nigdy nie możesz odejść',
       'Job security money can''t buy', 'Pewność, której nie da się kupić',
       null, null),
      ('Work', false,
       'Should rejected job candidates be told the real reason?',
       'Czy odrzuceni kandydaci powinni poznać prawdziwy powód?',
       'How else can they grow?', 'Jak inaczej mają się poprawić?',
       'Truth invites trouble', 'Prawda ściąga kłopoty',
       null, null),
      ('Work', false,
       'Is hiring away your friend''s best employee a betrayal?',
       'Czy podkupienie najlepszego pracownika przyjaciela to zdrada?',
       'Business has no friends', 'Biznes nie ma przyjaciół',
       'The employee chose freely', 'Pracownik wybrał sam',
       null, null),
      ('Work', false,
       'Is punctuality overrated compared to what you actually deliver?',
       'Czy punktualność jest przeceniana wobec tego, co faktycznie dostarczasz?',
       'Results don''t wear a watch', 'Wyniki nie noszą zegarka',
       'Lateness says "you don''t matter"', 'Spóźnienie mówi: „nie liczysz się"',
       null, null),
      ('Work', false,
       'Is being the expert better than being the boss?',
       'Czy lepiej być ekspertem niż szefem?',
       'Mastery outlasts job titles', 'Mistrzostwo przeżywa stanowiska',
       'The boss draws the map', 'To szef rysuje mapę',
       null, null),
      ('Work', false,
       'Should you ever return to an employer you once quit?',
       'Czy warto wracać do pracodawcy, od którego się odeszło?',
       'You left for a reason', 'Odszedłeś nie bez powodu',
       'A new chapter on familiar ground', 'Nowy rozdział na znanym gruncie',
       null, null),
      ('Work', false,
       'Should companies hire for attitude and train the skills later?',
       'Czy firmy powinny zatrudniać za nastawienie, a umiejętności szkolić później?',
       'You can''t teach hunger', 'Głodu sukcesu nie nauczysz',
       'Enthusiasm won''t fly the plane', 'Entuzjazm nie poprowadzi samolotu',
       null, null),
      ('Work', false,
       'Is taking a job you''re overqualified for a step backward?',
       'Czy przyjęcie pracy poniżej kwalifikacji to krok wstecz?',
       'Momentum matters', 'Rozpęd ma znaczenie',
       'A paycheck beats pride', 'Wypłata bije dumę',
       null, null),
      ('Work', false,
       'Should you walk out of meetings that waste your time?',
       'Czy powinno się wychodzić ze spotkań, które marnują twój czas?',
       'Your hours, your right', 'Twoje godziny, twoje prawo',
       'Respect isn''t optional', 'Szacunek nie jest opcjonalny',
       null, null),
      ('Work', false,
       'Is dreading Monday a sign you need to change your life?',
       'Czy lęk przed poniedziałkiem to znak, że musisz zmienić życie?',
       'Your body is casting a vote', 'Twoje ciało właśnie głosuje',
       'Everyone dreads Mondays a bit', 'Każdy trochę nie lubi poniedziałków',
       null, null),
      ('Work', false,
       'Should bonuses be split equally across the whole team?',
       'Czy premie powinny być dzielone równo na cały zespół?',
       'One boat, one tide', 'Jedna łódź, jeden przypływ',
       'Stars deserve star pay', 'Gwiazdy zasługują na gwiezdne stawki',
       null, null),
      ('Work', false,
       'Is a career plan pointless in a world that changes this fast?',
       'Czy plan kariery ma sens w świecie, który zmienia się tak szybko?',
       'Plans expire faster than milk', 'Plany psują się szybciej niż mleko',
       'No map, no journey', 'Bez mapy nie ma podróży',
       null, null),
      ('Work', false,
       'Is retiring overnight worse than slowly fading out of work?',
       'Czy emerytura z dnia na dzień jest gorsza niż stopniowe zwalnianie tempa?',
       'A sudden cliff breaks people', 'Nagły brzeg łamie ludzi',
       'A clean break, a clean start', 'Czyste cięcie, czysty start',
       null, null),
      ('Work', false,
       'Is the colleague who always asks "why?" the most valuable one in the room?',
       'Czy współpracownik, który zawsze pyta „po co?", jest najcenniejszy w zespole?',
       'Questions prevent catastrophes', 'Pytania zapobiegają katastrofom',
       'Someone has to actually row', 'Ktoś musi w końcu wiosłować',
       null, null),
      ('Ethics', false,
       'Is sharing streaming passwords with friends a form of stealing?',
       'Czy dzielenie się hasłami do streamingu z przyjaciółmi to forma kradzieży?',
       'The company priced it in', 'Firma to sobie wkalkulowała',
       'Someone''s work pays for it', 'Czyjaś praca to finansuje',
       null, null),
      ('Ethics', false,
       'Is bingeing true-crime stories treating real tragedy as entertainment?',
       'Czy pochłanianie historii true crime to robienie sobie rozrywki z prawdziwych tragedii?',
       'Victims become content', 'Ofiary stają się kontentem',
       'Understanding evil protects us', 'Rozumienie zła nas chroni',
       null, null),
      ('Ethics', false,
       'Is taking the last piece of food without offering it around a small crime?',
       'Czy branie ostatniego kawałka bez zapytania innych to małe przestępstwo?',
       'The sacred last-slice pause', 'Święta pauza nad ostatnim kawałkiem',
       'Food belongs to the fastest', 'Jedzenie jest dla najszybszych',
       null, null),
      ('Ethics', false,
       'Does dirty money become clean when it''s given to charity?',
       'Czy brudne pieniądze stają się czyste, gdy trafiają na cele dobroczynne?',
       'The hospital doesn''t ask where it''s from', 'Szpital nie pyta o źródło',
       'A receipt is not absolution', 'Paragon to nie rozgrzeszenie',
       'Would you refuse it for the needy?', 'Odmówiłbyś ich potrzebującym?'),
      ('Ethics', false,
       'Is pulling strings to get your child a job unfair play?',
       'Czy załatwianie dziecku pracy po znajomości to nieuczciwa gra?',
       'Someone just lost their fair shot', 'Ktoś właśnie stracił uczciwą szansę',
       'Any parent would do it', 'Każdy rodzic by to zrobił',
       null, null),
      ('Ethics', false,
       'Must you finish a meal your host proudly cooked, even if you hate it?',
       'Czy musisz dokończyć danie, które gospodarz z dumą ugotował, nawet gdy ci nie smakuje?',
       'You''re eating for their heart', 'Jesz dla ich serca',
       'Politeness shouldn''t hurt', 'Grzeczność nie powinna boleć',
       null, null),
      ('Ethics', false,
       'Should you pretend to love a gift you hate?',
       'Czy udawać zachwyt prezentem, który ci się nie podoba?',
       'The lie protects the giver', 'To kłamstwo chroni darczyńcę',
       'They''ll keep buying wrong', 'Będą dalej kupować nietrafione',
       null, null),
      ('Ethics', false,
       'Is a "no gifts" pact between adults the honest way to go?',
       'Czy umowa „bez prezentów" między dorosłymi to najuczciwsze wyjście?',
       'Ends the swap of unwanted stuff', 'Koniec wymiany niechcianych rzeczy',
       'Gifts are how some people love', 'Prezenty to czyjś język miłości',
       null, null),
      ('Ethics', false,
       'Is it wrong to laugh at a joke you find offensive?',
       'Czy śmiech z żartu, który uważasz za niestosowny, jest zły?',
       'Laughter is a vote of support', 'Śmiech to głos poparcia',
       'A reflex is not a moral stance', 'Odruch to nie poglądy',
       null, null),
      ('Ethics', false,
       'Is "I''m brutally honest" usually just an excuse to be brutal?',
       'Czy „jestem brutalnie szczery" to zwykle wymówka dla brutalności?',
       'The brutality is the point', 'Chodzi o brutalność, nie szczerość',
       'Soft lies help no one', 'Miękkie kłamstwa nikomu nie służą',
       null, null),
      ('Ethics', false,
       'Should you always offer your seat to someone older, even if it might offend them?',
       'Czy zawsze ustępować miejsca starszym, nawet jeśli może ich to urazić?',
       'Respect never expires', 'Szacunek się nie starzeje',
       '"Old" is your judgment of them', '„Starszy" to twoja ocena, nie ich',
       null, null),
      ('Ethics', false,
       'Is a promise made under pressure still binding?',
       'Czy obietnica złożona pod presją nadal zobowiązuje?',
       'Your word is your word', 'Słowo to słowo',
       'Coercion cancels consent', 'Przymus unieważnia zgodę',
       null, null),
      ('Ethics', false,
       'Would you rather be wronged than wrong someone?',
       'Czy wolałbyś zostać skrzywdzonym, niż skrzywdzić?',
       'Clean hands, broken nose', 'Czyste ręce, rozbity nos',
       'Being the victim still hurts', 'Bycie ofiarą też boli',
       null, null),
      ('Ethics', false,
       'Is sparing someone bad news until after their big day the right call?',
       'Czy wstrzymanie złych wieści do końca czyjegoś wielkiego dnia to dobra decyzja?',
       'Let them have their day', 'Pozwól im przeżyć ich dzień',
       'They''ll ask why you waited', 'Zapytają, czemu zwlekałeś',
       null, null)
      ,('Culture', false,
       'Does dubbing ruin a film?',
       'Czy dubbing psuje film?',
       'The voice is half the acting', 'Głos to połowa aktorstwa',
       'Reading isn''t watching', 'Czytanie napisów to nie oglądanie',
       null, null),
      ('Culture', false,
       'Is watching films and lectures at double speed cheating yourself?',
       'Czy oglądanie filmów i wykładów na podwójnej prędkości to oszukiwanie samego siebie?',
       'The tempo is part of the work', 'Tempo dzieła to nie przypadek',
       'Twice the speed, twice the knowledge', 'Dwa razy szybciej, dwa razy więcej',
       null, null),
      ('Culture', false,
       'Is the book always better than the film adaptation?',
       'Czy książka jest zawsze lepsza od ekranizacji?',
       'Imagination beats any budget', 'Wyobraźnia bije każdy budżet',
       'Some films outgrew their books', 'Niektóre filmy przerosły pierwowzór',
       null, null),
      ('Culture', false,
       'Is reading a summary of a book basically reading the book?',
       'Czy przeczytanie streszczenia to w zasadzie przeczytanie książki?',
       'You know the ideas now, don''t you?', 'Przecież znasz już najważniejsze tezy',
       'A postcard is not a journey', 'Pocztówka to nie podróż',
       null, null),
      ('Culture', false,
       'Is rereading an old favorite better than risking a new book?',
       'Czy powrót do ukochanej książki jest lepszy niż ryzyko z nową?',
       'Guaranteed joy exists', 'Gwarantowana radość istnieje',
       'Comfort never surprises you', 'Wygoda nigdy cię nie zaskoczy',
       null, null),
      ('Culture', false,
       'Should old books be edited to remove words that offend today?',
       'Czy stare książki powinno się redagować, usuwając słowa, które dziś obrażają?',
       'Books are for the living', 'Książki są dla żywych',
       'Editing the past erases it', 'Poprawianie przeszłości to jej wymazywanie',
       'Who gets to hold the red pen?', 'Kto trzyma czerwony długopis?'),
      ('Culture', false,
       'Should beloved classics be left alone rather than remade?',
       'Czy ukochane klasyki powinno się zostawić w spokoju zamiast robić remaki?',
       'Some things are finished', 'Pewne rzeczy są po prostu skończone',
       'Every generation deserves its own version', 'Każde pokolenie zasługuje na swoją wersję',
       null, null),
      ('Culture', false,
       'Can you own too many books?',
       'Czy można mieć za dużo książek?',
       'Unread books are a guilt list', 'Nieprzeczytane książki to lista zaległości',
       'A wall of books is a wall of friends', 'Ściana książek to ściana przyjaciół',
       null, null),
      ('Culture', false,
       'Is a live concert worth ten times the price of listening at home?',
       'Czy koncert na żywo jest wart dziesięć razy więcej niż słuchanie w domu?',
       'You''re buying the moment, not the sound', 'Kupujesz chwilę, nie dźwięk',
       'Better sound, zero queues, your sofa', 'Lepszy dźwięk, zero kolejek, własna kanapa',
       null, null),
      ('Culture', false,
       'Is clapping when the plane lands perfectly fine?',
       'Czy klaskanie po lądowaniu samolotu jest zupełnie w porządku?',
       'Joy needs no permission', 'Radość nie pyta o pozwolenie',
       'The pilot can''t hear you anyway', 'Pilot i tak cię nie słyszy',
       null, null),
      ('Culture', false,
       'Should chess count as a sport?',
       'Czy szachy powinny być uznawane za sport?',
       'Sweat is not the measure', 'Pot to nie miara sportu',
       'Sport means body, not board', 'Sport to ciało, nie plansza',
       null, null),
      ('Culture', false,
       'Is celebrating wildly in front of the losing team disrespectful?',
       'Czy hałaśliwe świętowanie na oczach przegranych to brak szacunku?',
       'You earned that joy', 'Zasłużyłeś na tę radość',
       'Class shows in victory', 'Klasę widać po zwycięstwie',
       null, null),
      ('Culture', false,
       'Is meeting your hero always a mistake?',
       'Czy spotkanie swojego idola to zawsze błąd?',
       'Idols shrink up close', 'Idole maleją z bliska',
       'Finding out they''re human is the gift', 'Odkrycie, że to człowiek, jest darem',
       null, null),
      ('Culture', false,
       'Is correcting someone''s grammar mid-story rude rather than helpful?',
       'Czy poprawianie czyichś błędów językowych w pół opowieści jest niegrzeczne, a nie pomocne?',
       'You''re hearing a story, not grading it', 'Słuchasz opowieści, nie oceniasz dyktanda',
       'Who else will ever tell them?', 'Kto inny im to powie?',
       null, null),
      ('Culture', false,
       'Can fiction teach more truth than facts?',
       'Czy fikcja potrafi nauczyć więcej prawdy niż fakty?',
       'Stories smuggle wisdom in', 'Opowieści przemycają mądrość',
       'Beautiful lies are still lies', 'Piękne kłamstwa to wciąż kłamstwa',
       null, null),
      ('Culture', false,
       'Do guilty pleasures really need the guilt?',
       'Czy „wstydliwe przyjemności" naprawdę potrzebują wstydu?',
       'Own what you love', 'Przyznaj się do tego, co kochasz',
       'Shame is what guards taste', 'To wstyd strzeże gustu',
       null, null),
      ('Culture', false,
       'Is knowing the classics part of being a complete adult?',
       'Czy znajomość klasyki to część bycia pełnym dorosłym?',
       'Culture is a shared language', 'Kultura to wspólny język',
       'Life''s too short for forced homework', 'Życie jest za krótkie na lektury z przymusu',
       null, null),
      ('Justice', false,
       'Should prison be unpleasant beyond just losing freedom?',
       'Czy więzienie powinno być dolegliwe ponad samą utratę wolności?',
       'Losing freedom IS the punishment', 'Utrata wolności to już jest kara',
       'Comfort mocks the victims', 'Wygoda kpi z ofiar',
       null, null),
      ('Justice', false,
       'Should evidence of guilt count even if it was obtained wrongly?',
       'Czy dowód winy powinien się liczyć, nawet jeśli zdobyto go nieuczciwie?',
       'Truth is truth', 'Prawda to prawda',
       'Poisoned tree, poisoned fruit', 'Zatrute drzewo daje zatrute owoce',
       null, null),
      ('Justice', false,
       'Should a whole team be punished for one member''s cheating?',
       'Czy cała drużyna powinna odpowiadać za oszustwo jednego zawodnika?',
       'They wore the same shirt', 'Nosili tę samą koszulkę',
       'Guilt is not contagious', 'Wina nie jest zaraźliwa',
       null, null),
      ('Justice', false,
       'Should being drunk make a crime worse rather than more excusable?',
       'Czy stan upojenia powinien zaostrzać winę, a nie ją łagodzić?',
       'The first glass was a choice', 'Pierwszy kieliszek był wyborem',
       'No awareness, no intent', 'Bez świadomości nie ma zamiaru',
       null, null),
      ('Justice', false,
       'Does betraying someone''s trust make the harm worse than harming a stranger?',
       'Czy nadużycie zaufania czyni krzywdę gorszą niż ta sama krzywda wobec obcego?',
       'They opened the door for you themselves', 'Sami otworzyli ci drzwi',
       'Harm is harm', 'Krzywda to krzywda',
       null, null),
      ('Justice', false,
       'Should an animal that seriously hurt a person always be put down?',
       'Czy zwierzę, które poważnie zraniło człowieka, powinno być zawsze uśpione?',
       'It will do it again', 'Zrobi to znowu',
       'It acted from nature, not malice', 'Działało z natury, nie ze złości',
       null, null),
      ('Justice', false,
       'Should sincere remorse soften a punishment?',
       'Czy szczera skrucha powinna łagodzić karę?',
       'Remorse is the whole point of punishing', 'Skrucha to przecież cel kary',
       'Anyone can act sorry', 'Każdy potrafi zagrać żal',
       null, null),
      ('Justice', false,
       'Should someone be punished for a crime they can no longer remember committing?',
       'Czy karać za zbrodnię, której sprawca już nie pamięta?',
       'The victim remembers', 'Ofiara pamięta',
       'You''d punish a stranger to himself', 'Ukarzesz kogoś, kto jest już kimś innym',
       'Does the old "you" still exist?', 'Czy dawne „ja" w ogóle jeszcze istnieje?'),
      ('Justice', false,
       'Is a rule applied without exceptions fairer than one applied with judgment?',
       'Czy zasada stosowana bez wyjątków jest sprawiedliwsza niż ocenianie każdego przypadku osobno?',
       'Exceptions breed favorites', 'Wyjątki rodzą pupili',
       'Life doesn''t fit templates', 'Życie nie mieści się w szablonach',
       null, null),
      ('Justice', false,
       'Should whoever finds a treasure get to keep it?',
       'Czy znalazca skarbu powinien móc go zatrzymać?',
       'The finder''s luck is still earned', 'Szczęście znalazcy to też zasługa',
       'History belongs to everyone', 'Historia należy do wszystkich',
       null, null),
      ('Technology', false,
       'Should you have the right to repair anything you own?',
       'Czy powinieneś mieć prawo naprawić wszystko, co posiadasz?',
       'Yours should mean yours', 'Twoje powinno znaczyć twoje',
       'Amateur repairs, real dangers', 'Amatorskie naprawy, prawdziwe ryzyko',
       null, null),
      ('Technology', false,
       'Should making products designed to break be treated as fraud?',
       'Czy projektowanie produktów tak, by się psuły, powinno być traktowane jak oszustwo?',
       'A lightbulb can burn for a century', 'Żarówka potrafi świecić sto lat',
       'Cheap things live short lives by design', 'Tanie rzeczy żyją krótko z definicji',
       null, null),
      ('Technology', false,
       'Is the death of the local shop a fair price for convenience?',
       'Czy śmierć osiedlowego sklepiku to uczciwa cena za wygodę?',
       'You voted with every click', 'Głosowałeś każdym kliknięciem',
       'Convenience gives you back your hours', 'Wygoda zwraca ci godziny życia',
       null, null),
      ('Technology', false,
       'Does fixing your family''s computer once make you their tech support forever?',
       'Czy naprawiając rodzinie komputer raz, zapisujesz się do pomocy technicznej na zawsze?',
       'One fix, a lifelong contract', 'Jedna naprawa, dożywotni kontrakt',
       'Love is also tech support', 'Miłość to też wsparcie techniczne',
       null, null),
      ('Technology', false,
       'Would you press a button that skips life''s boring parts?',
       'Czy nacisnąłbyś przycisk pomijający nudne fragmenty życia?',
       'Boredom is where ideas grow', 'Nuda to szklarnia pomysłów',
       'Life''s too short for queues', 'Życie jest za krótkie na kolejki',
       'Who decides what counts as boring?', 'Kto decyduje, co jest nudne?'),
      ('Technology', false,
       'Should cameras be mandatory in work video calls?',
       'Czy na służbowych wideorozmowach kamera powinna być obowiązkowa?',
       'Faces build teams', 'Twarze budują zespół',
       'My home is not a film set', 'Mój dom to nie plan zdjęciowy',
       null, null),
      ('Technology', false,
       'Are headphones in public a fair "do not disturb" sign?',
       'Czy słuchawki w miejscu publicznym to uczciwy znak „nie przeszkadzać"?',
       'The universal signal of our times', 'Uniwersalny sygnał naszych czasów',
       'Walls that we wear', 'Ściany, które nosimy na sobie',
       null, null),
      ('Technology', false,
       'Would you let anyone read your search history after you die?',
       'Czy pozwoliłbyś komuś czytać swoją historię wyszukiwania po śmierci?',
       'The most honest diary you own', 'Najszczerszy pamiętnik, jaki masz',
       'Some doors should stay closed forever', 'Niektóre drzwi powinny zostać zamknięte',
       null, null),
      ('Technology', false,
       'Is a paper book better than an e-book?',
       'Czy papierowa książka jest lepsza od e-booka?',
       'Smell, weight, memory', 'Zapach, ciężar, pamięć',
       'A thousand books in your pocket', 'Tysiąc książek w twojej kieszeni',
       null, null),
      ('Technology', false,
       'Is upgrading your phone every year indefensible?',
       'Czy wymiana telefonu co rok jest nie do obrony?',
       'A tool has become jewelry', 'Narzędzie stało się biżuterią',
       'Your money, your toys', 'Twoje pieniądze, twoje zabawki',
       null, null),
      ('Technology', false,
       'Is losing your phone worse than losing your wallet these days?',
       'Czy zgubienie telefonu jest dziś gorsze niż zgubienie portfela?',
       'Your whole life lives in there', 'Całe twoje życie tam mieszka',
       'It''s just a screen; money is money', 'To tylko ekran, pieniądze to pieniądze',
       null, null),
      ('Technology', false,
       'Would you wear glasses that showed you every stranger''s name?',
       'Czy nosiłbyś okulary pokazujące imię każdego mijanego przechodnia?',
       'Never forget a face again', 'Koniec z zapominaniem twarzy',
       'Strangers have a right to stay strangers', 'Obcy mają prawo pozostać obcy',
       null, null)
      ,('Health', false,
       'Does "everything in moderation" actually work as life advice?',
       'Czy „wszystko z umiarem" naprawdę działa jako recepta na życie?',
       'Moderation in moderation too?', 'Umiar także w umiarze?',
       'Some things deserve a hard zero', 'Niektóre rzeczy zasługują na twarde zero',
       null, null),
      ('Health', false,
       'Can buying something new be genuine self-care?',
       'Czy zakupy potrafią być prawdziwą troską o siebie?',
       'A small joy is still a joy', 'Mała radość to wciąż radość',
       'You can''t fill a void with receipts', 'Pustki nie zapełnisz paragonami',
       null, null),
      ('Health', false,
       'Should a self-inflicted hangover count as a real sick day?',
       'Czy kac z własnej winy zasługuje na prawdziwe zwolnienie?',
       'Sick is sick', 'Chory to chory',
       'Your choice, your desk', 'Twój wybór, twoje biurko',
       null, null),
      ('Health', false,
       'Does pain teach more than pleasure ever can?',
       'Czy ból uczy więcej, niż przyjemność kiedykolwiek nauczy?',
       'Growth lives outside comfort', 'Rozwój mieszka poza strefą wygody',
       'Joy teaches too — just gently', 'Radość też uczy, tylko łagodniej',
       null, null),
      ('Health', false,
       'Is talking to yourself out loud a sign of a healthy mind?',
       'Czy mówienie do siebie na głos to znak zdrowego umysłu?',
       'The best conversations are free', 'Najlepsze rozmowy są za darmo',
       'Thoughts should stay indoors', 'Myśli powinny zostawać w środku',
       null, null),
      ('Health', false,
       'Should you trust your body over your training plan?',
       'Czy słuchać ciała bardziej niż planu treningowego?',
       'The plan can''t feel your knees', 'Plan nie czuje twoich kolan',
       'The body is a lazy liar', 'Ciało to leniwy kłamca',
       null, null),
      ('Health', false,
       'Is loving very spicy food just masochism in disguise?',
       'Czy miłość do bardzo ostrego jedzenia to masochizm w przebraniu?',
       'The pain is the flavor', 'Ból jest przyprawą',
       'A trained tongue tastes more', 'Wytrenowany język czuje więcej',
       null, null),
      ('Health', false,
       'Is staying fit a duty you owe the people who love you?',
       'Czy dbanie o formę to obowiązek wobec tych, którzy cię kochają?',
       'They''re the ones who''d carry you', 'To oni będą cię nosić',
       'Your body, your ledger', 'Twoje ciało, twój rachunek',
       null, null),
      ('Health', false,
       'Would you give up your sense of taste for perfect health?',
       'Czy oddałbyś zmysł smaku za doskonałe zdrowie?',
       'Health is the real feast', 'Zdrowie to prawdziwa uczta',
       'A life without flavor is a forever diet', 'Życie bez smaku to wieczna dieta',
       null, null),
      ('Health', false,
       'Is worrying about your health the unhealthiest habit of all?',
       'Czy zamartwianie się zdrowiem to najbardziej niezdrowy nawyk ze wszystkich?',
       'Stress kills faster than burgers', 'Stres zabija skuteczniej niż burgery',
       'The watchful live longer', 'Czujni żyją dłużej',
       null, null),
      ('Health', false,
       'Do adults need a bedtime alarm more than a wake-up one?',
       'Czy dorosłym bardziej niż budzik potrzebny jest alarm „idź spać"?',
       'Midnight-you makes bad decisions', 'Nocna wersja ciebie podejmuje złe decyzje',
       'Evenings are the only free hours', 'Wieczór to jedyne wolne godziny',
       null, null),
      ('Health', false,
       'Is doing nothing a skill that has to be practiced?',
       'Czy umiejętność nicnierobienia trzeba ćwiczyć jak mięsień?',
       'Stillness is a muscle', 'Bezruch to mięsień',
       'Doing nothing is just... nothing', 'Nicnierobienie to po prostu nic',
       null, null),
      ('Society', false,
       'Should everyone work a customer-service job once in their life?',
       'Czy każdy powinien raz w życiu popracować w obsłudze klienta?',
       'Empathy is learned at the till', 'Empatii uczysz się przy kasie',
       'Forced lessons teach resentment', 'Przymusowe lekcje uczą urazy',
       null, null),
      ('Society', false,
       'Is fake politeness better than honest rudeness?',
       'Czy udawana uprzejmość jest lepsza niż szczera nieuprzejmość?',
       'Society runs on small fictions', 'Społeczeństwo jedzie na drobnych fikcjach',
       'Fake kindness is still fake', 'Udawana życzliwość to wciąż fałsz',
       null, null),
      ('Society', false,
       'Is the name your parents gave you yours to discard?',
       'Czy imię od rodziców jest twoje na tyle, by móc je porzucić?',
       'You wear it, you choose it', 'Ty je nosisz, ty wybierasz',
       'It was their first gift to you', 'To ich pierwszy prezent dla ciebie',
       null, null),
      ('Society', false,
       'Do we still need ceremonies to mark life''s big moments?',
       'Czy wciąż potrzebujemy uroczystości, by zaznaczać wielkie momenty życia?',
       'Rituals make time visible', 'Rytuały czynią czas widzialnym',
       'The moment matters, not the party', 'Liczy się moment, nie przyjęcie',
       null, null),
      ('Society', false,
       'Should museums be free for everyone?',
       'Czy muzea powinny być darmowe dla wszystkich?',
       'Heritage has no price tag', 'Dziedzictwo nie ma cennika',
       'Free means someone else pays', 'Darmowe znaczy, że płaci ktoś inny',
       null, null),
      ('Society', false,
       'Should a city tear down ugly buildings that work perfectly well?',
       'Czy miasto powinno wyburzać brzydkie budynki, które dobrze służą?',
       'Ugliness is a daily tax', 'Brzydota to codzienny podatek',
       'Today''s eyesore, tomorrow''s icon', 'Dzisiejszy koszmarek, jutrzejsza ikona',
       null, null),
      ('Society', false,
       'Do all opinions deserve a hearing, even the ignorant ones?',
       'Czy każda opinia zasługuje na wysłuchanie, nawet ta ignorancka?',
       'Sunlight works better than a gag', 'Światło działa lepiej niż knebel',
       'Nonsense grows when amplified', 'Bzdura rośnie, gdy ją nagłaśniać',
       null, null),
      ('Society', false,
       'Are the best neighbors the ones you barely know?',
       'Czy najlepsi sąsiedzi to ci, których ledwo znasz?',
       'Distance keeps the peace', 'Dystans strzeże spokoju',
       'One day you''ll need them', 'Kiedyś będziesz ich potrzebować',
       null, null),
      ('Society', false,
       'Is reporting a neighbor anonymously an act of cowardice?',
       'Czy anonimowe skarżenie na sąsiada to tchórzostwo?',
       'Say it to their face', 'Powiedz im to w twarz',
       'Anonymity prevents wars', 'Anonimowość zapobiega wojnom',
       null, null),
      ('Society', false,
       'Is starting a conversation with a stranger on a long journey an intrusion?',
       'Czy zagajanie rozmowy z nieznajomym w długiej podróży to naruszanie jego spokoju?',
       'Their silence wasn''t an invitation', 'Ich milczenie nie było zaproszeniem',
       'Strangers are friends in waiting', 'Nieznajomi to przyszli znajomi',
       null, null),
      ('Society', false,
       'Should you step in when a parent screams at their child in public?',
       'Czy reagować, gdy rodzic wrzeszczy na dziecko w miejscu publicznym?',
       'The child can''t defend itself', 'Dziecko samo się nie obroni',
       'You''re seeing one minute of their day', 'Widzisz jedną minutę ich dnia',
       null, null),
      ('Society', false,
       'Would people be kinder if everyone''s mood were visible?',
       'Czy ludzie byliby dla siebie lepsi, gdyby każdy nosił swój nastrój na widoku?',
       'You''d forgive the frowning', 'Wybaczyłbyś naburmuszonym',
       'The heart deserves privacy too', 'Serce też ma prawo do prywatności',
       null, null),
      ('Relationships', false,
       'Should couples manage their relationship like a project?',
       'Czy para powinna zarządzać związkiem jak projektem?',
       'What''s untended withers', 'Co niedoglądane, to więdnie',
       'Romance dies in meetings', 'Romantyzm umiera na zebraniach',
       null, null),
      ('Relationships', false,
       'In love, is the one who loves more the one who loses?',
       'Czy w miłości ten, kto kocha mocniej, przegrywa?',
       'Power flows to the cooler heart', 'Władzę ma chłodniejsze serce',
       'Loving fully is the win itself', 'Kochać na całego to już wygrana',
       null, null),
      ('Relationships', false,
       'Is eloping, just the two of you, more romantic than a big wedding?',
       'Czy ślub w tajemnicy, tylko we dwoje, jest bardziej romantyczny niż wielkie wesele?',
       'Just you two and the truth', 'Tylko wy i prawda',
       'Joy grows when witnessed', 'Radość rośnie, gdy ma świadków',
       null, null),
      ('Relationships', false,
       'Should you confess feelings to a close friend, knowing it could end the friendship?',
       'Czy wyznać uczucia bliskiemu przyjacielowi, wiedząc, że to może zakończyć przyjaźń?',
       'Silence is a slow goodbye', 'Milczenie to powolne pożegnanie',
       'Some doors close forever', 'Niektóre drzwi zamykają się na zawsze',
       null, null),
      ('Relationships', false,
       'Is telling your friends about your relationship fights a betrayal?',
       'Czy opowiadanie przyjaciołom o kłótniach w związku to zdrada?',
       'That fight belonged to you both', 'Ta kłótnia należała do was dwojga',
       'Everyone needs a witness', 'Każdy potrzebuje świadka',
       null, null),
      ('Relationships', false,
       'Could you be happy with someone exactly like yourself?',
       'Czy byłbyś szczęśliwy z kimś dokładnie takim jak ty?',
       'Finally, total understanding', 'Nareszcie pełne zrozumienie',
       'You''d drive yourself mad', 'Doprowadziłbyś sam siebie do szału',
       null, null),
      ('Relationships', false,
       'Should divorce end your bond with your ex''s family too?',
       'Czy rozwód powinien kończyć także więź z rodziną byłego partnera?',
       'The package came apart', 'Pakiet się rozpadł',
       'You divorced one person, not all of them', 'Rozwiodłeś się z jedną osobą, nie ze wszystkimi',
       null, null),
      ('Relationships', false,
       'Is finding new love soon after losing a spouse a betrayal?',
       'Czy nowa miłość krótko po stracie małżonka to zdrada?',
       'The heart is not a gravestone', 'Serce to nie nagrobek',
       'Some vows outlive death', 'Niektóre przysięgi przeżywają śmierć',
       'What would the departed want?', 'Czego chciałby ten, kto odszedł?'),
      ('Relationships', false,
       'Would you trust experts to choose your spouse better than you could?',
       'Czy zaufałbyś ekspertom, że wybiorą ci małżonka lepiej niż ty sam?',
       'Data beats butterflies', 'Dane biją motyle w brzuchu',
       'Chemistry can''t be calculated', 'Chemii nie da się policzyć',
       null, null),
      ('Relationships', false,
       'Should you tell your partner that their family treats you badly?',
       'Czy mówić partnerowi, że jego rodzina źle cię traktuje?',
       'Silence curdles into resentment', 'Przemilczane kwaśnieje w urazę',
       'You''d force them to pick a side', 'Zmusisz go do wyboru strony',
       null, null),
      ('Family', false,
       'Is treating your pet like a child perfectly healthy?',
       'Czy traktowanie zwierzaka jak dziecka jest zupełnie zdrowe?',
       'Love is love', 'Miłość to miłość',
       'A dog needs a dog''s life', 'Pies potrzebuje psiego życia',
       null, null),
      ('Family', false,
       'Should you ever sell a family heirloom to fix real problems?',
       'Czy można sprzedać rodzinną pamiątkę, by rozwiązać prawdziwe problemy?',
       'The living outrank the dead', 'Żywi są ważniejsi od umarłych',
       'Some things we only borrow from the next generation', 'Niektóre rzeczy tylko pożyczamy od następnych pokoleń',
       null, null),
      ('Family', false,
       'Should parents tell their kids about their own youthful mistakes?',
       'Czy rodzice powinni opowiadać dzieciom o własnych młodzieńczych błędach?',
       'A map of the minefield', 'Mapa pola minowego',
       'Confessions become permissions', 'Wyznania stają się przyzwoleniem',
       null, null),
      ('Family', false,
       'Is having a favorite child inevitable rather than shameful?',
       'Czy posiadanie ulubionego dziecka jest nieuniknione, a nie wstydliwe?',
       'The heart doesn''t do arithmetic', 'Serce nie zna arytmetyki',
       'Favorites leave scars on the rest', 'Ulubieńcy zostawiają blizny na pozostałych',
       null, null),
      ('Family', false,
       'Is hiding your tears from your children protecting them?',
       'Czy ukrywanie łez przed dziećmi to ich ochrona?',
       'They need a steady anchor', 'Potrzebują stabilnej kotwicy',
       'They''ll learn feelings are shameful', 'Nauczą się, że uczucia to wstyd',
       null, null),
      ('Family', false,
       'Is telling boys to toughen up ever good parenting?',
       'Czy mówienie chłopcom „bądź twardy" bywa dobrym wychowaniem?',
       'The world won''t be gentle with them', 'Świat nie będzie dla nich delikatny',
       'Armor rusts into loneliness', 'Zbroja rdzewieje w samotność',
       null, null),
      ('Family', false,
       'Would you want to know what your child really thinks of you?',
       'Czy chciałbyś wiedzieć, co twoje dziecko naprawdę o tobie myśli?',
       'The only review that matters', 'Jedyna recenzja, która się liczy',
       'Some truths need decades', 'Niektóre prawdy potrzebują dekad',
       null, null),
      ('Family', false,
       'Should family traditions bend to the youngest generation?',
       'Czy rodzinne tradycje powinny uginać się pod najmłodsze pokolenie?',
       'Traditions serve people, not the reverse', 'Tradycje służą ludziom, nie odwrotnie',
       'Bend enough and nothing is left', 'Wystarczy się naginać, a nic nie zostanie',
       null, null),
      ('Family', false,
       'Is naming your child after yourself an act of vanity?',
       'Czy nazwanie dziecka własnym imieniem to próżność?',
       'A name is not a legacy', 'Imię to nie dziedzictwo',
       'An honor, not a cage', 'Zaszczyt, nie klatka',
       null, null)
    ) as s(category, is_premium, en, pl, a1en, a1pl, a2en, a2pl, a3en, a3pl)
  loop
    -- skip if this EN text was already seeded
    if exists (
      select 1 from public.question_translations
      where locale = 'en' and question_text = r.en
    ) then
      continue;
    end if;

    insert into public.questions (category, is_premium)
    values (r.category, r.is_premium)
    returning id into qid;

    insert into public.question_translations (question_id, locale, question_text)
    values (qid, 'en', r.en),
           (qid, 'pl', r.pl);

    -- smaczek 1 (free teaser) -- always present
    insert into public.question_smaczki (question_id, position, is_active)
    values (qid, 1, true)
    returning id into s1;
    insert into public.question_smaczki_translations (smaczek_id, locale, text)
    values (s1, 'en', r.a1en),
           (s1, 'pl', r.a1pl);

    -- smaczek 2 (premium) -- most questions
    if r.a2en is not null then
      insert into public.question_smaczki (question_id, position, is_active)
      values (qid, 2, true)
      returning id into s2;
      insert into public.question_smaczki_translations (smaczek_id, locale, text)
      values (s2, 'en', r.a2en),
             (s2, 'pl', r.a2pl);
    end if;

    -- smaczek 3 (premium) -- only where a third angle genuinely deepens it
    if r.a3en is not null then
      insert into public.question_smaczki (question_id, position, is_active)
      values (qid, 3, true)
      returning id into s3;
      insert into public.question_smaczki_translations (smaczek_id, locale, text)
      values (s3, 'en', r.a3en),
             (s3, 'pl', r.a3pl);
    end if;
  end loop;
end $$;

-- ----------------------------------------------------------------------------
-- Schedule every still-unscheduled active question onto the next free dates.
-- Keeps Strategy A (unique question_id) intact.
-- ----------------------------------------------------------------------------
insert into public.daily_questions (publish_date, question_id)
select dates.d::date, q.id
from (
  select d, row_number() over (order by d) rn
  from generate_series(current_date, current_date + 1499, '1 day'::interval) d
  where d::date not in (select publish_date from public.daily_questions)
) dates
join (
  select id, row_number() over (order by random()) rn
  from public.questions
  where is_active
    and id not in (select question_id from public.daily_questions)
) q on q.rn = dates.rn
on conflict do nothing;

commit;
