-- ============================================================================
-- Seed batch 5: 125 globally-applicable debate questions (PL + EN) + 2 smaczki
-- ----------------------------------------------------------------------------
-- Generated 2026-07-03. Second half of the 250-question drop started in
-- 20260703120000_seed_global_dilemmas_batch_4.sql — same rules: universal
-- dilemmas, no country/law/currency framings, ~50/50 splits, deduplicated
-- against the full prod catalog (482 EN texts pulled 2026-07-03).
--
-- Smaczki: position 1 free hook, position 2 premium counter-angle.
-- is_premium stays false everywhere (column inert since 2026-07-01).
-- Idempotent: keyed on EN text.
-- Topics in this file: Money (15 of 19), Work (19), Technology (20),
-- Health (18), Culture (36), Environment (8), Lifestyle (9).
-- ============================================================================

begin;

do $$
declare
  r   record;
  qid uuid;
  s1  uuid;
  s2  uuid;
begin
  for r in
    select * from (values
      ('Money', false,
       'Is pirating a film from a giant corporation really theft?',
       'Czy piracenie filmu od wielkiej korporacji to naprawdę kradzież?',
       'They won''t even notice', 'Nawet tego nie zauważą',
       'Someone''s work is someone''s work', 'Czyjaś praca to czyjaś praca'),
      ('Money', false,
       'Is it wrong to drive a hard bargain with someone poorer than you?',
       'Czy twarde negocjacje z kimś biedniejszym od ciebie są złe?',
       'A deal is a deal', 'Umowa to umowa',
       'You squeeze where it hurts', 'Ściskasz tam, gdzie boli'),
      ('Money', false,
       'Is giving cash as a gift thoughtful rather than lazy?',
       'Czy pieniądze w prezencie to troska, a nie lenistwo?',
       'They''ll buy what they truly want', 'Kupią, co naprawdę chcą',
       'Zero thought, zero heart', 'Zero pomysłu, zero serca'),
      ('Money', false,
       'Is reselling scarce tickets at a huge markup just smart business?',
       'Czy odsprzedaż biletów z wielką przebitką to po prostu sprytny biznes?',
       'Supply meets demand', 'Popyt spotyka podaż',
       'Fans pay, middlemen profit', 'Fani płacą, pośrednik zarabia'),
      ('Money', false,
       'Is insuring everything mostly paying for fear?',
       'Czy ubezpieczanie wszystkiego to głównie płacenie za strach?',
       'The casino always wins', 'Kasyno zawsze wygrywa',
       'One bad day repays it all', 'Jeden zły dzień zwraca wszystko'),
      ('Money', false,
       'Should the birthday person''s dinner be paid for by the guests?',
       'Czy kolację urodzinową powinni opłacić goście?',
       'It''s their day', 'To ich święto',
       'You invited, you pay', 'Zapraszasz — płacisz'),
      ('Money', false,
       'If someone freely accepts low pay, is paying it still exploitation?',
       'Jeśli ktoś dobrowolnie godzi się na niską płacę, czy to nadal wyzysk?',
       'A choice made hungry isn''t free', 'Wybór z głodu nie jest wolny',
       'Agreed is agreed', 'Jak się umówili, tak jest'),
      ('Money', false,
       'Is giving money straight to a person in need better than giving to charities?',
       'Czy dawanie pieniędzy prosto potrzebującemu jest lepsze niż wpłata na organizacje?',
       'No middlemen, no offices', 'Bez pośredników i biur',
       'Experts help smarter', 'Eksperci pomagają mądrzej'),
      ('Money', false,
       'Is taking money from your parents as an adult embarrassing?',
       'Czy branie pieniędzy od rodziców w dorosłości jest wstydliwe?',
       'Stand on your own feet', 'Stój na własnych nogach',
       'Family helps family', 'Rodzina pomaga rodzinie'),
      ('Money', false,
       'If a parent''s will wrongs one sibling, should you fix it from your share?',
       'Gdy testament rodzica krzywdzi twoje rodzeństwo, czy naprawić to ze swojej części?',
       'Fairness over paper', 'Sprawiedliwość ponad papier',
       'It was their last wish', 'To była ostatnia wola'),
      ('Money', false,
       'Is tracking every small expense worth the effort?',
       'Czy notowanie każdego drobnego wydatku jest warte zachodu?',
       'Pennies decide fortunes', 'Grosze decydują o fortunie',
       'Life is not a spreadsheet', 'Życie to nie arkusz kalkulacyjny'),
      ('Money', false,
       'If you got rich overnight, would you owe your family a share?',
       'Gdybyś z dnia na dzień się wzbogacił, czy byłbyś winien rodzinie część?',
       'You didn''t get here alone', 'Nie doszedłeś tu sam',
       'Luck is not a debt', 'Szczęście to nie dług'),
      ('Money', false,
       'Does being richer than your neighbors matter more than being rich?',
       'Czy bycie bogatszym od sąsiadów znaczy więcej niż bycie bogatym?',
       'Everything is comparison', 'Wszystko jest porównaniem',
       'Envy is a poor ruler', 'Zazdrość to zła miarka'),
      ('Money', false,
       'Is asking strangers online to fund your dreams shameless?',
       'Czy proszenie obcych w sieci o finansowanie marzeń to bezwstyd?',
       'Earn it like everyone else', 'Zapracuj jak każdy',
       'No one has to give', 'Nikt nie musi wpłacać'),
      ('Money', false,
       'Is never truly owning your music and films a bad deal?',
       'Czy to, że nie posiadasz już muzyki i filmów na własność, to zły interes?',
       'One click and it''s gone', 'Jedno kliknięcie i znika',
       'The whole world for pennies', 'Cały świat za grosze'),
      ('Work', false,
       'Is stretching the truth on your CV ever acceptable?',
       'Czy podkoloryzowanie CV bywa dopuszczalne?',
       'Everyone polishes the story', 'Każdy poleruje swoją historię',
       'It starts with a lie', 'Zaczyna się od kłamstwa'),
      ('Work', false,
       'Should you tell your boss you''re looking for another job?',
       'Czy powiedzieć szefowi, że szukasz innej pracy?',
       'Honesty buys respect', 'Szczerość kupuje szacunek',
       'You''ll be written off', 'Zostaniesz skreślony'),
      ('Work', false,
       'Is it wrong to work for a company whose values you oppose?',
       'Czy praca dla firmy, której wartości odrzucasz, jest zła?',
       'Your work is your signature', 'Praca to twój podpis',
       'Bills don''t ask about values', 'Rachunki nie pytają o wartości'),
      ('Work', false,
       'Is it wiser to keep coworkers at arm''s length than befriend them?',
       'Czy mądrzej trzymać współpracowników na dystans, niż się z nimi przyjaźnić?',
       'Work and heart don''t mix', 'Praca i serce to osobne światy',
       'Eight hours a day alone?', 'Osiem godzin dziennie w samotności?'),
      ('Work', false,
       'Is expecting your job to give life meaning asking too much?',
       'Czy oczekiwanie, że praca nada życiu sens, to za dużo?',
       'Meaning lives after hours', 'Sens mieszka po godzinach',
       'A third of your life is spent there', 'To jedna trzecia życia'),
      ('Work', false,
       'Should you push through and work when you''re mildly sick?',
       'Czy przemęczać się w pracy przy lekkiej chorobie?',
       'The team counts on you', 'Zespół na ciebie liczy',
       'Heroes infect the office', 'Bohaterowie zarażają biuro'),
      ('Work', false,
       'Is secretly working two full-time remote jobs wrong if you deliver both?',
       'Czy potajemna praca na dwóch zdalnych etatach jest zła, jeśli oba dowozisz?',
       'Results are results', 'Wyniki to wyniki',
       'Loyalty can''t be split', 'Lojalności nie da się podzielić'),
      ('Work', false,
       'Should you report a likeable coworker who barely works?',
       'Czy zgłosić lubianego współpracownika, który prawie nie pracuje?',
       'You carry their load', 'To ty nosisz jego ciężar',
       'Nobody likes an informer', 'Nikt nie lubi donosiciela'),
      ('Work', false,
       'Is a university degree still worth the years and the cost?',
       'Czy studia wciąż są warte tych lat i pieniędzy?',
       'Doors still check diplomas', 'Drzwi wciąż sprawdzają dyplomy',
       'Skills outrun certificates', 'Umiejętności wyprzedzają papiery'),
      ('Work', false,
       'Should you follow a plan you know is bad because the boss decided?',
       'Czy realizować plan, o którym wiesz, że jest zły, bo tak zdecydował szef?',
       'Their call, their responsibility', 'Jego decyzja, jego odpowiedzialność',
       'You see the iceberg', 'To ty widzisz górę lodową'),
      ('Work', false,
       'Should a nap at work be as normal as a coffee break?',
       'Czy drzemka w pracy powinna być tak normalna jak przerwa na kawę?',
       'Rested brains earn more', 'Wypoczęty mózg zarabia więcej',
       'Work is not a bedroom', 'Praca to nie sypialnia'),
      ('Work', false,
       'Should you take a promotion into management if you''d enjoy the work less?',
       'Czy przyjąć awans na menedżera, jeśli sama praca będzie ci się mniej podobać?',
       'Up is the only direction', 'W górę to jedyny kierunek',
       'Trade joy for meetings?', 'Zamienić radość na zebrania?'),
      ('Work', false,
       'Is crying at work unprofessional?',
       'Czy płacz w pracy jest nieprofesjonalny?',
       'Emotions stay at the door', 'Emocje zostają za drzwiami',
       'You hired a human', 'Zatrudniłeś człowieka'),
      ('Work', false,
       'Should you be able to sell your unused vacation days back for money?',
       'Czy powinno się móc odsprzedawać niewykorzystany urlop za pieniądze?',
       'Your days, your currency', 'Twoje dni, twoja waluta',
       'Rest shouldn''t have a price tag', 'Odpoczynek nie powinien mieć ceny'),
      ('Work', false,
       'Should people with physically hard jobs retire earlier than office workers?',
       'Czy pracujący fizycznie powinni przechodzić na emeryturę wcześniej niż biurowi?',
       'Bodies wear out faster', 'Ciało zużywa się szybciej',
       'Who measures whose burden?', 'Kto zmierzy czyj ciężar?'),
      ('Work', false,
       'Is a prestigious company name on your CV worth a smaller paycheck?',
       'Czy prestiżowa firma w CV jest warta niższej pensji?',
       'That name opens doors later', 'Ta nazwa otworzy ci drzwi',
       'Prestige doesn''t pay rent', 'Prestiż nie płaci czynszu'),
      ('Work', false,
       'Is a dream job worth enduring a terrible boss?',
       'Czy wymarzona praca jest warta znoszenia okropnego szefa?',
       'You work for the work', 'Pracujesz dla dzieła',
       'People leave bosses, not jobs', 'Odchodzi się od szefów, nie z firm'),
      ('Work', false,
       'Is a company calling itself "a family" a warning sign?',
       'Czy firma nazywająca się „rodziną" to sygnał ostrzegawczy?',
       'Family doesn''t fire you', 'Rodzina cię nie zwalnia',
       'Maybe they just care', 'Może im po prostu zależy'),
      ('Work', false,
       'Should you tell an interviewer your real weaknesses?',
       'Czy mówić rekruterowi o swoich prawdziwych słabościach?',
       'Truth surfaces anyway', 'Prawda i tak wypłynie',
       'It''s a game — play it', 'To gra — graj w nią'),
      ('Technology', false,
       'Is relying on GPS for every trip making us helpless?',
       'Czy poleganie na nawigacji przy każdej trasie robi z nas bezradnych?',
       'Could you find home without it?', 'Trafiłbyś do domu bez niej?',
       'Maps freed our heads', 'Mapy uwolniły nam głowy'),
      ('Technology', false,
       'Would a world without any cash be a better world?',
       'Czy świat całkiem bez gotówki byłby lepszy?',
       'Lighter pockets, faster life', 'Lżejsza kieszeń, szybsze życie',
       'Every coin you spend is watched', 'Każdy twój grosz jest widziany'),
      ('Technology', false,
       'Is photographing strangers in public without asking wrong?',
       'Czy fotografowanie obcych w miejscach publicznych bez pytania jest złe?',
       'Public space, public faces', 'Publiczna przestrzeń, publiczne twarze',
       'Their face, their choice', 'Ich twarz, ich wybór'),
      ('Technology', false,
       'Is filming wrongdoing more useful than stepping in?',
       'Czy nagrywanie zła jest bardziej przydatne niż interwencja?',
       'Proof changes everything', 'Dowód zmienia wszystko',
       'The camera never saved anyone', 'Kamera nikogo nie uratowała'),
      ('Technology', false,
       'Are long voice messages a selfish way to communicate?',
       'Czy długie wiadomości głosowe to egoistyczna forma kontaktu?',
       'Your minute, their five', 'Twoja minuta to ich pięć',
       'It''s a human voice, finally', 'To wreszcie ludzki głos'),
      ('Technology', false,
       'Is turning off read receipts a small act of dishonesty?',
       'Czy wyłączenie potwierdzeń odczytu to drobna nieszczerość?',
       'You read it — admit it', 'Widziałeś — przyznaj się',
       'Peace over pressure', 'Spokój ponad presją'),
      ('Technology', false,
       'Is replacing every cashier with a machine making life worse?',
       'Czy zastępowanie każdego kasjera maszyną psuje nam życie?',
       'For some it''s the only chat of the day', 'Dla niektórych to jedyna rozmowa dnia',
       'No queue, no chit-chat', 'Brak kolejki, brak gadania'),
      ('Technology', false,
       'Is laughing at strangers'' fail videos harmless fun?',
       'Czy śmianie się z cudzych wpadek w sieci to niewinna rozrywka?',
       'They''d laugh too', 'Sami też by się śmiali',
       'That''s someone''s worst day', 'To czyjś najgorszy dzień'),
      ('Technology', false,
       'Would you get a payment chip under your skin to never carry a wallet?',
       'Czy wszczepiłbyś sobie chip płatniczy, by nigdy nie nosić portfela?',
       'You can''t lose your hand', 'Ręki nie zgubisz',
       'Your body is not a terminal', 'Twoje ciało to nie terminal'),
      ('Technology', false,
       'Should the news show the ugliest images of war and disaster?',
       'Czy wiadomości powinny pokazywać najbrutalniejsze obrazy wojen i katastrof?',
       'Truth shouldn''t be cropped', 'Prawdy się nie kadruje',
       'Horror numbs, it doesn''t teach', 'Groza znieczula, nie uczy'),
      ('Technology', false,
       'Do you have a duty to follow the news every day?',
       'Czy masz obowiązek codziennie śledzić wiadomości?',
       'Citizens must know', 'Obywatel musi wiedzieć',
       'Your peace matters more', 'Twój spokój znaczy więcej'),
      ('Technology', false,
       'Is secretly recording a conversation you''re part of ever fair?',
       'Czy potajemne nagrywanie rozmowy, w której uczestniczysz, bywa fair?',
       'Memory is a poor witness', 'Pamięć to słaby świadek',
       'Trust dies on tape', 'Zaufanie umiera na taśmie'),
      ('Technology', false,
       'Is sending AI-written messages to someone you love dishonest?',
       'Czy wysyłanie ukochanej osobie wiadomości napisanych przez AI to nieszczerość?',
       'Borrowed words, borrowed heart', 'Pożyczone słowa, pożyczone serce',
       'You felt it, it just typed', 'Ty to czułeś, ono tylko spisało'),
      ('Technology', false,
       'Could a robot pet ever give you what a real animal does?',
       'Czy robot-zwierzak mógłby ci dać to, co prawdziwe zwierzę?',
       'No fur, no funerals', 'Bez sierści i bez pożegnań',
       'It doesn''t actually love you', 'On cię przecież nie kocha'),
      ('Technology', false,
       'Is watching films at home simply better than the cinema now?',
       'Czy oglądanie filmów w domu jest już po prostu lepsze niż kino?',
       'Pause, pajamas, your sofa', 'Pauza, piżama, twoja kanapa',
       'The big screen is a temple', 'Wielki ekran to świątynia'),
      ('Technology', false,
       'Is arguing with strangers on the internet ever worth it?',
       'Czy kłótnie z obcymi w internecie bywają coś warte?',
       'Silence lets nonsense win', 'Milczenie oddaje pole bzdurom',
       'Nobody ever changes their mind', 'Nikt nigdy nie zmienia zdania'),
      ('Technology', false,
       'Is blocking ads on free websites a form of theft?',
       'Czy blokowanie reklam na darmowych stronach to forma kradzieży?',
       'Someone pays for "free"', 'Ktoś płaci za to „darmowe"',
       'My screen, my rules', 'Mój ekran, moje zasady'),
      ('Technology', false,
       'Should phones be locked away at concerts?',
       'Czy telefony powinny być zamykane na koncertach?',
       'Live means living it', 'Na żywo znaczy naprawdę',
       'My memory, my phone', 'Moje wspomnienie, mój telefon'),
      ('Technology', false,
       'Would you want a recording of every moment of your life?',
       'Czy chciałbyś mieć nagranie każdej chwili swojego życia?',
       'Nothing lost, ever', 'Nic już nie przepadnie',
       'Some moments should fade', 'Niektóre chwile powinny blednąć'),
      ('Technology', false,
       'Would you take a one-way ticket to be among the first on Mars?',
       'Czy wziąłbyś bilet w jedną stronę, by być wśród pierwszych na Marsie?',
       'A page in history', 'Strona w historii',
       'You''d never hear rain again', 'Nigdy już nie usłyszysz deszczu'),
      ('Health', false,
       'Is judging someone by their tattoos ever fair?',
       'Czy ocenianie kogoś po tatuażach bywa uzasadnione?',
       'Skin speaks on purpose', 'Skóra mówi celowo',
       'Ink is not character', 'Tusz to nie charakter'),
      ('Health', false,
       'Is drinking alone at home a warning sign?',
       'Czy picie w pojedynkę w domu to sygnał ostrzegawczy?',
       'Habits grow in silence', 'Nałogi rosną w ciszy',
       'A glass isn''t a cry for help', 'Kieliszek to nie wołanie o pomoc'),
      ('Health', false,
       'Are we too quick to call ordinary sadness an illness?',
       'Czy zbyt szybko nazywamy zwykły smutek chorobą?',
       'Sadness is part of life', 'Smutek to część życia',
       'Better too early than too late', 'Lepiej za wcześnie niż za późno'),
      ('Health', false,
       'Is meditation overrated as a cure for modern stress?',
       'Czy medytacja jest przereklamowana jako lek na stres?',
       'Sitting won''t pay your bills', 'Siedzenie nie opłaci rachunków',
       'Millennia of practice know something', 'Tysiące lat praktyki coś wiedzą'),
      ('Health', false,
       'Would you take a test revealing every disease you''re at risk of?',
       'Czy zrobiłbyś test ujawniający wszystkie choroby, które ci grożą?',
       'Forewarned is forearmed', 'Przezorny zawsze ubezpieczony',
       'You''d live waiting', 'Żyłbyś w oczekiwaniu'),
      ('Health', false,
       'Should younger patients come first when there aren''t enough organs?',
       'Czy młodsi pacjenci powinni mieć pierwszeństwo, gdy narządów brakuje?',
       'More life to save', 'Więcej życia do ocalenia',
       'Every life counts the same', 'Każde życie liczy się tak samo'),
      ('Health', false,
       'Should doctors be allowed to prescribe placebos without telling you?',
       'Czy lekarze powinni móc przepisywać placebo bez twojej wiedzy?',
       'If it works, it works', 'Skoro działa, to działa',
       'Healing built on a lie', 'Leczenie na kłamstwie'),
      ('Health', false,
       'Do you know your own body better than your doctor does?',
       'Czy znasz swoje ciało lepiej niż twój lekarz?',
       'You''ve lived in it for years', 'Mieszkasz w nim całe życie',
       'Feelings aren''t lab results', 'Odczucia to nie wyniki badań'),
      ('Health', false,
       'Is addiction an illness rather than a choice?',
       'Czy uzależnienie to choroba, a nie wybór?',
       'Nobody chooses the cage', 'Nikt nie wybiera klatki',
       'The first time was a choice', 'Pierwszy raz był wyborem'),
      ('Health', false,
       'If doping were open and equal for everyone, would sport be fairer?',
       'Czy sport byłby uczciwszy, gdyby doping był jawny i dostępny dla wszystkich?',
       'At least it''s honest', 'Przynajmniej w otwarte karty',
       'It becomes a chemists'' race', 'To już wyścig chemików'),
      ('Health', false,
       'Is complimenting someone''s weight loss a bad habit?',
       'Czy komplementowanie czyjegoś schudnięcia to zły nawyk?',
       'You don''t know their story', 'Nie znasz ich historii',
       'Kind words are kind', 'Miłe słowo to miłe słowo'),
      ('Health', false,
       'Is keeping a serious illness secret from your family your right?',
       'Czy zatajenie poważnej choroby przed rodziną to twoje prawo?',
       'It''s your battle', 'To twoja walka',
       'They''d want to carry it too', 'Bliscy chcą to nieść z tobą'),
      ('Health', false,
       'Would you edit your own genes to be healthier?',
       'Czy poprawiłbyś własne geny, by być zdrowszym?',
       'Your body, your code', 'Twoje ciało, twój kod',
       'Where does fixing end?', 'Gdzie kończy się naprawianie?'),
      ('Health', false,
       'Would you give one of your kidneys to save a stranger?',
       'Czy oddałbyś nerkę, by uratować obcego człowieka?',
       'You have a spare', 'Masz przecież zapasową',
       'Charity begins at home', 'Najpierw swoi'),
      ('Health', false,
       'Would you take a pill that erased all your fear?',
       'Czy wziąłbyś tabletkę, która usuwa cały strach?',
       'Fear is the only wall', 'Strach to jedyny mur',
       'Fear keeps you alive', 'Strach trzyma cię przy życiu'),
      ('Health', false,
       'Would a life without physical pain be a better life?',
       'Czy życie bez fizycznego bólu byłoby lepsze?',
       'Imagine never hurting', 'Wyobraź sobie: nic nie boli',
       'Pain is the body''s alarm', 'Ból to alarm ciała'),
      ('Health', false,
       'Is the world unfairly built for morning people?',
       'Czy świat jest niesprawiedliwie urządzony pod ranne ptaszki?',
       'Eight a.m. punishes half of us', 'Ósma rano karze połowę z nas',
       'Someone has to open the bakery', 'Ktoś musi otworzyć piekarnię'),
      ('Health', false,
       'Is filling every quiet moment with sound robbing you of your thoughts?',
       'Czy zagłuszanie każdej cichej chwili odbiera ci własne myśli?',
       'You never meet yourself', 'Nigdy nie spotykasz samego siebie',
       'Life just sounds better with music', 'Z muzyką życie po prostu brzmi lepiej'),
      ('Culture', false,
       'Does everything happen for a reason?',
       'Czy wszystko dzieje się z jakiegoś powodu?',
       'The dots connect backwards', 'Kropki łączą się wstecz',
       'Chaos owes you no story', 'Chaos nie jest ci winien historii'),
      ('Culture', false,
       'Do we truly choose anything freely?',
       'Czy cokolwiek naprawdę wybieramy sami?',
       'You could have done otherwise', 'Mogłeś przecież inaczej',
       'Your brain decided first', 'Mózg zdecydował pierwszy'),
      ('Culture', false,
       'Is reading horoscopes harmless fun?',
       'Czy czytanie horoskopów to niewinna zabawa?',
       'It''s entertainment, relax', 'To rozrywka, wyluzuj',
       'Little lies grow big', 'Małe kłamstwa rosną'),
      ('Culture', false,
       'Can people truly change who they are?',
       'Czy ludzie naprawdę mogą zmienić to, kim są?',
       'Every day rewires us', 'Każdy dzień nas przepisuje',
       'The core never moves', 'Rdzeń zostaje ten sam'),
      ('Culture', false,
       'Is happiness mostly a choice?',
       'Czy szczęście to w większości wybór?',
       'Same rain, different moods', 'Ten sam deszcz, różne humory',
       'Try choosing it in tragedy', 'Wybierz je w tragedii'),
      ('Culture', false,
       'Can you understand the world deeply without ever traveling far?',
       'Czy można głęboko rozumieć świat, nigdy daleko nie podróżując?',
       'Books travel further', 'Książki podróżują dalej',
       'You have to smell a place', 'Miejsce trzeba poczuć nosem'),
      ('Culture', false,
       'Is being the best in a small circle better than average among the best?',
       'Czy lepiej być najlepszym w małym gronie niż przeciętnym wśród najlepszych?',
       'Confidence grows where you shine', 'Pewność rośnie tam, gdzie błyszczysz',
       'Giants make you grow', 'Przy gigantach się rośnie'),
      ('Culture', false,
       'Is swearing in everyday speech nothing to apologize for?',
       'Czy przekleństwa na co dzień to nic, za co trzeba przepraszać?',
       'Honest words, strong feelings', 'Szczere słowa, mocne emocje',
       'Language shapes the room', 'Język tworzy atmosferę'),
      ('Culture', false,
       'Should old traditions be kept alive even when they cause harm?',
       'Czy stare tradycje powinny trwać, nawet gdy wyrządzają krzywdę?',
       'Roots hold us up', 'Korzenie nas trzymają',
       'Harm is harm, even in costume', 'Krzywda to krzywda, nawet w stroju ludowym'),
      ('Culture', false,
       'Do you owe anything to the place you grew up in?',
       'Czy jesteś coś winien miejscu, w którym dorastałeś?',
       'It made you', 'To ono cię ukształtowało',
       'You didn''t choose your cradle', 'Kołyski się nie wybiera'),
      ('Culture', false,
       'In hard times, is art as necessary as bread?',
       'Czy w trudnych czasach sztuka jest równie potrzebna jak chleb?',
       'Souls starve too', 'Dusza też głoduje',
       'Try eating a poem', 'Spróbuj zjeść wiersz'),
      ('Culture', false,
       'Should we stop honoring great people once we learn of their crimes?',
       'Czy przestać czcić wielkich ludzi, gdy poznajemy ich zbrodnie?',
       'Honor the whole truth', 'Cześć należy się całej prawdzie',
       'The deeds remain great', 'Dzieła pozostają wielkie'),
      ('Culture', false,
       'Are some topics simply off-limits for jokes?',
       'Czy istnieją tematy, z których po prostu nie wolno żartować?',
       'Some wounds never close', 'Niektóre rany się nie zamykają',
       'Laughter is how we survive', 'Śmiech pozwala przetrwać'),
      ('Culture', false,
       'Should funerals celebrate a life rather than mourn a death?',
       'Czy pogrzeb powinien świętować życie zamiast opłakiwać śmierć?',
       'They''d want you smiling', 'Chcieliby twojego uśmiechu',
       'Grief needs its tears', 'Żałoba potrzebuje łez'),
      ('Culture', false,
       'Should the dead be spoken of honestly rather than only kindly?',
       'Czy o zmarłych należy mówić szczerze, a nie tylko dobrze?',
       'Death doesn''t rewrite the story', 'Śmierć nie przepisuje historii',
       'Let them rest in peace', 'Pozwól im spoczywać w spokoju'),
      ('Culture', false,
       'Can a popcorn blockbuster be worth as much as high art?',
       'Czy kinowy hit może być wart tyle, co sztuka wysoka?',
       'Joy is joy', 'Radość to radość',
       'Sugar is not a meal', 'Cukier to nie obiad'),
      ('Culture', false,
       'Is uncommissioned street art still vandalism?',
       'Czy nielegalne graffiti to wciąż wandalizm?',
       'It''s someone else''s wall', 'To czyjaś ściana',
       'The street is a gallery', 'Ulica to galeria'),
      ('Culture', false,
       'Is switching the team you support a betrayal?',
       'Czy zmiana klubu, któremu kibicujesz, to zdrada?',
       'Loyalty is the whole point', 'Wierność to sedno kibicowania',
       'It''s entertainment, not marriage', 'To rozrywka, nie małżeństwo'),
      ('Culture', false,
       'Is mastering one thing better than being good at many?',
       'Czy lepiej być mistrzem jednej rzeczy niż dobrym w wielu?',
       'Depth beats width', 'Głębia bije szerokość',
       'The world rewards the flexible', 'Świat nagradza elastycznych'),
      ('Culture', false,
       'Is expecting the worst the smartest way to live?',
       'Czy zakładanie najgorszego to najmądrzejszy sposób na życie?',
       'Never disappointed again', 'Koniec z rozczarowaniami',
       'You pay for it daily', 'Płacisz za to każdego dnia'),
      ('Culture', false,
       'Would most people be happier living outside big cities?',
       'Czy większość ludzi byłaby szczęśliwsza poza wielkimi miastami?',
       'Trees beat traffic', 'Drzewa wygrywają z korkami',
       'Cities are where life happens', 'To w miastach dzieje się życie'),
      ('Culture', false,
       'Do spoilers really ruin a good story?',
       'Czy spoilery naprawdę psują dobrą historię?',
       'The ending was the gift', 'Zakończenie było prezentem',
       'Great stories can''t be spoiled', 'Wielkich historii nie da się zepsuć'),
      ('Culture', false,
       'Should treasures taken long ago be returned to where they came from?',
       'Czy skarby zabrane przed wiekami powinny wrócić tam, skąd pochodzą?',
       'Stolen stays stolen', 'Kradzione pozostaje kradzione',
       'History belongs to everyone', 'Historia należy do wszystkich'),
      ('Culture', false,
       'Can you enjoy great art made by a terrible person?',
       'Czy można cieszyć się wielką sztuką stworzoną przez okropnego człowieka?',
       'The art outgrows its maker', 'Dzieło przerasta twórcę',
       'Applause feeds the monster', 'Oklaski karmią potwora'),
      ('Culture', false,
       'Does having no regrets mean you played it too safe?',
       'Czy brak jakichkolwiek żali oznacza, że grałeś zbyt ostrożnie?',
       'Scars prove you tried', 'Blizny dowodzą prób',
       'You can walk wisely, not timidly', 'Można iść mądrze, nie bojaźliwie'),
      ('Culture', false,
       'Can envy be good fuel rather than poison?',
       'Czy zazdrość może być paliwem, a nie trucizną?',
       'It shows you what you want', 'Pokazuje ci, czego chcesz',
       'It burns the tank it fills', 'Spala bak, który napełnia'),
      ('Culture', false,
       'Would you live your exact same life again from the start?',
       'Czy przeżyłbyś jeszcze raz dokładnie to samo życie?',
       'It led you here', 'Doprowadziło cię tutaj',
       'Once was enough', 'Raz wystarczy'),
      ('Culture', false,
       'Is your gut feeling usually smarter than your reasoning?',
       'Czy przeczucie jest zwykle mądrzejsze niż rozum?',
       'Instinct is ancient wisdom', 'Instynkt to prastara mądrość',
       'Gut feelings sank ships', 'Przeczucia zatapiały okręty'),
      ('Culture', false,
       'Does power corrupt everyone, given enough time?',
       'Czy władza z czasem psuje każdego?',
       'History keeps receipts', 'Historia trzyma rachunki',
       'Character can hold the line', 'Charakter potrafi się obronić'),
      ('Culture', false,
       'Is the world actually getting better, whatever the news says?',
       'Czy świat naprawdę staje się lepszy, cokolwiek mówią wiadomości?',
       'Look at the long charts', 'Spójrz na długie wykresy',
       'Tell that to today''s victims', 'Powiedz to dzisiejszym ofiarom'),
      ('Culture', false,
       'Is lasting love more a choice than a feeling?',
       'Czy trwała miłość to bardziej wybór niż uczucie?',
       'You choose them every morning', 'Wybierasz ją każdego ranka',
       'You can''t decide to feel', 'Uczuć się nie postanawia'),
      ('Culture', false,
       'Is being respected worth more than being liked?',
       'Czy szacunek jest wart więcej niż sympatia?',
       'Respect survives storms', 'Szacunek przetrwa burze',
       'Cold respect, lonely evenings', 'Chłodny szacunek, samotne wieczory'),
      ('Culture', false,
       'Is perfectionism more a gift than a curse?',
       'Czy perfekcjonizm to bardziej dar niż przekleństwo?',
       'Great things demand it', 'Wielkie rzeczy go wymagają',
       'Done beats perfect', 'Zrobione bije idealne'),
      ('Culture', false,
       'Do most adults still feel like they''re just pretending to be adults?',
       'Czy większość dorosłych wciąż czuje, że tylko udaje dorosłość?',
       'Everyone improvises', 'Wszyscy improwizują',
       'Some really do grow up', 'Niektórzy naprawdę dorastają'),
      ('Culture', false,
       'Is voting blindly worse than not voting at all?',
       'Czy głosowanie na ślepo jest gorsze niż niegłosowanie wcale?',
       'A blind vote steers too', 'Ślepy głos też steruje',
       'Showing up still matters', 'Sama obecność ma znaczenie'),
      ('Culture', false,
       'Is cutting all ties and starting over somewhere new a right everyone has?',
       'Czy zerwanie wszystkich więzi i start od zera gdzie indziej to prawo każdego z nas?',
       'Your life belongs to you', 'Twoje życie należy do ciebie',
       'Someone waits by the phone', 'Ktoś czeka przy telefonie'),
      ('Environment', false,
       'Do your small green choices matter while industries pollute at scale?',
       'Czy twoje małe ekologiczne wybory mają znaczenie, gdy przemysł truje na potęgę?',
       'Millions of small acts add up', 'Miliony drobiazgów to potęga',
       'A drop against a flood', 'Kropla przeciw powodzi'),
      ('Environment', false,
       'Should we bring extinct species back to life if we can?',
       'Czy powinniśmy wskrzeszać wymarłe gatunki, skoro potrafimy?',
       'We owe them that much', 'Tyle jesteśmy im winni',
       'Their world is gone', 'Ich świata już nie ma'),
      ('Environment', false,
       'Should fragile natural wonders be closed to tourists completely?',
       'Czy kruche cuda natury powinny być całkiem zamknięte dla turystów?',
       'Love them from afar', 'Kochaj z daleka',
       'Beauty no one sees', 'Piękno, którego nikt nie zobaczy'),
      ('Environment', false,
       'Should pet cats be kept indoors for the sake of wildlife?',
       'Czy koty domowe powinny zostawać w domu dla dobra dzikiej przyrody?',
       'Billions of birds a year', 'Miliardy ptaków rocznie',
       'A cat needs to roam', 'Kot musi buszować'),
      ('Environment', false,
       'Is killing a spider in your home a small wrong?',
       'Czy zabicie pająka w domu to małe zło?',
       'It was a life', 'To było życie',
       'My home, not his', 'To mój dom, nie jego'),
      ('Environment', false,
       'Is feeding wild animals in parks a kindness?',
       'Czy dokarmianie dzikich zwierząt w parkach to dobroć?',
       'Winter is merciless', 'Zima nie zna litości',
       'You''re taming them to death', 'Oswajasz je na zgubę'),
      ('Environment', false,
       'Should humanity wipe out the mosquito if it could?',
       'Czy ludzkość powinna zlikwidować komary, gdyby mogła?',
       'The deadliest animal on Earth', 'Najbardziej zabójcze zwierzę świata',
       'Pull one thread, unravel it all', 'Pociągnij nitkę, spruje się całość'),
      ('Environment', false,
       'Is food flown across the world a luxury we should give up?',
       'Czy jedzenie latające przez pół świata to luksus, z którego trzeba zrezygnować?',
       'Eat what grows nearby', 'Jedz to, co rośnie obok',
       'The world on a plate is a miracle', 'Świat na talerzu to cud'),
      ('Lifestyle', false,
       'Is a resort holiday as valid as "real" traveling?',
       'Czy wakacje w resorcie są równie wartościowe jak „prawdziwe" podróżowanie?',
       'Rest is the whole point', 'Odpoczynek to istota urlopu',
       'You saw the pool, not the country', 'Widziałeś basen, nie kraj'),
      ('Lifestyle', false,
       'Does photographing every moment steal something from it?',
       'Czy fotografowanie każdej chwili coś jej odbiera?',
       'You lived it through a lens', 'Przeżyłeś to przez obiektyw',
       'Memory fades, photos stay', 'Pamięć blaknie, zdjęcia zostają'),
      ('Lifestyle', false,
       'When visiting, must you follow local customs you disagree with?',
       'Czy w podróży trzeba przestrzegać lokalnych zwyczajów, z którymi się nie zgadzasz?',
       'Their home, their rules', 'Ich dom, ich zasady',
       'Respect has limits', 'Szacunek ma granice'),
      ('Lifestyle', false,
       'Is refusing to try new foods as an adult a character flaw?',
       'Czy odmawianie próbowania nowych potraw w dorosłości to wada charakteru?',
       'Closed mouth, closed mind', 'Zamknięte usta, zamknięty umysł',
       'Taste is nobody''s business', 'Smak to prywatna sprawa'),
      ('Lifestyle', false,
       'Could a life with no fixed home be a full life?',
       'Czy życie bez stałego domu może być pełne?',
       'The world becomes your home', 'Świat staje się domem',
       'Roots are what hold us', 'To korzenie nas trzymają'),
      ('Lifestyle', false,
       'Is returning to the same holiday place every year a wasted chance?',
       'Czy powrót co roku w to samo miejsce na wakacje to zmarnowana szansa?',
       'So much world unseen', 'Tyle świata niezobaczonego',
       'Some places become family', 'Niektóre miejsca stają się rodziną'),
      ('Lifestyle', false,
       'Is not knowing how to cook as an adult embarrassing?',
       'Czy nieumiejętność gotowania w dorosłości to wstyd?',
       'Feeding yourself is basic', 'Wykarmienie się to podstawa',
       'That''s what restaurants are for', 'Od tego są restauracje'),
      ('Lifestyle', false,
       'Is changing a classic dish an insult to its origins?',
       'Czy zmienianie klasycznej potrawy to obraza jej tradycji?',
       'Grandma''s recipe is sacred', 'Przepis babci jest święty',
       'Every classic was once new', 'Każda klasyka była kiedyś nowością'),
      ('Lifestyle', false,
       'Should pets sleep in their owners'' beds?',
       'Czy zwierzęta powinny spać w łóżkach właścicieli?',
       'They''re family', 'Przecież to rodzina',
       'A bed is for humans', 'Łóżko jest dla ludzi')
    ) as s(category, is_premium, en, pl, a1en, a1pl, a2en, a2pl)
  loop
    -- skip if this EN text was already seeded
    if exists (
      select 1 from public.question_translations
      where locale = 'en' and question_text = r.en
    ) then
      continue;
    end if;

    insert into public.questions (category, is_premium)
    values (r.category, r.is_premium)
    returning id into qid;

    insert into public.question_translations (question_id, locale, question_text)
    values (qid, 'en', r.en),
           (qid, 'pl', r.pl);

    -- smaczek 1 (free teaser)
    insert into public.question_smaczki (question_id, position, is_active)
    values (qid, 1, true)
    returning id into s1;
    insert into public.question_smaczki_translations (smaczek_id, locale, text)
    values (s1, 'en', r.a1en),
           (s1, 'pl', r.a1pl);

    -- smaczek 2 (premium)
    insert into public.question_smaczki (question_id, position, is_active)
    values (qid, 2, true)
    returning id into s2;
    insert into public.question_smaczki_translations (smaczek_id, locale, text)
    values (s2, 'en', r.a2en),
           (s2, 'pl', r.a2pl);
  end loop;
end $$;

-- ----------------------------------------------------------------------------
-- Schedule every still-unscheduled active question onto the next free dates.
-- Keeps Strategy A (unique question_id) intact.
-- ----------------------------------------------------------------------------
insert into public.daily_questions (publish_date, question_id)
select dates.d::date, q.id
from (
  select d, row_number() over (order by d) rn
  from generate_series(current_date, current_date + 1499, '1 day'::interval) d
  where d::date not in (select publish_date from public.daily_questions)
) dates
join (
  select id, row_number() over (order by random()) rn
  from public.questions
  where is_active
    and id not in (select question_id from public.daily_questions)
) q on q.rn = dates.rn
on conflict do nothing;

commit;
