-- ============================================================================
-- Polish copy-editing pass over the 1000-question catalog (2026-07-09)
-- ----------------------------------------------------------------------------
-- Full editorial review of every PL question + smaczek against the EN source.
-- The original bulk translation read stiff/literal in places; this rewrites the
-- weakest PL strings to read as if written natively in Polish (idioms, natural
-- word order, punchier smaczki) while keeping the exact same meaning and the
-- app's existing male-form convention.
--
-- 61 edits across 49 questions: 26 question texts (all PL) + 35 smaczki
-- (33 PL, 2 EN). The 2 EN edits + their PL pair fix a genuine content bug:
-- question 89c2bb8f (auto-added tips) carried smaczki copied from an unrelated
-- question in BOTH languages; replaced with on-topic ones.
--
-- Every UPDATE is guarded by the prior text (… and question_text = '<old>'),
-- so this is idempotent and a no-op on any row that has already drifted or been
-- re-edited. All 61 old values were verified byte-for-byte against prod before
-- writing this file. Prior text (old + new) is backed up in the sibling
-- .backup.json. Touches only translation text — no ids, votes, calendar, or
-- schema.
-- ============================================================================

begin;

update question_translations set question_text='Czy miliarderzy powinni płacić wyższe podatki?' where question_id='e0734eeb-d0e0-4432-8d37-0bac4257b19f'::uuid and locale='pl' and question_text='Czy miliarderzy powinni być bardziej opodatkowani?';
update question_translations set question_text='Czy do posiadania dzieci powinna być wymagana licencja?' where question_id='0d84cbe7-9085-4e16-a6ca-1a43b460b074'::uuid and locale='pl' and question_text='Czy ludzie powinni potrzebować licencji, zanim będą mogli mieć dzieci?';
update question_translations set question_text='Czy sztuczna inteligencja powinna móc podejmować decyzje o życiu i śmierci pacjentów?' where question_id='16bece38-eb48-4317-bb73-51b3ceb64b0f'::uuid and locale='pl' and question_text='Czy sztuczna inteligencja powinna móc podejmować decyzje medyczne na temat życia i śmierci?';
update question_translations set question_text='Czy jedzenie mięsa jest moralnie złe, skoro można jeść roślinnie?' where question_id='27771fe7-97a1-43bb-9cbd-097428493731'::uuid and locale='pl' and question_text='Czy jedzenie mięsa jest moralnie złe, skoro dostępne jest jedzenie roślinne?';
update question_translations set question_text='Czy to w porządku, że jedni zostają miliarderami, gdy inni głodują?' where question_id='5f63e9e9-4b46-49dc-9b4d-290d7b936de5'::uuid and locale='pl' and question_text='Czy powinno być możliwe zostanie miliarderem, podczas gdy inni głodują?';
update question_translations set question_text='Gdybyś mógł wymazać swoje najboleśniejsze wspomnienie, czy powinieneś to zrobić?' where question_id='15dc4795-292a-4b3b-9a8f-c49fa4fe3831'::uuid and locale='pl' and question_text='Gdybyś mógł usunąć swoje najbardziej bolesne wspomnienie, powinieneś?';
update question_translations set question_text='Czy oddanie starszego rodzica do domu opieki jest czymś złym?' where question_id='2fed91a2-f02a-4784-9b14-16164dfd7655'::uuid and locale='pl' and question_text='Czy to złe oddać starszego rodzica do domu opieki?';
update question_translations set question_text='Czy dzieci surowych rodziców osiągają w życiu więcej?' where question_id='3ae9a5c1-d0e4-4135-83bd-7e74e92e3891'::uuid and locale='pl' and question_text='Czy surowi rodzice wychowują bardziej udane dzieci?';
update question_translations set question_text='Czy winny jest ten, kto wykonał rozkaz, wiedząc, że jest zły?' where question_id='3f66582c-8790-414b-abfd-f8221a61107e'::uuid and locale='pl' and question_text='Czy ktoś jest winny, wykonując rozkazy, które uważał za złe?';
update question_translations set question_text='Czy łamanie zasad, by nakarmić głodującą rodzinę, jest czymś złym?' where question_id='4bc5e444-b207-4a03-a5d7-08667d78a4e6'::uuid and locale='pl' and question_text='Czy łamanie zasad, by nakarmić głodującą rodzinę, jest złem?';
update question_translations set question_text='Czy rodzic może słusznie podnieść głos na dziecko?' where question_id='52e8efef-aee4-4875-ade1-bfe5694bf029'::uuid and locale='pl' and question_text='Czy rodzic ma kiedykolwiek rację, podnosząc głos na dziecko?';
update question_translations set question_text='Gdybyś mógł się dowiedzieć, którego dnia umrzesz, chciałbyś to wiedzieć?' where question_id='579d535f-6f59-40f8-bf68-82b21cd19f9f'::uuid and locale='pl' and question_text='Gdybyś mógł poznać dokładny dzień swojej śmierci, chciałbyś go znać?';
update question_translations set question_text='Czy wydałbyś członka rodziny, który popełnił poważne przestępstwo?' where question_id='0cebc5c6-3921-417d-870c-5a354b47c6d5'::uuid and locale='pl' and question_text='Czy wydałbyś członka rodziny, który popełnił ciężki czyn?';
update question_translations set question_text='Czy intercyza kłóci się z prawdziwą miłością?' where question_id='6eff0771-65de-49c2-82b0-79e9e2bb6e46'::uuid and locale='pl' and question_text='Czy żądanie intercyzy zdradza brak prawdziwej miłości?';
update question_translations set question_text='Czy opowiadanie dzieciom pocieszających kłamstw o świecie jest złe?' where question_id='96eb43da-38e1-4b33-bacc-7763d0fe6de3'::uuid and locale='pl' and question_text='Czy to złe, by opowiadać dzieciom pocieszające kłamstwa o świecie?';
update question_translations set question_text='Czy wziąłbyś na siebie przestępstwo, którego nie popełniłeś, by chronić ukochaną osobę?' where question_id='9cb73e49-f1f0-4b68-9bf5-185f4df785e3'::uuid and locale='pl' and question_text='Czy przyznałbyś się do winy, której nie popełniłeś, by chronić kogoś, kogo kochasz?';
update question_translations set question_text='Czy można zniknąć bez słowa po trzech miesiącach randkowania?' where question_id='57d93dd4-a41f-48cc-8de5-ac2280ea0bd9'::uuid and locale='pl' and question_text='Czy można „zghostować" kogoś, z kim randkujesz od 3 miesięcy?';
update question_smaczki_translations st set text='Było między wami coś więcej?' from question_smaczki s where st.smaczek_id=s.id and s.question_id='57d93dd4-a41f-48cc-8de5-ac2280ea0bd9'::uuid and s.position=1 and st.locale='pl' and st.text='Byliście już intymni?';
update question_smaczki_translations st set text='Towary też jadą tymi drogami' from question_smaczki s where st.smaczek_id=s.id and s.question_id='23f0212c-93b8-4ac6-beed-b08694b88f7a'::uuid and s.position=1 and st.locale='pl' and st.text='Towary jadą drogami?';
update question_smaczki_translations st set text='Z czego będą żyć rolnicy?' from question_smaczki s where st.smaczek_id=s.id and s.question_id='27771fe7-97a1-43bb-9cbd-097428493731'::uuid and s.position=2 and st.locale='pl' and st.text='A ubodzy rolnicy?';
update question_smaczki_translations st set text='Dyscyplina się posypie?' from question_smaczki s where st.smaczek_id=s.id and s.question_id='3278873d-6d56-4b17-8611-29b8c717b325'::uuid and s.position=2 and st.locale='pl' and st.text='Rozpad dyscypliny?';
update question_smaczki_translations st set text='Szpitale i szkoły to udźwigną?' from question_smaczki s where st.smaczek_id=s.id and s.question_id='64942b79-9416-47ca-a4c1-71eabf70c25c'::uuid and s.position=1 and st.locale='pl' and st.text='Wydolność usług?';
update question_smaczki_translations st set text='Jak odsiać przestępców?' from question_smaczki s where st.smaczek_id=s.id and s.question_id='64942b79-9416-47ca-a4c1-71eabf70c25c'::uuid and s.position=2 and st.locale='pl' and st.text='Kontrola przestępców?';
update question_smaczki_translations st set text='A jeśli to choroba?' from question_smaczki s where st.smaczek_id=s.id and s.question_id='8b54aec1-b9a0-41b7-9a2d-766d886cfe50'::uuid and s.position=2 and st.locale='pl' and st.text='A choroba?';
update question_smaczki_translations st set text='Głosowanie na ślepo?' from question_smaczki s where st.smaczek_id=s.id and s.question_id='c1118fa8-c151-40c8-88cb-9d870779d444'::uuid and s.position=2 and st.locale='pl' and st.text='Niedoinformowani głosują?';
update question_smaczki_translations st set text='Związek to nie fuzja' from question_smaczki s where st.smaczek_id=s.id and s.question_id='049e8a14-65b7-466a-b613-f84a0abf80b3'::uuid and s.position=2 and st.locale='pl' and st.text='Wciąż masz siebie';
update question_smaczki_translations st set text='Bez niego nie byłbyś sobą' from question_smaczki s where st.smaczek_id=s.id and s.question_id='15dc4795-292a-4b3b-9a8f-c49fa4fe3831'::uuid and s.position=2 and st.locale='pl' and st.text='To uczyniło cię tobą';
update question_smaczki_translations st set text='Jedno życie kontra miliony?' from question_smaczki s where st.smaczek_id=s.id and s.question_id='17725e28-eb5e-4f79-bb0e-0a513103452b'::uuid and s.position=1 and st.locale='pl' and st.text='Jedna twarz nad tłumem?';
update question_smaczki_translations st set text='Równamy w dół?' from question_smaczki s where st.smaczek_id=s.id and s.question_id='406986a1-57b5-46e6-8a03-1530fd70f161'::uuid and s.position=2 and st.locale='pl' and st.text='Nas też pociąga w dół?';
update question_smaczki_translations st set text='Bez uprzedzeń, bez znajomości' from question_smaczki s where st.smaczek_id=s.id and s.question_id='474c1680-71cc-48b1-b67f-fe59f049725d'::uuid and s.position=1 and st.locale='pl' and st.text='Bez uprzedzeń, bez wyjątków';
update question_smaczki_translations st set text='A jeśli każdy tak zacznie?' from question_smaczki s where st.smaczek_id=s.id and s.question_id='4bc5e444-b207-4a03-a5d7-08667d78a4e6'::uuid and s.position=2 and st.locale='pl' and st.text='Zasady nagną się dla każdego?';
update question_smaczki_translations st set text='Tego zegara się nie odzobaczy' from question_smaczki s where st.smaczek_id=s.id and s.question_id='579d535f-6f59-40f8-bf68-82b21cd19f9f'::uuid and s.position=2 and st.locale='pl' and st.text='Zegar, którego nie odgonisz';
update question_smaczki_translations st set text='Obietnica, która coś znaczy' from question_smaczki s where st.smaczek_id=s.id and s.question_id='6541e3b7-2e5b-4658-9438-5076e49941ca'::uuid and s.position=2 and st.locale='pl' and st.text='Obietnica, która trzyma';
update question_smaczki_translations st set text='Odebrać mu pożegnanie?' from question_smaczki s where st.smaczek_id=s.id and s.question_id='68e3d717-7120-4b25-baab-e123a30af94a'::uuid and s.position=2 and st.locale='pl' and st.text='Odebrać im pożegnanie?';
update question_smaczki_translations st set text='Puszczasz to płazem?' from question_smaczki s where st.smaczek_id=s.id and s.question_id='6b9529be-05c0-446c-9a58-7d706aca77e4'::uuid and s.position=2 and st.locale='pl' and st.text='Puszczasz im płazem?';
update question_smaczki_translations st set text='Tego żąda sumienie?' from question_smaczki s where st.smaczek_id=s.id and s.question_id='6db69f39-d7c6-4b37-9e85-a954c927f9f6'::uuid and s.position=1 and st.locale='pl' and st.text='Sumienie żąda?';
update question_smaczki_translations st set text='Zakładasz porażkę?' from question_smaczki s where st.smaczek_id=s.id and s.question_id='6eff0771-65de-49c2-82b0-79e9e2bb6e46'::uuid and s.position=1 and st.locale='pl' and st.text='Planujesz porażkę?';
update question_smaczki_translations st set text='Pochować wszystkich, których kochasz?' from question_smaczki s where st.smaczek_id=s.id and s.question_id='74e30dde-61f9-4995-99ba-9a8a22eaa75d'::uuid and s.position=2 and st.locale='pl' and st.text='Pochować wszystkich, kogo kochasz?';
update question_smaczki_translations st set text='Stare schematy wracają' from question_smaczki s where st.smaczek_id=s.id and s.question_id='773f1b9c-e69b-4abf-8a23-5246c538f474'::uuid and s.position=2 and st.locale='pl' and st.text='Wzorce wracają';
update question_smaczki_translations st set text='Złamanego zaufania nie skleisz' from question_smaczki s where st.smaczek_id=s.id and s.question_id='8b97b981-a9f2-405f-b95b-2065b23bd9c0'::uuid and s.position=2 and st.locale='pl' and st.text='Raz złamane zaufanie';
update question_smaczki_translations st set text='Od czego są przyjaciele?' from question_smaczki s where st.smaczek_id=s.id and s.question_id='945cd618-3ce8-478e-8059-45673146cdc7'::uuid and s.position=1 and st.locale='pl' and st.text='Przyjaciel pomoże';
update question_smaczki_translations st set text='Poznać się można wszędzie' from question_smaczki s where st.smaczek_id=s.id and s.question_id='b1f26e52-5c76-46dd-bf70-7dd3edbc5114'::uuid and s.position=2 and st.locale='pl' and st.text='To po prostu nowa droga';
update question_smaczki_translations st set text='Zabić posłańca?' from question_smaczki s where st.smaczek_id=s.id and s.question_id='b354db77-0631-4036-b901-1e17f694c307'::uuid and s.position=2 and st.locale='pl' and st.text='Posłaniec zawsze winny?';
update question_smaczki_translations st set text='Tam opieka będzie lepsza?' from question_smaczki s where st.smaczek_id=s.id and s.question_id='2fed91a2-f02a-4784-9b14-16164dfd7655'::uuid and s.position=1 and st.locale='pl' and st.text='Lepsza opieka na miejscu?';
update question_smaczki_translations st set text='Wiedziałeś, że to złe' from question_smaczki s where st.smaczek_id=s.id and s.question_id='3f66582c-8790-414b-abfd-f8221a61107e'::uuid and s.position=2 and st.locale='pl' and st.text='Wiedziałeś swoje';
update question_smaczki_translations st set text='Fair pay for staff, always' from question_smaczki s where st.smaczek_id=s.id and s.question_id='89c2bb8f-0443-41b1-ab9b-c0f5528daa03'::uuid and s.position=1 and st.locale='en' and st.text='Their life, their call';
update question_smaczki_translations st set text='Obsługa zawsze dostanie swoje' from question_smaczki s where st.smaczek_id=s.id and s.question_id='89c2bb8f-0443-41b1-ab9b-c0f5528daa03'::uuid and s.position=1 and st.locale='pl' and st.text='Ich życie, ich wybór';
update question_smaczki_translations st set text='A tip must be earned' from question_smaczki s where st.smaczek_id=s.id and s.question_id='89c2bb8f-0443-41b1-ab9b-c0f5528daa03'::uuid and s.position=2 and st.locale='en' and st.text='Care means speaking up?';
update question_smaczki_translations st set text='Na napiwek trzeba zasłużyć' from question_smaczki s where st.smaczek_id=s.id and s.question_id='89c2bb8f-0443-41b1-ab9b-c0f5528daa03'::uuid and s.position=2 and st.locale='pl' and st.text='Troska to odwaga mówić?';
update question_translations set question_text='Czy rzecz robiona powoli, ręcznie, jest warta więcej niż idealny produkt z masowej produkcji?' where question_id='b9e1471c-7d17-4fc1-9863-2249114bfd47'::uuid and locale='pl' and question_text='Czy rzecz robiona powoli ręką jest warta więcej niż idealna z masowej produkcji?';
update question_translations set question_text='Gdybyś mógł na zawsze pozostać fizycznie trzydziestolatkiem, czy byś chciał?' where question_id='c4fbed60-ab48-4f03-831f-0d2ec937e739'::uuid and locale='pl' and question_text='Gdybyś mógł na zawsze zostać fizycznie trzydziestolatkiem, powinieneś?';
update question_translations set question_text='Czy dorosłe dzieci mają obowiązek opiekować się starzejącymi się rodzicami?' where question_id='d64bc98c-d637-4bf9-8dba-f911c7ecf294'::uuid and locale='pl' and question_text='Czy dorosłe dzieci są winne opiekę starzejącym się rodzicom?';
update question_translations set question_text='Czy pracownik powinien mieć prawo ignorować wszystkie wiadomości z pracy po godzinach?' where question_id='0eb5cdb9-c34c-43dd-b317-367d24aa2124'::uuid and locale='pl' and question_text='Czy pracownik powinien mieć prawo olać wszystkie wiadomości z pracy po godzinach?';
update question_smaczki_translations st set text='Chcę zasuwać — moja sprawa' from question_smaczki s where st.smaczek_id=s.id and s.question_id='640b34a4-01c5-48ee-819e-c79e5556337d'::uuid and s.position=2 and st.locale='pl' and st.text='Daj mi haratać, jeśli chcę';
update question_smaczki_translations st set text='Łatwa wymówka, żeby urwać się z pracy' from question_smaczki s where st.smaczek_id=s.id and s.question_id='c1f648fa-0dfc-40e5-abba-cebed819189a'::uuid and s.position=2 and st.locale='pl' and st.text='Łatwa wymówka, żeby olać pracę';
update question_translations set question_text='Czy zaufałbyś robotowi jako głównemu opiekunowi twojego starszego rodzica?' where question_id='e11f4d4f-b743-49ab-93d3-68ab6406896f'::uuid and locale='pl' and question_text='Czy zaufałbyś robotowi jako głównemu opiekunowi twojego starego rodzica?';
update question_translations set question_text='Czy dni z odstępstwem to mądra część zdrowej diety?' where question_id='4136eed0-9962-43a7-b443-fda38826ad88'::uuid and locale='pl' and question_text='Czy dni na luzie to mądra część zdrowej diety?';
update question_smaczki_translations st set text='Na zmarszczki się zasługuje?' from question_smaczki s where st.smaczek_id=s.id and s.question_id='6859c462-8a50-4fc1-9e14-6af69586f798'::uuid and s.position=1 and st.locale='pl' and st.text='Zmarszczki się zasługuje?';
update question_translations set question_text='Czy powinieneś porównywać dziecko z bardziej udanym rodzeństwem?' where question_id='b283445b-e820-4843-b039-fac5108f00f4'::uuid and locale='pl' and question_text='Czy powinieneś porównywać dziecko do bardziej udanego rodzeństwa?';
update question_translations set question_text='Czy rodzice mają obowiązek pomóc dzieciom w opłaceniu edukacji?' where question_id='290fd57b-b838-4183-8af4-71c95542cb34'::uuid and locale='pl' and question_text='Czy rodzice są winni dzieciom pomoc w opłaceniu edukacji?';
update question_translations set question_text='Czy dorosły śpiący z pluszakiem z dzieciństwa nie ma nic do ukrycia?' where question_id='6317d6de-2087-4d38-88eb-ca01f43767a8'::uuid and locale='pl' and question_text='Czy dorosły śpiący z pluszakiem z dzieciństwa nie ma czego ukrywać?';

commit;
